---
permalink: audit/accessing-audit-log-file.html 
sidebar: sidebar 
keywords: storagegrid, audit, log, log file, access, accessing 
summary: O compartilhamento de auditoria contém o arquivo audit.log ativo e todos os arquivos de log de auditoria compatados. Você pode acessar arquivos de log de auditoria diretamente da linha de comando do nó Admin. 
---
= Acessar o arquivo de log de auditoria
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O compartilhamento de auditoria contém o arquivo ativo `audit.log` e todos os arquivos de log de auditoria compatados. Você pode acessar arquivos de log de auditoria diretamente da linha de comando do nó Admin.

O `audit.log` o arquivo permanece vazio, a menos que você configure o StorageGRID para *Nós de administração/nós locais* ou *Nó de administração e servidor syslog externo*. Para mais informações, consulte link:../monitor/configure-log-management.html#select-log-location["Selecione o local do log"] .

.Antes de começar
* Você link:../admin/admin-group-permissions.html["permissões de acesso específicas"]tem .
* Tem de ter o `Passwords.txt` ficheiro.
* Você deve saber o endereço IP de um nó Admin.


.Passos
. Faça login em um nó Admin:
+
.. Introduza o seguinte comando: `ssh admin@_primary_Admin_Node_IP_`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
.. Digite o seguinte comando para mudar para root: `su -`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
+
Quando você estiver conetado como root, o prompt mudará de `$` para `#`.



. Vá para o diretório que contém os arquivos de log de auditoria:
+
`cd  /var/local/audit/export/`

. Visualize o ficheiro de registo de auditoria atual ou guardado, conforme necessário.

