---
permalink: audit/audit-log-file-rotation.html 
sidebar: sidebar 
keywords: storagegrid, audit, log file, audit.log, audit.log file, rotation, save, autosave, auto save, auto-save 
summary: Os arquivos de logs de auditoria são salvos no diretório /var/local/audit/export/ de um nó de administração.  Os arquivos de log de auditoria ativos são chamados audit.log. 
---
= Rotação do arquivo de log de auditoria
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se o StorageGRID estiver configurado para *Nós de administração/nós locais* ou *Nó de administração e servidor syslog externo*, os arquivos de logs de auditoria serão salvos no nó de administração `/var/local/audit/export/` diretório.  Os arquivos de log de auditoria ativos são nomeados `audit.log` .


NOTE: Opcionalmente, você pode alterar o destino dos logs de auditoria e enviar informações de auditoria para um servidor syslog externo.  Os logs locais dos registros de auditoria continuam sendo gerados e armazenados quando um servidor syslog externo é configurado. Consulte link:../monitor/configure-audit-messages.html["Configurar mensagens de auditoria e servidor syslog externo"] .

Uma vez por dia, o arquivo ativo `audit.log` é salvo e um novo `audit.log` arquivo é iniciado. O nome do ficheiro guardado indica quando foi guardado, no formato `_yyyy-mm-dd.txt_`. Se mais de um log de auditoria for criado em um único dia, os nomes de arquivo usarão a data em que o arquivo foi salvo, anexado por um número, no formato `_yyyy-mm-dd.txt.n_`. Por exemplo, `2018-04-15.txt` e `2018-04-15.txt.1` são os primeiros e segundos arquivos de log criados e salvos em 15 de abril de 2018.

Após um dia, o arquivo salvo é compactado e renomeado, no formato `_yyyy-mm-dd.txt.gz_` , que preserva a data original.  Com o tempo, o armazenamento do nó de administração alocado para logs de auditoria é consumido.  Um script monitora o consumo de espaço do log de auditoria e exclui os arquivos de log conforme necessário para liberar espaço no `/var/local/audit/export/` diretório.  Os logs de auditoria são excluídos com base na data em que foram criados.  Os logs mais antigos são excluídos primeiro.  Você pode monitorar as ações do script no seguinte arquivo: `/var/local/log/manage-audit.log` .

Este exemplo mostra o `audit.log` ficheiro ativo, o ficheiro do dia anterior (`2018-04-15.txt`) e o ficheiro comprimido para o dia anterior (`2018-04-14.txt.gz`).

[listing]
----
audit.log
2018-04-15.txt
2018-04-14.txt.gz
----