---
permalink: audit/data-types.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, data, types, UI32, UI64, FC32, IPAD, CSTR, IPAD 
summary: Diferentes tipos de dados são usados para armazenar informações em mensagens de auditoria. 
---
= Tipos de dados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diferentes tipos de dados são usados para armazenar informações em mensagens de auditoria.

[cols="1a,4a"]
|===
| Tipo | Descrição 


 a| 
UI32
 a| 
Inteiro longo não assinado (32 bits); ele pode armazenar os números de 0 a 4.294.967.295.



 a| 
UI64
 a| 
Número inteiro duplo longo não assinado (64 bits); pode armazenar os números de 0 a 18.446.744.073.709.551.615.



 a| 
FC32
 a| 
Constante de quatro carateres; um valor inteiro não assinado de 32 bits representado como quatro carateres ASCII, como "ABCD".



 a| 
IPAD
 a| 
Usado para endereços IP.



 a| 
CSTR
 a| 
Um array de comprimento variável de carateres UTF-8. Os carateres podem ser escapados com as seguintes convenções:

* Barra invertida é.
* O retorno do carro é r.
* Aspas duplas.
* A alimentação de linha (nova linha) é n.
* Os carateres podem ser substituídos por seus equivalentes hexadecimais (no formato HH, onde HH é o valor hexadecimal que representa o caractere).


|===