---
permalink: audit/metadata-update-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, Metadata update, S3 metadata update, SUPD 
summary: As mensagens de auditoria são geradas quando um cliente S3 atualiza os metadados de um objeto. 
---
= Mensagens de atualização de metadados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As mensagens de auditoria são geradas quando um cliente S3 atualiza os metadados de um objeto.



== Mensagens de auditoria de atualização de metadados do S3

[cols="1a,1a,2a,1a,2a"]
|===
| Código | Nome | Descrição | Traçado | Consulte 


 a| 
SUPD
 a| 
S3 metadados atualizados
 a| 
Gerado quando um cliente S3 atualiza os metadados de um objeto ingerido.
 a| 
CBID, S3KY, HTRH
 a| 
link:supd-s3-metadata-updated.html["SUPD: S3 metadados atualizados"]

|===


== Exemplo: Atualização de metadados S3

O exemplo mostra uma transação bem-sucedida para atualizar os metadados de um objeto S3 existente.



=== SUPD: Atualização de metadados S3

O cliente S3 faz uma solicitação (SUPD) para atualizar os metadados especificados (`x-amz-meta-\*`) para o objeto S3 (S3KY). Neste exemplo, cabeçalhos de solicitação são incluídos no campo HTRH porque ele foi configurado como um cabeçalho de protocolo de auditoria (**CONFIGURAÇÃO** > **Monitoramento** > **Auditoria e servidor syslog**). link:../monitor/configure-audit-messages.html["Configurar mensagens de auditoria e destinos de log"]Consulte .

[listing]
----
2017-07-11T21:54:03.157462 [AUDT:[RSLT(FC32):SUCS][TIME(UI64):17631][SAIP(IPAD):"10.96.100.254"]
[HTRH(CSTR):"{\"accept-encoding\":\"identity\",\"authorization\":\"AWS LIUF17FGJARQHPY2E761:jul/hnZs/uNY+aVvV0lTSYhEGts=\",
\"content-length\":\"0\",\"date\":\"Tue, 11 Jul 2017 21:54:03 GMT\",\"host\":\"10.96.99.163:18082\",
\"user-agent\":\"aws-cli/1.9.20 Python/2.7.6 Linux/3.13.0-119-generic botocore/1.3.20\",
\"x-amz-copy-source\":\"/testbkt1/testobj1\",\"x-amz-metadata-directive\":\"REPLACE\",\"x-amz-meta-city\":\"Vancouver\"}"]
[S3AI(CSTR):"20956855414285633225"][SACC(CSTR):"acct1"][S3AK(CSTR):"SGKHyyv9ZQqWRbJSQc5vI7mgioJwrdplShE02AUaww=="]
[SUSR(CSTR):"urn:sgws:identity::20956855414285633225:root"]
[SBAI(CSTR):"20956855414285633225"][SBAC(CSTR):"acct1"][S3BK(CSTR):"testbkt1"]
[S3KY(CSTR):"testobj1"][CBID(UI64):0xCB1D5C213434DD48][CSIZ(UI64):10][AVER(UI32):10]
[ATIM(UI64):1499810043157462][ATYP(FC32):SUPD][ANID(UI32):12258396][AMID(FC32):S3RQ]
[ATID(UI64):8987436599021955788]]
----