---
permalink: audit/sade-security-audit-enable.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SADE, Security Audit Enable 
summary: 'Esta mensagem indica que o serviço de origem "(ID do nó) restaurou o registo de mensagens de auditoria; as mensagens de auditoria estão novamente a ser recolhidas e entregues.' 
---
= SADE: Ativação da auditoria de segurança
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esta mensagem indica que o serviço de origem (ID do nó) restaurou o registo de mensagens de auditoria; as mensagens de auditoria estão novamente a ser recolhidas e entregues.

[cols="1a,1a,4a"]
|===
| Código | Campo | Descrição 


 a| 
AETM
 a| 
Ativar método
 a| 
O método utilizado para ativar a auditoria.



 a| 
AEUN
 a| 
Nome de utilizador
 a| 
O nome de usuário que executou o comando para ativar o log de auditoria.



 a| 
RSLT
 a| 
Resultado
 a| 
Este campo tem o valor NENHUM. RSLT é um campo de mensagem obrigatório, mas não é relevante para esta mensagem. NENHUM é usado em vez DE SUCS para que esta mensagem não seja filtrada.

|===
A mensagem implica que o registo foi anteriormente desativado (SADD), mas foi agora restaurado. Isso geralmente é usado apenas durante a ingestão em massa para melhorar o desempenho do sistema. Após a atividade em massa, a auditoria é restaurada e a capacidade de desativar a auditoria é então permanentemente bloqueada.
