---
permalink: audit/syst-node-stopping.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SYST, Node Stopping 
summary: 'Quando um serviço é parado graciosamente, essa mensagem é gerada para indicar que o desligamento foi solicitado e que o serviço iniciou sua sequência de desligamento. O SISTEMA pode ser usado para determinar se o desligamento foi solicitado, antes que o serviço seja reiniciado (ao contrário do SYSD, que é normalmente enviado após o reinício do serviço).' 
---
= SIST: Paragem do nó
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando um serviço é parado graciosamente, essa mensagem é gerada para indicar que o desligamento foi solicitado e que o serviço iniciou sua sequência de desligamento. O SYST pode ser usado para determinar se o desligamento foi solicitado, antes que o serviço seja reiniciado (ao contrário do SYSD, que normalmente é enviado após o reinício do serviço).

[cols="1a,1a,4a"]
|===
| Código | Campo | Descrição 


 a| 
RSLT
 a| 
Limpar encerramento
 a| 
A natureza do desligamento:

SUCS: O sistema foi desligado de forma limpa.

|===
A mensagem não indica se o servidor host está sendo interrompido, apenas o serviço de relatórios. O código RSLT de uma mensagem DO SISTEMA não pode indicar um desligamento "sujo", porque a mensagem é gerada apenas por desligamentos "limpos".
