---
permalink: audit/wput-swift-put.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, WPUT, Swift PUT 
summary: Quando um cliente Swift emite uma transação PUT, uma solicitação é feita para criar um novo objeto ou contentor. Esta mensagem é emitida pelo servidor se a transação for bem-sucedida. 
---
= WPUT: Swift PUT
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando um cliente Swift emite uma transação PUT, uma solicitação é feita para criar um novo objeto ou contentor. Esta mensagem é emitida pelo servidor se a transação for bem-sucedida.

[cols="1a,1a,4a"]
|===
| Código | Campo | Descrição 


 a| 
CBID
 a| 
Identificador do bloco de conteúdo
 a| 
O identificador exclusivo do bloco de conteúdo solicitado. Se o CBID for desconhecido, este campo é definido como 0. As operações em contentores não incluem este campo.



 a| 
CSIZ
 a| 
Tamanho do conteúdo
 a| 
O tamanho do objeto recuperado em bytes. As operações em contentores não incluem este campo.



 a| 
HTRH
 a| 
Cabeçalho de solicitação HTTP
 a| 
Lista de nomes e valores de cabeçalho de solicitação HTTP registrados, conforme selecionado durante a configuração.

 `X-Forwarded-For` É incluído automaticamente se estiver presente na solicitação e se o `X-Forwarded-For` valor for diferente do endereço IP do remetente da solicitação (campo de auditoria SAIP).



 a| 
MTME
 a| 
Hora da última modificação
 a| 
O timestamp Unix, em microssegundos, indicando quando o objeto foi modificado pela última vez.



 a| 
RSLT
 a| 
Código do resultado
 a| 
Resultado da transação PUT. O resultado é sempre:

SUCS: Bem-sucedido



 a| 
SAIP
 a| 
Endereço IP do cliente solicitante
 a| 
O endereço IP do aplicativo cliente que fez a solicitação.



 a| 
TEMPO
 a| 
Tempo
 a| 
Tempo total de processamento da solicitação em microssegundos.



 a| 
TLIP
 a| 
Endereço IP do balanceador de carga confiável
 a| 
Se a solicitação foi roteada por um balanceador de carga confiável da camada 7, o endereço IP do balanceador de carga.



 a| 
UUID
 a| 
Identificador universal único
 a| 
O identificador do objeto dentro do sistema StorageGRID.



 a| 
WACC
 a| 
ID da conta Swift
 a| 
O ID exclusivo da conta, conforme especificado pelo sistema StorageGRID.



 a| 
WCON
 a| 
Contentor Swift
 a| 
O nome do contentor Swift.



 a| 
WOBJ
 a| 
Objeto Swift
 a| 
O identificador de objeto Swift. As operações em contentores não incluem este campo.



 a| 
WUSR
 a| 
Usuário da conta Swift
 a| 
O nome de usuário da conta Swift que identifica exclusivamente o cliente que realiza a transação.

|===