---
permalink: swnodes/collecting-information-about-your-deployment-environment.html 
sidebar: sidebar 
keywords: how to collect information about your vmware deployment environment 
summary: Antes de implantar nós de grade, você deve coletar informações sobre a configuração de rede e o ambiente VMware. 
---
= Colete informações sobre seu ambiente de implantação (VMware)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de implantar nós de grade, você deve coletar informações sobre a configuração de rede e o ambiente VMware.


NOTE: É mais eficiente executar uma única instalação de todos os nós, em vez de instalar alguns nós agora e alguns nós depois.



== Informações da VMware

Você deve acessar o ambiente de implantação e coletar informações sobre o ambiente VMware, as redes criadas para as redes Grid, Admin e Client e os tipos de volume de armazenamento que você planeja usar para os nós de armazenamento.

Você deve coletar informações sobre seu ambiente VMware, incluindo o seguinte:

* O nome de usuário e a senha de uma conta do VMware vSphere que tem permissões apropriadas para concluir a implantação.
* Informações de configuração de host, datastore e rede para cada máquina virtual de nó StorageGRID.



NOTE: O VMware Live vMotion faz com que o tempo do relógio da máquina virtual salte e não é suportado para nós de grade de qualquer tipo. Embora raros, tempos de clock incorretos podem resultar em perda de dados ou atualizações de configuração.



== Informações da rede de grelha

Você deve coletar informações sobre a rede da VMware criada para a rede de grade do StorageGRID (obrigatório), incluindo:

* O nome da rede.
* O método utilizado para atribuir endereços IP, estáticos ou DHCP.
+
** Se você estiver usando endereços IP estáticos, os detalhes de rede necessários para cada nó de grade (endereço IP, gateway, máscara de rede).
** Se estiver a utilizar DHCP, o endereço IP do nó de administração principal na rede de grelha. Consulte link:how-grid-nodes-discover-primary-admin-node.html["Como os nós de grade descobrem o nó de administração principal"] para obter mais informações.






== Informações da rede de administração

Para nós que serão conetados à rede de administração StorageGRID opcional, você deve coletar informações sobre a rede VMware criada para essa rede, incluindo:

* O nome da rede.
* O método utilizado para atribuir endereços IP, estáticos ou DHCP.
+
** Se você estiver usando endereços IP estáticos, os detalhes de rede necessários para cada nó de grade (endereço IP, gateway, máscara de rede).
** Se estiver a utilizar DHCP, o endereço IP do nó de administração principal na rede de grelha. Consulte link:how-grid-nodes-discover-primary-admin-node.html["Como os nós de grade descobrem o nó de administração principal"] para obter mais informações.


* A lista de sub-rede externa (ESL) para a rede de administração.




== Informações da rede do cliente

Para os nós que serão conetados à rede cliente StorageGRID opcional, você deve coletar informações sobre a rede VMware criada para essa rede, incluindo:

* O nome da rede.
* O método utilizado para atribuir endereços IP, estáticos ou DHCP.
* Se você estiver usando endereços IP estáticos, os detalhes de rede necessários para cada nó de grade (endereço IP, gateway, máscara de rede).




== Informações sobre interfaces adicionais

Opcionalmente, você pode adicionar interfaces de tronco ou acesso à VM no vCenter após instalar o nó. Por exemplo, você pode querer adicionar uma interface de tronco a um Admin ou Gateway Node, para que você possa usar interfaces VLAN para segregar o tráfego que pertence a diferentes aplicativos ou locatários. Ou, talvez você queira adicionar uma interface de acesso para usar em um grupo de alta disponibilidade (HA).

As interfaces adicionadas são exibidas na página interfaces VLAN e na página grupos HA no Gerenciador de Grade.

* Se você adicionar uma interface de tronco, configure uma ou mais interfaces VLAN para cada nova interface pai. link:../admin/configure-vlan-interfaces.html["Configurar interfaces VLAN"]Consulte .
* Se você adicionar uma interface de acesso, será necessário adicioná-la diretamente aos grupos de HA. link:../admin/configure-high-availability-group.html["configurar grupos de alta disponibilidade"]Consulte .




== Volumes de storage para nós de storage virtual

Você deve coletar as seguintes informações para nós de storage baseados em máquina virtual:

* O número e o tamanho dos volumes de armazenamento (LUNs de armazenamento) que pretende adicionar. link:storage-and-performance-requirements.html["Requisitos de storage e desempenho"]Consulte .




== Informações de configuração da grade

Você deve coletar informações para configurar sua grade:

* Licença de grade
* Endereços IP do servidor NTP (Network Time Protocol)
* Endereços IP do servidor DNS

