---
permalink: swnodes/cpu-and-ram-requirements.html 
sidebar: sidebar 
keywords: cpu, ram, cpu cores 
summary: Antes de instalar o software StorageGRID, verifique e configure o hardware para que ele esteja pronto para suportar o sistema StorageGRID. 
---
= Requisitos de CPU e RAM para StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar o software StorageGRID, verifique e configure o hardware para que ele esteja pronto para suportar o sistema StorageGRID.

Cada nó do StorageGRID requer os seguintes recursos mínimos:

* Núcleos de CPU: 8 por nó
* RAM: Depende do total de RAM disponível e da quantidade de software que não seja StorageGRID executado no sistema
+
** Geralmente, pelo menos 24 GB por nó e 2 a 16 GB menos do que a RAM total do sistema
** Se vários locatários tiverem até 5.000 buckets cada, pelo menos 64 GB por nó
+

NOTE: O sistema StorageGRID suporta um máximo de 20.000 buckets para cada conta de locatário S3.





Os recursos de nó somente de metadados baseados em software devem corresponder aos recursos dos nós de storage existentes. Por exemplo:

* Se o local do StorageGRID existente estiver usando dispositivos SG6000 ou SG6100, os nós somente de metadados baseados em software deverão atender aos seguintes requisitos mínimos:
+
** 128 GB DE RAM
** CPU de 8 núcleos
** SSD de 8 TB ou armazenamento equivalente para o banco de dados Cassandra (rangedb/0)


* Se o site StorageGRID existente estiver usando nós de armazenamento virtuais com 24 GB de RAM, CPU de 8 núcleos e 3 TB ou 4 TB de armazenamento de metadados, os nós somente de metadados baseados em software deverão usar recursos semelhantes (24 GB de RAM, CPU de 8 núcleos e 4 TB de armazenamento de metadados (rangedb/0)).


Ao adicionar um novo site StorageGRID, a capacidade total de metadados do novo local deve, no mínimo, corresponder aos locais StorageGRID existentes e os novos recursos do local devem corresponder aos nós de storage nos locais StorageGRID existentes.


NOTE: "Linux" refere-se a uma implantação RHEL, Ubuntu ou Debian.  Para obter uma lista de versões suportadas, consulte o https://imt.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade NetApp (IMT)"^] .

[role="tabbed-block"]
====
.Linux
--
Certifique-se de que o número de nós de StorageGRID que você planeja executar em cada host físico ou virtual não exceda o número de núcleos de CPU ou a RAM física disponível. Se os hosts não forem dedicados à execução do StorageGRID (não recomendado), certifique-se de considerar os requisitos de recursos dos outros aplicativos.

--
.VMware
--
A VMware oferece suporte a um nó por máquina virtual. Certifique-se de que o nó StorageGRID não exceda a RAM física disponível. Cada máquina virtual deve ser dedicada à execução do StorageGRID.

--
====

CAUTION: Monitore regularmente o uso de CPU e memória para garantir que esses recursos continuem a acomodar sua carga de trabalho. Por exemplo, dobrar a alocação de RAM e CPU para nós de armazenamento virtuais forneceria recursos semelhantes aos fornecidos para nós de appliance StorageGRID. Além disso, se a quantidade de metadados por nó exceder 500 GB, considere aumentar a RAM por nó para 48 GB ou mais. Para obter informações sobre como gerenciar o armazenamento de metadados de objetos, aumentar a configuração de Espaço Reservado para Metadados e monitorar o uso de CPU e memória, consulte as instruções para link:../admin/index.html["administrar"], link:../monitor/index.html["monitorização"] e link:../upgrade/index.html["a atualizar"] StorageGRID.

Se o hyperthreading estiver habilitado nos hosts físicos subjacentes, você poderá fornecer 8 núcleos virtuais (4 núcleos físicos) por nó. Se o hyperthreading não estiver habilitado nos hosts físicos subjacentes, você deverá fornecer 8 núcleos físicos por nó.

Se você estiver usando máquinas virtuais como hosts e tiver controle sobre o tamanho e o número de VMs, use uma única VM para cada nó do StorageGRID e dimensione a VM de acordo.

(Somente RHEL, Debian e Ubuntu) Para implantações de produção, você não deve executar vários nós de armazenamento no mesmo hardware de armazenamento físico ou host virtual.  Cada nó de armazenamento em uma única implantação do StorageGRID deve estar em seu próprio domínio de falha isolado.  Você pode maximizar a durabilidade e a disponibilidade dos dados do objeto se garantir que uma única falha de hardware possa afetar apenas um único nó de armazenamento.

Consulte link:storage-and-performance-requirements.html["Requisitos de storage e desempenho"].
