---
permalink: swnodes/creating-node-configuration-files.html 
sidebar: sidebar 
keywords: how to create rhel ubuntu or debian node configuration files, port, remap, port remap 
summary: Os arquivos de configuração de nó são pequenos arquivos de texto que fornecem as informações que o serviço de host do StorageGRID precisa para iniciar um nó e conectá-lo à rede apropriada e bloquear recursos de armazenamento. Os arquivos de configuração de nós são usados para nós virtuais e não são usados para nós do dispositivo. 
---
= Criar arquivos de configuração de nó para implantações Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os arquivos de configuração de nó são pequenos arquivos de texto que fornecem as informações que o serviço de host do StorageGRID precisa para iniciar um nó e conectá-lo à rede apropriada e bloquear recursos de armazenamento. Os arquivos de configuração de nós são usados para nós virtuais e não são usados para nós do dispositivo.


NOTE: "Linux" refere-se a uma implantação RHEL, Ubuntu ou Debian.  Para obter uma lista de versões suportadas, consulte o https://imt.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade NetApp (IMT)"^] .



== Local para arquivos de configuração de nó

Coloque o arquivo de configuração para cada nó do StorageGRID `/etc/storagegrid/nodes` no diretório no host onde o nó será executado. Por exemplo, se você planeja executar um nó de administrador, um nó de gateway e um nó de armazenamento no HostA, você deve colocar três arquivos de configuração de nó no `/etc/storagegrid/nodes` HostA.

Você pode criar os arquivos de configuração diretamente em cada host usando um editor de texto, como vim ou nano, ou você pode criá-los em outro lugar e movê-los para cada host.



== Nomenclatura de arquivos de configuração de nó

Os nomes dos arquivos de configuração são significativos. O formato é `node-name.conf`, onde `node-name` é um nome atribuído ao nó. Esse nome aparece no Instalador do StorageGRID e é usado para operações de manutenção de nós, como a migração de nós.

Os nomes dos nós devem seguir estas regras:

* Deve ser único
* Deve começar com uma letra
* Pode conter os carateres De A a Z e de a a z
* Pode conter os números de 0 a 9
* Pode conter um ou mais hífens (-)
* Não deve ter mais de 32 carateres, não incluindo a `.conf` extensão


Quaisquer arquivos `/etc/storagegrid/nodes` que não sigam essas convenções de nomenclatura não serão analisados pelo serviço host.

Se você tiver uma topologia de vários locais planejada para sua grade, um esquema típico de nomes de nós pode ser:

`site-nodetype-nodenumber.conf`

Por exemplo, você pode usar `dc1-adm1.conf` para o primeiro nó de administrador no data center 1 e `dc2-sn3.conf` para o terceiro nó de storage no data center 2. No entanto, você pode usar qualquer esquema que desejar, desde que todos os nomes de nós sigam as regras de nomenclatura.



== Conteúdo de um arquivo de configuração de nó

Um arquivo de configuração contém pares chave/valor, com uma chave e um valor por linha. Para cada par chave/valor, siga estas regras:

* A chave e o valor devem ser separados por um sinal igual (`=`) e espaço em branco opcional.
* As teclas não podem conter espaços.
* Os valores podem conter espaços incorporados.
* Qualquer espaço em branco à frente ou à direita é ignorado.


A tabela a seguir define os valores para todas as chaves suportadas. Cada chave tem uma das seguintes designações:

* *Obrigatório*: Necessário para cada nó ou para os tipos de nó especificados
* *Melhor prática*: Opcional, embora recomendado
* *Opcional*: Opcional para todos os nós




=== Teclas de rede Admin



==== ADMIN_IP

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Endereço IPv4 da rede Grid do nó de administração que você deseja usar para instalar o nó baseado em Linux.  Para recuperação, use o IP do nó de administração primário, se disponível; caso contrário, use o IP de um nó de administração não primário.  Se você omitir esse parâmetro, o nó tentará descobrir um nó de administração primário usando mDNS.

link:how-grid-nodes-discover-primary-admin-node.html["Como os nós de grade descobrem o nó de administração principal"]

*Nota*: Este valor é ignorado, e pode ser proibido, no nó Admin principal.
 a| 
Prática recomendada

|===


==== ADMIN_NETWORK_CONFIG

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
DHCP, ESTÁTICO OU DESATIVADO
 a| 
Opcional

|===


==== ADMIN_NETWORK_ESL

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Lista de sub-redes separadas por vírgulas na notação CIDR à qual esse nó deve se comunicar usando o gateway de rede Admin.

Exemplo: `172.16.0.0/21,172.17.0.0/21`
 a| 
Opcional

|===


==== ADMIN_NETWORK_GATEWAY

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Endereço IPv4 do gateway de rede de administração local para este nó. Deve estar na sub-rede definida por ADMIN_network_IP e ADMIN_network_MASK. Este valor é ignorado para redes configuradas por DHCP.

Exemplos:

`1.1.1.1`

`10.224.4.81`
 a| 
Obrigatório se `ADMIN_NETWORK_ESL` for especificado. Opcional caso contrário.

|===


==== ADMIN_NETWORK_IP

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Endereço IPv4 deste nó na rede Admin. Esta chave só é necessária quando ADMIN_NETWORK_CONFIG é ESTÁTICA; não a especifique para outros valores.

Exemplos:

`1.1.1.1`

`10.224.4.81`
 a| 
Necessário quando ADMIN_NETWORK_CONFIG é ESTÁTICO.

Opcional caso contrário.

|===


==== ADMIN_NETWORK_MAC

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
O endereço MAC da interface de rede de administração no contentor.

Este campo é opcional. Se omitido, um endereço MAC será gerado automaticamente.

Deve ser 6 pares de dígitos hexadecimais separados por dois pontos.

Exemplo: `b2:9c:02:c2:27:10`
 a| 
Opcional

|===


==== ADMIN_NETWORK_MASK

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
IPv4 máscara de rede para este nó, na rede Admin. Especifique esta chave quando ADMIN_NETWORK_CONFIG estiver ESTÁTICA; não a especifique para outros valores.

Exemplos:

`255.255.255.0`

`255.255.248.0`
 a| 
Necessário se Admin_network_IP for especificado e ADMIN_network_CONFIG for ESTÁTICO.

Opcional caso contrário.

|===


==== ADMIN_NETWORK_MTU

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
A unidade de transmissão máxima (MTU) para este nó na rede Admin. Não especifique se ADMIN_NETWORK_CONFIG é DHCP. Se especificado, o valor deve estar entre 1280 e 9216. Se omitido, 1500 é usado.

Se você quiser usar quadros jumbo, defina o MTU para um valor adequado para quadros jumbo, como 9000. Caso contrário, mantenha o valor padrão.

*IMPORTANTE*: O valor MTU da rede deve corresponder ao valor configurado na porta do switch à qual o nó está conetado. Caso contrário, problemas de desempenho da rede ou perda de pacotes podem ocorrer.

Exemplos:

`1500`

`8192`
 a| 
Opcional

|===


==== ADMIN_NETWORK_TARGET

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Nome do dispositivo host que você usará para acesso à rede de administração pelo nó StorageGRID. Apenas são suportados nomes de interface de rede. Normalmente, você usa um nome de interface diferente do que foi especificado para GRID_NETWORK_TARGET ou CLIENT_network_TARGET.

*Nota*: Não use dispositivos bond ou bridge como destino de rede. Configure uma VLAN (ou outra interface virtual) em cima do dispositivo de ligação ou use um par bridge e Ethernet virtual (vete).

*Prática recomendada*:Especifique um valor mesmo que este nó não tenha inicialmente um endereço IP de rede Admin. Em seguida, você pode adicionar um endereço IP de rede Admin mais tarde, sem ter que reconfigurar o nó no host.

Exemplos:

`bond0.1002`

`ens256`
 a| 
Prática recomendada

|===


==== ADMIN_NETWORK_TARGET_TYPE

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Interface (este é o único valor suportado.)
 a| 
Opcional

|===


==== ADMIN_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Verdadeiro ou Falso

Defina a chave como "true" para fazer com que o contentor StorageGRID use o endereço MAC da interface de destino do host na rede de administração.

*Prática recomendada:* em redes onde o modo promíscuo seria necessário, use a chave ADMIN_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC em vez disso.

Para mais detalhes sobre clonagem de MAC para Linux, consultelink:../swnodes/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Considerações e recomendações para clonagem de endereços MAC"]
 a| 
Prática recomendada

|===


==== ADMIN_ROLE

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Primário ou não primário

Esta chave só é necessária quando NODE_TYPE: VM_Admin_Node; não a especifique para outros tipos de nó.
 a| 
Obrigatório quando NODE_TYPE é VM_Admin_Node

Opcional caso contrário.

|===


=== Bloquear chaves de dispositivo



==== BLOCK_DEVICE_AUDIT_LOGS

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Caminho e nome do arquivo especial do dispositivo de bloco que este nó usará para armazenamento persistente de logs de auditoria.

Exemplos:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-audit-logs`
 a| 
Necessário para nós com NODE_TYPE: VM_Admin_Node. Não o especifique para outros tipos de nó.

|===


==== BLOCK_DEVICE_RANGEDB_NNN

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Caminho e nome do arquivo especial do dispositivo de bloco que este nó usará para armazenamento de objetos persistente. Esta chave é necessária apenas para nós com NODE_TYPE: VM_Storage_Node; não a especifique para outros tipos de nó.

Somente block_DEVICE_RANGEDB_000 é necessário; o resto é opcional. O dispositivo de bloco especificado para block_DEVICE_RANGEDB_000 deve ter pelo menos 4 TB; os outros podem ser menores.

Não deixe lacunas. Se você especificar block_DEVICE_RANGEDB_005, você também deve especificar BLOCK_DEVICE_RANGEDB_004.

*Nota*: Para compatibilidade com implantações existentes, chaves de dois dígitos são suportadas para nós atualizados.

Exemplos:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-rangedb-000`
 a| 
Obrigatório:

BLOCK_DEVICE_RANGEDB_000

Opcional:

BLOCK_DEVICE_RANGEDB_001

BLOCK_DEVICE_RANGEDB_002

BLOCK_DEVICE_RANGEDB_003

BLOCK_DEVICE_RANGEDB_004

BLOCK_DEVICE_RANGEDB_005

BLOCK_DEVICE_RANGEDB_006

BLOCK_DEVICE_RANGEDB_007

BLOCK_DEVICE_RANGEDB_008

BLOCK_DEVICE_RANGEDB_009

BLOCK_DEVICE_RANGEDB_010

BLOCK_DEVICE_RANGEDB_011

BLOCK_DEVICE_RANGEDB_012

BLOCK_DEVICE_RANGEDB_013

BLOCK_DEVICE_RANGEDB_014

BLOCK_DEVICE_RANGEDB_015

|===


==== BLOCK_DEVICE_TABLES

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Caminho e nome do arquivo especial do dispositivo de bloco este nó usará para armazenamento persistente de tabelas de banco de dados. Esta chave é necessária apenas para nós com NODE_TYPE: VM_Admin_Node; não a especifique para outros tipos de nó.

Exemplos:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-tables`
 a| 
Obrigatório

|===


==== BLOCK_DEVICE_VAR_LOCAL

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Caminho e nome do arquivo especial do dispositivo de bloco que este nó usará para seu `/var/local` armazenamento persistente.

Exemplos:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-var-local`
 a| 
Obrigatório

|===


=== Chaves da rede do cliente



==== CLIENT_NETWORK_CONFIG

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
DHCP, ESTÁTICO OU DESATIVADO
 a| 
Opcional

|===


==== CLIENT_NETWORK_GATEWAY

[cols="4a,2a"]
|===


 a| 
Valor
 a| 
Designação



 a| 
Endereço IPv4 do gateway de rede de cliente local para este nó, que deve estar na sub-rede definida por CLIENT_network_IP e CLIENT_network_MASK. Este valor é ignorado para redes configuradas por DHCP.

Exemplos:

`1.1.1.1`

`10.224.4.81`
 a| 
Opcional

|===


==== CLIENT_NETWORK_IP

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Endereço IPv4 deste nó na rede do cliente.

Esta chave só é necessária quando CLIENT_NETWORK_CONFIG é ESTÁTICA; não a especifique para outros valores.

Exemplos:

`1.1.1.1`

`10.224.4.81`
 a| 
Necessário quando CLIENT_NETWORK_CONFIG é ESTÁTICO

Opcional caso contrário.

|===


==== CLIENT_NETWORK_MAC

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
O endereço MAC da interface de rede do cliente no contentor.

Este campo é opcional. Se omitido, um endereço MAC será gerado automaticamente.

Deve ser 6 pares de dígitos hexadecimais separados por dois pontos.

Exemplo: `b2:9c:02:c2:27:20`
 a| 
Opcional

|===


==== CLIENT_NETWORK_MASK

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
IPv4 máscara de rede para este nó na rede do cliente.

Especifique esta chave quando CLIENT_NETWORK_CONFIG for STATIC; não a especifique para outros valores.

Exemplos:

`255.255.255.0`

`255.255.248.0`
 a| 
Necessário se CLIENT_network_IP for especificado e CLIENT_network_CONFIG for ESTÁTICO

Opcional caso contrário.

|===


==== CLIENT_NETWORK_MTU

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
A unidade de transmissão máxima (MTU) para este nó na rede do cliente. Não especifique se CLIENT_NETWORK_CONFIG é DHCP. Se especificado, o valor deve estar entre 1280 e 9216. Se omitido, 1500 é usado.

Se você quiser usar quadros jumbo, defina o MTU para um valor adequado para quadros jumbo, como 9000. Caso contrário, mantenha o valor padrão.

*IMPORTANTE*: O valor MTU da rede deve corresponder ao valor configurado na porta do switch à qual o nó está conetado. Caso contrário, problemas de desempenho da rede ou perda de pacotes podem ocorrer.

Exemplos:

`1500`

`8192`
 a| 
Opcional

|===


==== CLIENT_NETWORK_TARGET

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Nome do dispositivo host que você usará para acesso à rede do cliente pelo nó StorageGRID. Apenas são suportados nomes de interface de rede. Normalmente, você usa um nome de interface diferente do que foi especificado para GRID_Network_TARGET ou ADMIN_network_TARGET.

*Nota*: Não use dispositivos bond ou bridge como destino de rede. Configure uma VLAN (ou outra interface virtual) em cima do dispositivo de ligação ou use um par bridge e Ethernet virtual (vete).

*Prática recomendada:* Especifique um valor mesmo que este nó não tenha inicialmente um endereço IP de rede do cliente. Em seguida, você pode adicionar um endereço IP da rede do cliente mais tarde, sem ter que reconfigurar o nó no host.

Exemplos:

`bond0.1003`

`ens423`
 a| 
Prática recomendada

|===


==== CLIENT_NETWORK_TARGET_TYPE

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Interface (este é apenas o valor suportado.)
 a| 
Opcional

|===


==== CLIENT_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Verdadeiro ou Falso

Defina a chave como "true" para fazer com que o contentor StorageGRID use o endereço MAC da interface de destino do host na rede do cliente.

*Melhor prática:* em redes onde o modo promíscuo seria necessário, use a chave CLIENT_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC em vez disso.

Para mais detalhes sobre clonagem de MAC para Linux, consultelink:../swnodes/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Considerações e recomendações para clonagem de endereços MAC"]
 a| 
Prática recomendada

|===


=== Chaves de rede de grade



==== GRID_NETWORK_CONFIG

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
ESTÁTICO ou DHCP

O padrão é ESTÁTICO se não for especificado.
 a| 
Prática recomendada

|===


==== GRID_NETWORK_GATEWAY

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Endereço IPv4 do gateway de rede local para este nó, que deve estar na sub-rede definida por GRID_Network_IP e GRID_NETWORK_MASK. Este valor é ignorado para redes configuradas por DHCP.

Se a rede de Grade for uma única sub-rede sem gateway, use o endereço de gateway padrão para a sub-rede (X.Y.z.1) ou o valor GRID_Network_IP deste nó; qualquer valor simplificará expansões futuras de rede de Grade.
 a| 
Obrigatório

|===


==== GRID_NETWORK_IP

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Endereço IPv4 deste nó na rede de Grade. Esta chave só é necessária quando GRID_NETWORK_CONFIG é ESTÁTICA; não a especifique para outros valores.

Exemplos:

`1.1.1.1`

`10.224.4.81`
 a| 
Necessário quando GRID_NETWORK_CONFIG é ESTÁTICO

Opcional caso contrário.

|===


==== GRID_NETWORK_MAC

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
O endereço MAC da interface Grid Network no contentor.

Deve ser 6 pares de dígitos hexadecimais separados por dois pontos.

Exemplo: `b2:9c:02:c2:27:30`
 a| 
Opcional

Se omitido, um endereço MAC será gerado automaticamente.

|===


==== GRID_NETWORK_MASK

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
IPv4 máscara de rede para este nó na rede de Grade. Especifique esta chave quando GRID_NETWORK_CONFIG estiver ESTÁTICA; não a especifique para outros valores.

Exemplos:

`255.255.255.0`

`255.255.248.0`
 a| 
Necessário quando GRID_Network_IP é especificado e GRID_NETWORK_CONFIG é ESTÁTICO.

Opcional caso contrário.

|===


==== GRID_NETWORK_MTU

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
A unidade de transmissão máxima (MTU) para este nó na rede de Grade. Não especifique se GRID_NETWORK_CONFIG é DHCP. Se especificado, o valor deve estar entre 1280 e 9216. Se omitido, 1500 é usado.

Se você quiser usar quadros jumbo, defina o MTU para um valor adequado para quadros jumbo, como 9000. Caso contrário, mantenha o valor padrão.

*IMPORTANTE*: O valor MTU da rede deve corresponder ao valor configurado na porta do switch à qual o nó está conetado. Caso contrário, problemas de desempenho da rede ou perda de pacotes podem ocorrer.

*IMPORTANTE*: Para obter o melhor desempenho da rede, todos os nós devem ser configurados com valores MTU semelhantes em suas interfaces Grid Network. O alerta *incompatibilidade de MTU da rede de Grade* é acionado se houver uma diferença significativa nas configurações de MTU para a rede de Grade em nós individuais. Os valores de MTU não precisam ser os mesmos para todos os tipos de rede.

Exemplos:

`1500`

`8192`
 a| 
Opcional

|===


==== GRID_NETWORK_TARGET

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Nome do dispositivo host que você usará para acesso à rede de Grade pelo nó StorageGRID. Apenas são suportados nomes de interface de rede. Normalmente, você usa um nome de interface diferente do que foi especificado para ADMIN_NETWORK_TARGET ou CLIENT_network_TARGET.

*Nota*: Não use dispositivos bond ou bridge como destino de rede. Configure uma VLAN (ou outra interface virtual) em cima do dispositivo de ligação ou use um par bridge e Ethernet virtual (vete).

Exemplos:

`bond0.1001`

`ens192`
 a| 
Obrigatório

|===


==== GRID_NETWORK_TARGET_TYPE

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Interface (este é o único valor suportado.)
 a| 
Opcional

|===


==== GRID_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Verdadeiro ou Falso

Defina o valor da chave como "true" para fazer com que o contentor StorageGRID use o endereço MAC da interface de destino do host na rede de Grade.

*Melhor prática:* em redes onde o modo promíscuo seria necessário, use a chave GRID_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC em vez disso.

Para mais detalhes sobre clonagem de MAC para Linux, consultelink:../swnodes/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Considerações e recomendações para clonagem de endereços MAC"]
 a| 
Prática recomendada

|===


=== Chave de senha de instalação (temporária)



==== CUSTOM_TEMPORARY_PASSWORD_HASH

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Para o nó de administração principal, defina uma senha temporária padrão para a API de instalação do StorageGRID durante a instalação.

*Nota*: Defina uma senha de instalação somente no nó Admin principal. Se você tentar definir uma senha em outro tipo de nó, a validação do arquivo de configuração do nó falhará.

Definir este valor não tem efeito quando a instalação estiver concluída.

Se esta chave for omitida, por padrão nenhuma senha temporária será definida. Como alternativa, você pode definir uma senha temporária usando a API de instalação do StorageGRID.

Deve ser um `crypt()` hash de senha SHA-512 com formato `$6$<salt>$<password hash>` para uma senha de pelo menos 8 e não mais de 32 carateres.

Esse hash pode ser gerado usando ferramentas CLI, como o `openssl passwd` comando no modo SHA-512.
 a| 
Prática recomendada

|===


=== Chave de interfaces



==== Interface_TARGET_nnnn

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Nome e descrição opcional para uma interface extra que você deseja adicionar a este nó. Você pode adicionar várias interfaces extras a cada nó.

Para _nnnnn_, especifique um número exclusivo para cada entrada INTERFACE_TARGET que você está adicionando.

Para o valor, especifique o nome da interface física no host bare-metal. Em seguida, opcionalmente, adicione uma vírgula e forneça uma descrição da interface, que é exibida na página interfaces VLAN e na página grupos HA.

Exemplo: `INTERFACE_TARGET_0001=ens256, Trunk`

Se você adicionar uma interface de tronco, deverá configurar uma interface de VLAN no StorageGRID. Se você adicionar uma interface de acesso, poderá adicionar a interface diretamente a um grupo HA; não será necessário configurar uma interface VLAN.
 a| 
Opcional

|===


=== Tecla RAM máxima



==== MÁXIMO_RAM

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
A quantidade máxima de RAM que este nó pode consumir. Se esta chave for omitida, o nó não tem restrições de memória. Ao definir este campo para um nó de nível de produção, especifique um valor que seja pelo menos 24 GB e 16 a 32 GB menor que a RAM total do sistema.

*Nota*: O valor da RAM afeta o espaço reservado de metadados real de um nó. Consulte link:../admin/managing-object-metadata-storage.html["Descrição do que é Metadata Reserved Space"].

O formato deste campo é `_numberunit_`, onde `_unit_` pode ser `b`, `k`, , `m` `g` ou .

Exemplos:

`24g`

`38654705664b`

*Nota*: Se você quiser usar essa opção, você deve habilitar o suporte do kernel para cgroups de memória.
 a| 
Opcional

|===


=== Chaves de tipo de nó



==== NODE_TYPE (TIPO DE NÓ)

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Tipo de nó:

* VM_Admin_Node
* VM_Storage_Node
* VM_Archive_Node
* VM_API_Gateway

 a| 
Obrigatório

|===


==== TIPO_ARMAZENAMENTO

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Define o tipo de objetos que um nó de storage contém. Para obter mais informações, link:../primer/what-storage-node-is.html#types-of-storage-nodes["Tipos de nós de storage"]consulte . Esta chave é necessária apenas para nós com NODE_TYPE: VM_Storage_Node; não a especifique para outros tipos de nó. Tipos de armazenamento:

* combinado
* dados
* metadados


*Nota*: Se o STORAGE_TYPE não for especificado, o tipo Storage Node é definido como combinado (dados e metadados) por padrão.
 a| 
Opcional

|===


=== Teclas de remapeamento de portas


NOTE: O suporte para remapeamento de portas está obsoleto e será removido em uma versão futura. Para remover portas remapeadas, consultelink:../maintain/removing-port-remaps-on-bare-metal-hosts.html["Remova os remapas de portas em hosts bare metal"] .



==== PORT_REMAP

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Remapeia qualquer porta usada por um nó para comunicações internas de nó de grade ou comunicações externas. O remapeamento de portas é necessário se as políticas de rede empresarial restringirem uma ou mais portas usadas pelo StorageGRID, conforme descrito em link:../network/internal-grid-node-communications.html["Comunicações internas do nó da grade"] ou link:../network/external-communications.html["Comunicações externas"].

*IMPORTANTE*: Não remapegue as portas que você está planejando usar para configurar pontos de extremidade do balanceador de carga.

*Nota*: Se apenas PORT_REMAP estiver definido, o mapeamento especificado será usado para comunicações de entrada e saída. Se Port_REMAP_INBOUND também for especificado, PORT_REMAP se aplica apenas às comunicações de saída.

O formato usado é: `_network type_/_protocol_/_default port used by grid node_/_new port_`, Onde `_network type_` está grade, admin ou cliente e `_protocol_` é tcp ou udp.

Exemplo: `PORT_REMAP = client/tcp/18082/443`

Você também pode remapear várias portas usando uma lista separada por vírgulas.

Exemplo: `PORT_REMAP = client/tcp/18082/443, client/tcp/18083/80`
 a| 
Opcional

|===


==== PORT_REMAP_INBOUND

[cols="4a,2a"]
|===
| Valor | Designação 


 a| 
Remapeia as comunicações de entrada para a porta especificada. Se você especificar PORT_REMAP_INBOUND, mas não especificar um valor para PORT_REMAP, as comunicações de saída para a porta não serão alteradas.

*IMPORTANTE*: Não remapegue as portas que você está planejando usar para configurar pontos de extremidade do balanceador de carga.

O formato usado é: `_network type_/_protocol_/_remapped port_/_default port used by grid node_`, Onde `_network type_` está grade, admin ou cliente e `_protocol_` é tcp ou udp.

Exemplo: `PORT_REMAP_INBOUND = grid/tcp/3022/22`

Você também pode remapear várias portas de entrada usando uma lista separada por vírgulas.

Exemplo: `PORT_REMAP_INBOUND = grid/tcp/3022/22, admin/tcp/3022/22`
 a| 
Opcional

|===