---
permalink: swnodes/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: how to download installation files 
summary: Você deve baixar os arquivos de instalação do StorageGRID e extrair os arquivos necessários.  Opcionalmente, você pode verificar manualmente os arquivos no pacote de instalação. 
---
= Baixe e extraia os arquivos de instalação do StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve baixar o arquivo de instalação do StorageGRID e extrair os arquivos necessários. Opcionalmente, você pode verificar manualmente os arquivos no pacote de instalação.

.Passos
. Vá para https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Página de downloads do NetApp para StorageGRID"^] .
. Selecione o botão para baixar a versão mais recente ou selecione outra versão no menu suspenso e selecione *Go*.
. Inicie sessão com o nome de utilizador e a palavra-passe da sua conta NetApp.
. Se for apresentada uma instrução Caution/MustRead, leia-a e selecione a caixa de verificação.
+

CAUTION: Você deve aplicar os hotfixes necessários depois de instalar a versão do StorageGRID. Para obter mais informações, consulte a. link:../maintain/storagegrid-hotfix-procedure.html["procedimento de hotfix nas instruções de recuperação e manutenção"]

. Leia o Contrato de Licença de Utilizador final, selecione a caixa de verificação e, em seguida, selecione *Accept & continue*.
. Na coluna *Instalar StorageGRID*, selecione o arquivo de instalação .tgz ou .zip para o seu tipo de nó baseado em software: RHEL, Ubuntu ou Debian, ou VMware.
+

NOTE: Use o `.zip` arquivo se você estiver executando o Windows no laptop de serviço.

. Salve o arquivo de instalação.
. [[download-verification-package]]A verificação da assinatura do código é manual em um nó Linux.  Opcionalmente, se você precisar verificar o arquivo de instalação:
+
.. Baixe o pacote de verificação de assinatura de código StorageGRID. O nome do arquivo deste pacote usa o formato `StorageGRID_<version-number>_Code_Signature_Verification_Package.tar.gz`, onde `<version-number>` está a versão do software StorageGRID.
.. Siga os passos paralink:download-files-verify.html["verifique manualmente os arquivos de instalação"] .


. Extraia os arquivos do arquivo de instalação.
. Escolha os arquivos que você precisa.
+
Os arquivos de que você precisa dependem da topologia de grade planejada e de como você implantará seu sistema StorageGRID.

+

NOTE: Os caminhos listados na tabela são relativos ao diretório de nível superior instalado pelo arquivo de instalação extraído.



[role="tabbed-block"]
====
.RHEL
--
[cols="1a,1a"]
|===
| Caminho e nome do arquivo | Descrição 


| ./rpms/README  a| 
Um arquivo de texto que descreve todos os arquivos contidos no arquivo de download do StorageGRID.



| ./rpms/NLF000000.txt  a| 
Uma licença gratuita que não fornece qualquer direito de suporte para o produto.



| ./rpms/StorageGRID-Webscale-Images-_version_-SHA.rpm  a| 
Pacote RPM para instalar as imagens do nó StorageGRID em seus hosts RHEL.



| ./rpms/StorageGRID-Webscale-Service-_version_-SHA.rpm  a| 
Pacote RPM para instalar o serviço de host StorageGRID em seus hosts RHEL.



| Ferramenta de script de implantação | Descrição 


| ./rpms/configure-StorageGRID.py  a| 
Um script Python usado para automatizar a configuração de um sistema StorageGRID.



| ./rpms/configure-sga.py  a| 
Um script Python usado para automatizar a configuração de dispositivos StorageGRID.



| ./rpms/configure-StorageGRID.sample.json  a| 
Um exemplo de arquivo de configuração para uso com o `configure-storagegrid.py` script.



| ./rpms/StorageGRID-ssoauth.py  a| 
Um exemplo de script Python que você pode usar para fazer login na API de Gerenciamento de Grade quando o logon único estiver ativado. Você também pode usar este script para integração Ping federate.



| ./rpms/configure-StorageGRID.blank.json  a| 
Um arquivo de configuração em branco para uso com o `configure-storagegrid.py` script.



| ./rpms/extras/ansible  a| 
Exemplo de função do Ansible e manual de estratégia para configurar hosts do RHEL para implantação de contêineres do StorageGRID. Você pode personalizar a função ou o manual de estratégia conforme necessário.



| ./rpms/StorageGRID-ssoauth-azure.py  a| 
Um exemplo de script Python que você pode usar para fazer login na API de Gerenciamento de Grade quando o logon único (SSO) está habilitado usando o ative Directory ou Ping federate.



| ./rpms/StorageGRID-ssoauth-azure.js  a| 
Um script auxiliar chamado pelo script Python complementar `storagegrid-ssoauth-azure.py` para executar interações SSO com o Azure.



| ./rpms/extras/api-schemas  a| 
Esquemas de API para StorageGRID.

*Nota*: Antes de executar uma atualização, você pode usar esses esquemas para confirmar que qualquer código que você tenha escrito para usar APIs de gerenciamento do StorageGRID será compatível com a nova versão do StorageGRID se você não tiver um ambiente StorageGRID que não seja de produção para teste de compatibilidade de atualização.

|===
--
.Ubuntu ou Debian
--
[cols="1a,1a"]
|===
| Caminho e nome do arquivo | Descrição 


| ./debs/README  a| 
Um arquivo de texto que descreve todos os arquivos contidos no arquivo de download do StorageGRID.



| ./debs/NLF000000.txt  a| 
Um arquivo de licença do NetApp que não é de produção que pode ser usado para testes e implantações de prova de conceito.



| ./debs/StorageGRID-webscale-images-version-SHA.deb  a| 
Pacote DEB para instalar as imagens do nó StorageGRID em hosts Ubuntu ou Debian.



| ./debs/StorageGRID-webscale-images-version-SHA.deb.md5  a| 
MD5 checksum para o arquivo `/debs/storagegrid-webscale-images-version-SHA.deb`.



| ./debs/StorageGRID-webscale-service-version-SHA.deb  a| 
Pacote DEB para instalar o serviço host StorageGRID em hosts Ubuntu ou Debian.



| Ferramenta de script de implantação | Descrição 


| ./debs/configure-StorageGRID.py  a| 
Um script Python usado para automatizar a configuração de um sistema StorageGRID.



| ./debs/configure-sga.py  a| 
Um script Python usado para automatizar a configuração de dispositivos StorageGRID.



| ./debs/StorageGRID-ssoauth.py  a| 
Um exemplo de script Python que você pode usar para fazer login na API de Gerenciamento de Grade quando o logon único estiver ativado. Você também pode usar este script para integração Ping federate.



| ./debs/configure-StorageGRID.sample.json  a| 
Um exemplo de arquivo de configuração para uso com o `configure-storagegrid.py` script.



| ./debs/configure-StorageGRID.blank.json  a| 
Um arquivo de configuração em branco para uso com o `configure-storagegrid.py` script.



| ./debs/extras/ansible  a| 
Exemplo Ansible role e playbook para configurar hosts Ubuntu ou Debian para a implantação de contentores StorageGRID. Você pode personalizar a função ou o manual de estratégia conforme necessário.



| ./debs/StorageGRID-ssoauth-azure.py  a| 
Um exemplo de script Python que você pode usar para fazer login na API de Gerenciamento de Grade quando o logon único (SSO) está habilitado usando o ative Directory ou Ping federate.



| ./debs/StorageGRID-ssoauth-azure.js  a| 
Um script auxiliar chamado pelo script Python complementar `storagegrid-ssoauth-azure.py` para executar interações SSO com o Azure.



| ./debs/extras/api-schemas  a| 
Esquemas de API para StorageGRID.

*Nota*: Antes de executar uma atualização, você pode usar esses esquemas para confirmar que qualquer código que você tenha escrito para usar APIs de gerenciamento do StorageGRID será compatível com a nova versão do StorageGRID se você não tiver um ambiente StorageGRID que não seja de produção para teste de compatibilidade de atualização.

|===
--
.VMware
--
[cols="1a,1a"]
|===
| Caminho e nome do arquivo | Descrição 


| ./vSphere/README  a| 
Um arquivo de texto que descreve todos os arquivos contidos no arquivo de download do StorageGRID.



| ./vSphere/NLF000000.txt  a| 
Uma licença gratuita que não fornece qualquer direito de suporte para o produto.



| ./vsphere/NetApp-SG-version-SHA.vmdk  a| 
O arquivo de disco da máquina virtual que é usado como um modelo para criar máquinas virtuais de nó de grade.



| ./vsphere/vsphere-primary-admin.ovf ./vsphere/vsphere-primary-admin.mf  a| 
O arquivo de modelo Open Virtualization Format (`.ovf`) e o arquivo de manifesto (`.mf`) para implantar o nó de administração principal.



| ./vsphere/vsphere-non-primary-admin.ovf ./vsphere/vsphere-non-primary-admin.mf  a| 
O arquivo de (`.ovf`modelo ) e o arquivo de manifesto (`.mf`) para implantar nós de administração não primários.



| ./vsphere/vsphere-gateway.ovf ./vsphere/vsphere-gateway.mf  a| 
O arquivo de (`.ovf`modelo ) e o arquivo de manifesto (`.mf`) para implantar nós do Gateway.



| ./vsphere/vsphere-storage.ovf ./vsphere/vsphere-storage.mf  a| 
O arquivo de (`.ovf`modelo ) e o arquivo de manifesto (`.mf`) para implantar nós de storage baseados em máquina virtual.



| Ferramenta de script de implantação | Descrição 


| ./vsphere/deploy-vsphere-ovftool.sh  a| 
Um script de shell Bash usado para automatizar a implantação de nós de grade virtual.



| ./vsphere/deploy-vsphere-ovftool-sample.ini  a| 
Um exemplo de arquivo de configuração para uso com o `deploy-vsphere-ovftool.sh` script.



| ./vsphere/configure-StorageGRID.py  a| 
Um script Python usado para automatizar a configuração de um sistema StorageGRID.



| ./vsphere/configure-sga.py  a| 
Um script Python usado para automatizar a configuração de dispositivos StorageGRID.



| ./vsphere/StorageGRID-ssoauth.py  a| 
Um exemplo de script Python que você pode usar para entrar na API de Gerenciamento de Grade quando o logon único (SSO) está ativado. Você também pode usar este script para integração Ping federate.



| ./vsphere/configure-StorageGRID.sample.json  a| 
Um exemplo de arquivo de configuração para uso com o `configure-storagegrid.py` script.



| ./vsphere/configure-StorageGRID.blank.json  a| 
Um arquivo de configuração em branco para uso com o `configure-storagegrid.py` script.



| ./vsphere/StorageGRID-ssoauth-azure.py  a| 
Um exemplo de script Python que você pode usar para fazer login na API de Gerenciamento de Grade quando o logon único (SSO) está habilitado usando o ative Directory ou Ping federate.



| ./vsphere/StorageGRID-ssoauth-azure.js  a| 
Um script auxiliar chamado pelo script Python complementar `storagegrid-ssoauth-azure.py` para executar interações SSO com o Azure.



| ./vsphere/extras/api-schemas  a| 
Esquemas de API para StorageGRID.

*Nota*: Antes de executar uma atualização, você pode usar esses esquemas para confirmar que qualquer código que você tenha escrito para usar APIs de gerenciamento do StorageGRID será compatível com a nova versão do StorageGRID se você não tiver um ambiente StorageGRID que não seja de produção para teste de compatibilidade de atualização.

|===
--
====