---
permalink: swnodes/overview-of-installation-rest-api.html 
sidebar: sidebar 
keywords: installation REST API 
summary: O StorageGRID fornece a API de instalação do StorageGRID para executar tarefas de instalação. 
---
= Saiba mais sobre a instalação da StorageGRID API REST
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O StorageGRID fornece a API de instalação do StorageGRID para executar tarefas de instalação.

A API usa a plataforma de API de código aberto Swagger para fornecer a documentação da API. O Swagger permite que desenvolvedores e não desenvolvedores interajam com a API em uma interface de usuário que ilustra como a API responde a parâmetros e opções. Esta documentação pressupõe que você esteja familiarizado com as tecnologias da Web padrão e o formato de dados JSON.


CAUTION: Todas as operações de API executadas usando a página da Documentação da API são operações ativas. Tenha cuidado para não criar, atualizar ou excluir dados de configuração ou outros dados por engano.

Cada comando REST API inclui o URL da API, uma ação HTTP, quaisquer parâmetros de URL necessários ou opcionais e uma resposta de API esperada.



[[storagegrid-installation-api]]
== API de instalação do StorageGRID

A API de instalação do StorageGRID só está disponível quando você estiver configurando inicialmente o sistema StorageGRID e se precisar executar uma recuperação do nó de administração principal. A API de instalação pode ser acessada por HTTPS a partir do Gerenciador de Grade.

Para acessar a documentação da API, vá para a página da Web de instalação no nó de administração principal e selecione *Ajuda* > *Documentação da API* na barra de menus.

A API de instalação do StorageGRID inclui as seguintes seções:

* *config*: Operações relacionadas à versão do produto e às versões da API. Você pode listar a versão de lançamento do produto e as principais versões da API suportadas por esse lançamento.
* *grid*: Operações de configuração em nível de grid. Você pode obter e atualizar as configurações do grid, incluindo detalhes do grid, sub-redes da Grid Network, senhas do grid e endereços IP dos servidores NTP e do servidor DNS.
* *nós*: Operações de configuração em nível de nó. Você pode recuperar uma lista de nós da grade, excluir um nó da grade, configurar um nó da grade, visualizar um nó da grade e redefinir a configuração de um nó da grade.
* *Provisionamento*: Operações de provisionamento. Você pode iniciar a operação de provisionamento e visualizar o status da operação de provisionamento.
* *Recuperação*: Operações de recuperação do nó de administração principal. Você pode redefinir informações, carregar o pacote de recuperação, iniciar a recuperação e visualizar o status da operação de recuperação.
* *pacote de recuperação*: Operações para baixar o pacote de recuperação.
* *sites*: Operações de configuração em nível de site. Você pode criar, visualizar, excluir e modificar um site.
* *senha-temporária*: Operações na senha temporária para proteger a mgmt-api durante a instalação.

