---
permalink: swnodes/post-installation-guidelines.html 
sidebar: sidebar 
keywords: after installation guidelines 
summary: Depois de concluir a implantação e a configuração do nó de grade, siga estas diretrizes para endereçamento DHCP e alterações na configuração da rede. 
---
= Diretrizes de pós-instalação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de concluir a implantação e a configuração do nó de grade, siga estas diretrizes para endereçamento DHCP e alterações na configuração da rede.

* Se o DHCP foi usado para atribuir endereços IP, configure uma reserva DHCP para cada endereço IP nas redes que estão sendo usadas.
+
Só pode configurar o DHCP durante a fase de implementação. Não é possível configurar o DHCP durante a configuração.

+

NOTE: Os nós reiniciam quando a configuração da rede de Grade é alterada pelo DHCP, o que pode causar interrupções se uma alteração de DHCP afetar vários nós ao mesmo tempo.

* Você deve usar os procedimentos alterar IP se quiser alterar endereços IP, máscaras de sub-rede e gateways padrão para um nó de grade. link:../maintain/configuring-ip-addresses.html["Configurar endereços IP"]Consulte .
* Se você fizer alterações na configuração de rede, incluindo alterações de roteamento e gateway, a conetividade do cliente para o nó de administração principal e outros nós de grade pode ser perdida. Dependendo das alterações de rede aplicadas, talvez seja necessário restabelecer essas conexões.

