---
permalink: swnodes/starting-storagegrid-host-service.html 
sidebar: sidebar 
keywords: how to start host service 
summary: Para iniciar seus nós do StorageGRID e garantir que eles sejam reiniciados após uma reinicialização do host, você deve habilitar e iniciar o serviço de host do StorageGRID. 
---
= Inicie o serviço do host StorageGRID (Linux)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para iniciar seus nós do StorageGRID e garantir que eles sejam reiniciados após uma reinicialização do host, você deve habilitar e iniciar o serviço de host do StorageGRID.


NOTE: "Linux" refere-se a uma implantação RHEL, Ubuntu ou Debian.  Para obter uma lista de versões suportadas, consulte o https://imt.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade NetApp (IMT)"^] .

.Passos
. Execute os seguintes comandos em cada host:
+
[listing]
----
sudo systemctl enable storagegrid
sudo systemctl start storagegrid
----
. Execute o seguinte comando para garantir que a implantação está em andamento:
+
[listing]
----
sudo storagegrid node status node-name
----
. Se qualquer nó retornar um status de "não está em execução" ou "parado", execute o seguinte comando:
+
[listing]
----
sudo storagegrid node start node-name
----
. Se você já ativou e iniciou o serviço de host StorageGRID (ou se não tiver certeza se o serviço foi ativado e iniciado), execute também o seguinte comando:
+
[listing]
----
sudo systemctl reload-or-restart storagegrid
----

