---
permalink: swnodes/troubleshooting-installation-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot ubuntu or debian installation 
summary: Se ocorrerem problemas durante a instalação do sistema StorageGRID, pode aceder aos ficheiros de registo de instalação. O suporte técnico também pode precisar usar os arquivos de log de instalação para resolver problemas. 
---
= Solucionar problemas de instalação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se ocorrerem problemas durante a instalação do sistema StorageGRID, pode aceder aos ficheiros de registo de instalação. O suporte técnico também pode precisar usar os arquivos de log de instalação para resolver problemas.


NOTE: "Linux" refere-se a uma implantação RHEL, Ubuntu ou Debian.  Para obter uma lista de versões suportadas, consulte o https://imt.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade NetApp (IMT)"^] .

[role="tabbed-block"]
====
.Linux
--
Os seguintes arquivos de log de instalação estão disponíveis no contentor que está executando cada nó:

* `/var/local/log/install.log` (encontrado em todos os nós da grade)
* `/var/local/log/gdu-server.log` (Encontrado no nó de administração principal)


Os seguintes arquivos de log de instalação estão disponíveis no host:

* `/var/log/storagegrid/daemon.log`
* `/var/log/storagegrid/nodes/node-name.log`


Para saber como acessar os arquivos de log, link:../monitor/collecting-log-files-and-system-data.html["Colete arquivos de log e dados do sistema"]consulte .

--
.VMware
--
A seguir estão os principais arquivos de log de instalação, que suporte técnico pode precisar para resolver problemas.

* `/var/local/log/install.log` (encontrado em todos os nós da grade)
* `/var/local/log/gdu-server.log` (Encontrado no nó de administração principal)


*A reserva de recursos da máquina virtual requer ajuste*

Os arquivos OVF incluem uma reserva de recursos projetada para garantir que cada nó de grade tenha RAM e CPU suficientes para operar com eficiência. Se você criar máquinas virtuais implantando esses arquivos OVF no VMware e o número predefinido de recursos não estiver disponível, as máquinas virtuais não serão iniciadas.

.Sobre esta tarefa
Se você tiver certeza de que o host da VM tem recursos suficientes para cada nó de grade, ajuste manualmente os recursos alocados para cada máquina virtual e tente iniciar as máquinas virtuais.

.Passos
. Na árvore cliente do VMware vSphere Hypervisor, selecione a máquina virtual que não foi iniciada.
. Clique com o botão direito do rato na máquina virtual e selecione *Edit Settings* (Editar definições).
. Na janela Propriedades de máquinas virtuais, selecione a guia *recursos*.
. Ajuste os recursos alocados à máquina virtual:
+
.. Selecione *CPU* e, em seguida, use o controle deslizante de reserva para ajustar o MHz reservado para esta máquina virtual.
.. Selecione *memória* e, em seguida, use o controle deslizante reserva para ajustar o MB reservado para esta máquina virtual.


. Clique em *OK*.
. Repita conforme necessário para outras máquinas virtuais hospedadas no mesmo host da VM.


*A senha de instalação temporária foi desabilitada*

Ao implantar um nó VMware, você pode especificar opcionalmente uma senha de instalação temporária. Você deve ter essa senha para acessar o console da VM ou usar SSH antes que o novo nó se una à grade.

Se você optou por desativar a senha de instalação temporária, você deve executar etapas adicionais para depurar problemas de instalação.

Você pode fazer um dos seguintes procedimentos:

* Reimplante a VM, mas especifique uma senha de instalação temporária para que você possa acessar o console ou usar SSH para depurar problemas de instalação.
* Use o vCenter para definir a senha:
+
.. Desligue a VM.
.. Vá para *VM*, selecione a guia *Configure* e selecione *vApp Options*.
.. Especifique o tipo de senha de instalação temporária a definir:
+
*** Selecione *CUSTOM_TEMPORARY_password* para definir uma senha temporária personalizada.
*** Selecione *TEMPORARY_PASSWORD_TYPE* para usar o nome do nó como senha temporária.


.. Selecione *Definir valor*.
.. Defina a senha temporária:
+
*** Altere *CUSTOM_TEMPORARY_PASSWORD* para um valor de senha personalizado.
*** Atualize o *TEMPORARY_PASSWORD_TYPE* com o valor *Use node name*.


.. Reinicie a VM para aplicar a nova senha.




--
====
.Informações relacionadas
* Para saber como acessar os arquivos de log, link:../monitor/logs-files-reference.html["Referência de ficheiros de registo"]consulte .
* link:../troubleshoot/index.html["Solucionar problemas de um sistema StorageGRID"]
* Se precisar de ajuda adicional, entre em Contato https://mysupport.netapp.com/site/global/dashboard["Suporte à NetApp"^]com .

