---
permalink: upgrade/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: O StorageGRID 12,0 usa a versão 4 da API de gerenciamento de grade. A versão 4 desconsidera a versão 3; no entanto, as versões 1, 2 e 3 ainda são suportadas. 
---
= Alterações na API Grid Management
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O StorageGRID 12,0 usa a versão 4 da API de gerenciamento de grade. A versão 4 desconsidera a versão 3; no entanto, as versões 1, 2 e 3 ainda são suportadas.


NOTE: Você pode continuar usando versões obsoletas da API de gerenciamento com o StorageGRID 12,0; no entanto, o suporte para essas versões da API será removido em uma versão futura do StorageGRID. Depois de atualizar para o StorageGRID 12,0, você pode desativar as APIs obsoletas usando a `PUT /grid/config/management` API.

Para saber mais, link:../admin/using-grid-management-api.html["Use a API de gerenciamento de grade"]acesse .



== Novos endpoints privados para mover ADC

Os seguintes endpoints privados foram adicionados para permitir que você link:../maintain/move-adc-service.html["Mova o serviço ADC"]entre um nó de armazenamento para outro no mesmo site:

`/private/move-adc`

`/private/move-adc/start`

`/private/move-adc/retry`
