---
permalink: upgrade/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: O StorageGRID 12.0 usa a versão 4 da API de gerenciamento de grade.  A versão 4 substitui a versão 3; no entanto, as versões 1, 2 e 3 ainda são suportadas. 
---
= Alterações na API Grid Management
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O StorageGRID 12.0 usa a versão 4 da API de gerenciamento de grade.  A versão 4 substitui a versão 3; no entanto, as versões 1, 2 e 3 ainda são suportadas.


NOTE: Você pode continuar a usar versões obsoletas da API de gerenciamento com o StorageGRID 12.0; no entanto, o suporte para essas versões da API será removido em uma versão futura do StorageGRID.  Após a atualização para o StorageGRID 12.0, você pode desativar as APIs obsoletas usando o `PUT /grid/config/management` API.

Para saber mais, link:../admin/using-grid-management-api.html["Use a API de gerenciamento de grade"]acesse .



== Novos pontos de extremidade para buckets de ramificação

Os seguintes pontos de extremidade foram adicionados para permitir que vocêlink:../tenant/what-is-branch-bucket.html["gerenciar buckets de ramificação"] :

`GET /org/containers/{branchBucketName}/branch`

`PUT /org/containers/{branchBucketName}/branch`



== Novos endpoints privados para Move ADC

Os seguintes pontos de extremidade privados foram adicionados para permitir que vocêlink:../maintain/move-adc-service.html["mover o serviço ADC"] de um nó de armazenamento para outro no mesmo site:

`/private/move-adc`

`/private/move-adc/start`

`/private/move-adc/retry`



== Novos endpoints privados para converter para nó somente de dados

Os seguintes pontos de extremidade privados foram adicionados para permitir que vocêlink:../maintain/convert-to-data-only-node.html["converter um ou mais nós de armazenamento combinados"] que não contêm o serviço ADC em nós somente de dados.

`/private/convert-to-data-only-node`

`/private/convert-to-data-only-node/start`

`/private/convert-to-data-only-node/retry`
