---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html 
sidebar: sidebar 
keywords: upgrade, grid tasks, firewall, ports 
summary: Antes de atualizar um sistema StorageGRID, verifique se o sistema está pronto para acomodar a atualização. Certifique-se de que o sistema está funcionando normalmente e que todos os nós de grade estejam operacionais. 
---
= Verifique o estado do sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de atualizar um sistema StorageGRID, verifique se o sistema está pronto para acomodar a atualização. Certifique-se de que o sistema está funcionando normalmente e que todos os nós de grade estejam operacionais.

.Passos
. Faça login no Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
. Verifique e resolva quaisquer alertas ativos.
. Consultelink:../network/internal-grid-node-communications.html["Comunicações internas do nó da grade"] elink:../network/external-communications.html["Comunicações externas"] para garantir que todas as portas necessárias para o StorageGRID 12.0 sejam abertas antes da atualização.
+

NOTE: Nenhuma porta adicional é necessária ao atualizar para o StorageGRID 12.0.


