---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html 
sidebar: sidebar 
keywords: upgrade, grid tasks, firewall, ports 
summary: Antes de atualizar um sistema StorageGRID, verifique se o sistema está pronto para acomodar a atualização. Certifique-se de que o sistema está funcionando normalmente e que todos os nós de grade estejam operacionais. 
---
= Verifique o estado do sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de atualizar um sistema StorageGRID, verifique se o sistema está pronto para acomodar a atualização. Certifique-se de que o sistema está funcionando normalmente e que todos os nós de grade estejam operacionais.

.Passos
. Faça login no Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
. Verifique e resolva quaisquer alertas ativos.
. Confirme se não há tarefas de grade conflitantes ativas ou pendentes.
+
.. Selecione *SUPPORT* > *Tools* > *Grid topology*.
.. Selecione *_site_* > *_Main Admin Node_* > *CMN* > *Grid Tasks* > *Configuration*.
+
As tarefas de avaliação de gerenciamento do ciclo de vida das informações (ILME) são as únicas tarefas de grade que podem ser executadas simultaneamente com a atualização do software.

.. Se quaisquer outras tarefas de grade estiverem ativas ou pendentes, aguarde até que elas terminem ou liberem seu bloqueio.
+

NOTE: Contacte o suporte técnico se uma tarefa não terminar ou libertar o respetivo bloqueio.



. link:../network/internal-grid-node-communications.html["Comunicações internas do nó da grade"]Consulte e link:../network/external-communications.html["Comunicações externas"] para garantir que todas as portas necessárias para o StorageGRID 11,9 estejam abertas antes de atualizar.
+

NOTE: Não são necessárias portas adicionais ao atualizar para o StorageGRID 12,0.


