---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html 
sidebar: sidebar 
keywords: upgrade, grid tasks, firewall, ports 
summary: Antes de atualizar um sistema StorageGRID, verifique se o sistema está pronto para acomodar a atualização. Certifique-se de que o sistema está funcionando normalmente e que todos os nós de grade estejam operacionais. 
---
= Verifique a condição do seu sistema StorageGRID antes de atualizar
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de atualizar um sistema StorageGRID, verifique se o sistema está pronto para acomodar a atualização. Certifique-se de que o sistema está funcionando normalmente e que todos os nós de grade estejam operacionais.

.Passos
. Faça login no Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
. Verifique e resolva quaisquer alertas ativos.
. Consulte link:../network/internal-grid-node-communications.html["Comunicações internas do nó da grade"] e link:../network/external-communications.html["Comunicações externas"] para garantir que todas as portas necessárias para StorageGRID 12.1 estejam abertas antes de você realizar a atualização.
+

NOTE: Não são necessárias portas adicionais ao atualizar para StorageGRID 12.1.


