---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: Saiba como seu sistema StorageGRID será afetado durante a atualização. 
---
= Como seu sistema é afetado durante a atualização
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Saiba como seu sistema StorageGRID será afetado durante a atualização.



== O acesso SSH externo é permitido até que a atualização seja concluída

O acesso SSH externo é permitido durante a atualização.  Quando a atualização for concluída, o acesso SSH externo será bloqueado por padrão.  Após a atualização, você pode usar a aba *Bloquear SSH* disponível na página *Grid Manager* > *Configurações de segurança* paralink:../admin/manage-external-ssh-access.html["gerenciar acesso SSH externo"] .  O acesso SSH entre nós da grade não é afetado.



== As atualizações do StorageGRID não causam interrupções

O sistema StorageGRID pode obter e recuperar dados de aplicativos clientes durante todo o processo de atualização. Se aprovar a atualização de todos os nós do mesmo tipo (por exemplo, nós de storage), os nós serão derrubados um de cada vez, portanto, não haverá tempo em que todos os nós de grade ou todos os nós de grade de um determinado tipo estejam indisponíveis.

Para permitir disponibilidade contínua, verifique se sua política de ILM contém regras que especificam o armazenamento de várias cópias de cada objeto. Você também deve garantir que todos os clientes S3 externos estejam configurados para enviar solicitações para um dos seguintes:

* Um endereço IP virtual do grupo de alta disponibilidade (HA)
* Um balanceador de carga de terceiros de alta disponibilidade
* Vários nós de gateway para cada cliente
* Vários nós de storage para cada cliente




== As aplicações do cliente podem sofrer interrupções de curto prazo

O sistema StorageGRID pode obter e recuperar dados de aplicativos clientes durante todo o processo de atualização; no entanto, as conexões de clientes com nós de gateway individuais ou nós de storage podem ser interrompidas temporariamente se a atualização precisar reiniciar os serviços nesses nós. A conetividade será restaurada após a conclusão do processo de atualização e os serviços são retomados nos nós individuais.

Talvez seja necessário agendar o tempo de inatividade para aplicar uma atualização se a perda de conetividade por um curto período não for aceitável. Você pode usar a aprovação seletiva para agendar quando certos nós são atualizados.


NOTE: Você pode usar vários gateways e grupos de alta disponibilidade (HA) para fornecer failover automático durante o processo de atualização. Consulte as instruções para link:../admin/configure-high-availability-group.html["configurando grupos de alta disponibilidade"].



== Os reparos em segundo plano não serão executados em grades com nós de versões mistas

Os reparos em segundo plano não são executados durante a atualização quando a grade contém nós de versões mistas.  Quaisquer inconsistências que ocorrerem durante uma interrupção do site não serão reparadas até que a atualização seja concluída.



== O firmware do dispositivo foi atualizado

Durante a atualização do StorageGRID 12.0:

* Todos os nós do dispositivo StorageGRID são atualizados automaticamente para a versão de firmware 12.0 do StorageGRID Appliance Installer.
* Os dispositivos SG6060 e SGF6024 são atualizados automaticamente para a versão de firmware do BIOS 3B08.EX e a versão de firmware do BMC 4.01.07.
* Os dispositivos SG100 e SG1000 são atualizados automaticamente para a versão de firmware do BIOS 3B13.EC e a versão de firmware do BMC 4.75.07.
* Os dispositivos SGF6112, SG6160, SG110 e SG1100 são atualizados automaticamente para a versão de firmware do BIOS 3A14.QD e a versão de firmware do BMC 3.19.07.




== As políticas de ILM são tratadas de forma diferente de acordo com seu status

* A política ativa permanecerá a mesma após a atualização.
* Apenas as últimas 10 políticas históricas são preservadas na atualização.
* Se houver uma política proposta, ela será excluída durante a atualização.




== Os alertas podem ser acionados

Os alertas podem ser acionados quando os serviços começam e param e quando o sistema StorageGRID está operando como um ambiente de versão mista (alguns nós de grade executando uma versão anterior, enquanto outros foram atualizados para uma versão posterior). Outros alertas podem ser acionados após a conclusão da atualização.

Por exemplo, você pode ver o alerta *Não foi possível comunicar com o nó* quando os serviços são interrompidos, ou pode ver o alerta *Erro de comunicação do Cassandra* quando alguns nós foram atualizados para o StorageGRID 12.0, mas outros nós ainda estão executando o StorageGRID 11.9.  Em geral, esses alertas serão apagados quando a atualização for concluída.

O alerta *Posicionamento do ILM inatingível* pode ser acionado quando os nós de armazenamento são interrompidos durante a atualização para o StorageGRID 12.0.  Este alerta pode persistir por 1 dia após a conclusão da atualização.

Após a conclusão da atualização, você pode revisar qualquer alerta relacionado a atualização selecionando *alertas resolvidos recentemente* ou *alertas atuais* no painel do Gerenciador de Grade.



== As alterações de configuração são restritas


NOTE: Esta lista se aplica especificamente a atualizações do StorageGRID 11.9 para o StorageGRID 12.0.  Se você estiver atualizando para outra versão do StorageGRID , consulte a lista de alterações restritas nas instruções de atualização dessa versão.

Até que a tarefa *Ativar novo recurso* seja concluída:

* Não faça alterações na configuração da grade.
* Não ative ou desative nenhum novo recurso.
* Não atualize a configuração do ILM. Caso contrário, você pode experimentar comportamento inconsistente e inesperado de ILM.
* Não aplique um hotfix ou recupere um nó de grade.
+

NOTE: Entre em Contato com o suporte técnico se precisar recuperar um nó durante a atualização.

* Você não deve gerenciar grupos de HA, interfaces de VLAN ou pontos de extremidade do balanceador de carga enquanto estiver atualizando para o StorageGRID 12.0.
* Não exclua nenhum grupo de HA até que a atualização para o StorageGRID 12.0 seja concluída.  Endereços IP virtuais em outros grupos de HA podem se tornar inacessíveis.


Até que a tarefa *etapas de atualização final* seja concluída:

* Não execute um procedimento de expansão.
* Não efetue um procedimento de desativação.

