---
permalink: upgrade/obtaining-required-materials-for-software-upgrade.html 
sidebar: sidebar 
keywords: upgrade, requirements, rhel, red hat, linux, ubuntu, debian 
summary: Antes de iniciar a atualização de software, obtenha todos os materiais necessários. 
---
= Obtenha os materiais necessários para uma atualização de software StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de iniciar a atualização de software, obtenha todos os materiais necessários.

[cols="1a,3a"]
|===
| Item | Notas 


 a| 
Serviço de laptop
 a| 
O computador portátil de serviço deve ter:

* Porta de rede
* Cliente SSH (por exemplo, PuTTY)




 a| 
link:../admin/web-browser-requirements.html["Navegador da Web suportado"]
 a| 
O suporte do navegador normalmente muda para cada versão do StorageGRID. Certifique-se de que o seu navegador é compatível com a nova versão do StorageGRID.



 a| 
Frase-passe do aprovisionamento
 a| 
A frase-passe é criada e documentada quando o sistema StorageGRID é instalado pela primeira vez. A senha de provisionamento não está listada no `Passwords.txt` arquivo.



 a| 
Arquivo RPM ou DEB do Linux
 a| 
Se algum nó for implantado em hosts Linux, você deve link:linux-installing-rpm-or-deb-package-on-all-hosts.html["Baixe e instale o pacote RPM ou DEB em todos os hosts"] antes de iniciar a atualização.

Certifique-se de que seu sistema operacional Linux atenda aos requisitos mínimos de versão do kernel do StorageGRID. Ver link:../swnodes/installing-linux.html["Instalar o StorageGRID em hosts Linux"] .



 a| 
Documentação do StorageGRID
 a| 
* https://library.netapp.com/ecm/ecm_download_file/ECMLP3351267["Notas de lançamento"^]. Você precisa fazer login com sua NetApp conta ou criar uma conta para acessar as notas de versão. Leia-as atentamente antes de iniciar a atualização.
* https://kb.netapp.com/hybrid/StorageGRID/Maintenance/StorageGRID_12.0_software_upgrade_resolution_guide["Guia de resolução de atualização do software StorageGRID"^]para a versão principal para a qual você está atualizando (é necessário fazer login)
* Outro https://docs.netapp.com/us-en/storagegrid-family/index.html["Documentação do StorageGRID"^], conforme necessário.


|===