---
permalink: upgrade/verifying-installed-version-of-storagegrid.html 
sidebar: sidebar 
keywords: storagegrid, version, current version, previous version 
summary: Antes de iniciar a atualização, verifique se a versão anterior do StorageGRID está atualmente instalada com o hotfix disponível mais recente aplicado. 
---
= Verifique a versão instalada do StorageGRID antes de atualizar
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de iniciar a atualização, verifique se a versão anterior do StorageGRID está atualmente instalada com o hotfix disponível mais recente aplicado.

.Sobre esta tarefa
Antes de atualizar para StorageGRID 12.1, seu grid deve ter StorageGRID 12.0 ou posterior instalado. Se você estiver usando uma versão anterior do StorageGRID, você deve instalar todos os arquivos de atualização anteriores junto com seus hotfixes mais recentes (altamente recomendado) até que a versão atual do seu grid seja pelo menos StorageGRID 12.0.0.

Um possível caminho de atualização é mostrado no <<example-upgrade-path,exemplo>>.


CAUTION: A NetApp recomenda fortemente que você aplique o hotfix mais recente para cada versão do StorageGRID antes de atualizar para a próxima versão e que você também aplique o hotfix mais recente para cada nova versão instalada.  Em alguns casos, você deve aplicar um hotfix para evitar o risco de perda de dados.  Consulte https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp Downloads: StorageGRID"^] e as notas de versão de cada hotfix para saber mais.



[[verify-installed-version]]
== Verificar versão instalada

.Passos
. Faça login no Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
. Na parte superior do Gerenciador de Grade, selecione *Ajuda* > *sobre*.
. Verifique se a *Versão* é 11.9.0.8 ou posterior.
. Se a *Versão* não for 11.9.0.8 ou posterior, vá para https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp Downloads: StorageGRID"^] para baixar os arquivos de atualização e hotfix necessários.
. link:../upgrade/index.html["Siga as instruções de atualização"]para cada versão que você baixou. link:../maintain/storagegrid-hotfix-procedure.html["Aplique o hotfix mais recente"] para cada lançamento (altamente recomendado).


Consulte o exemplo de atualização a seguir.



[[example-upgrade-pathexample-upgrade-to-storagegrid-12-0-from-version-11-8]]
== [[example-upgrade-path]]Exemplo: Atualizar para o StorageGRID 12.0 da versão 11.8

O exemplo a seguir mostra os passos para atualizar do StorageGRID versão 11.9 para a versão 12.0 em preparação para uma atualização do StorageGRID 12.1.

Transfira e instale o software na seguinte sequência para preparar o seu sistema para a atualização:

. Atualize para a versão principal do StorageGRID 11.8.0.
. Aplique o hotfix do StorageGRID 11,8.0._y_ mais recente.
. Atualize para a versão principal do StorageGRID 11.9.0.
. Aplique o hotfix do StorageGRID 11.9.0.8 ou posterior.

