---
permalink: upgrade/whats-new.html 
sidebar: sidebar 
keywords: what is new in StorageGRID 12.0 
summary: Esta versão do StorageGRID introduz os seguintes recursos e alterações funcionais. 
---
= Novidades do StorageGRID 12,0
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esta versão do StorageGRID introduz os seguintes recursos e alterações funcionais.



== Replicação entre grade com S3 Object Lock

Você pode configurar a replicação entre grade entre buckets com o S3 Object Lock ativado. link:../admin/grid-federation-what-is-cross-grid-replication.html#cgr-with-ol["Replicação entre grade com S3 Object Lock"]Consulte a .

A NetApp recomenda usar esse recurso somente entre os buckets de origem e destino do StorageGRID 12,0. No entanto, esse recurso é suportado entre os buckets de origem do StorageGRID 11,9 com o bloqueio de objeto S3 desativado e os buckets de destino do StorageGRID 12,0 com o bloqueio de objeto S3 ativado.



== Segurança



=== Aprimoramento de segurança para senhas criptografadas em disco

Segurança de senha melhorada, incluindo uma contagem de hash redonda altamente aumentada para hashes de senha SHA512.



== S3 baldes



=== Baldes de ramificação

Agora você pode link:../tenant/manage-branch-bucket-html["crie buckets de ramificação"]usar um balde S3. Um bucket de ramificação fornece acesso a objetos de bucket do S3 como eles existiam em um determinado momento. Um bucket de ramificação não é o mesmo que um backup.



== Interface do utilizador



=== Tema escuro

As configurações de tema escuro e tema do sistema estão disponíveis no menu Usuário do Gerenciador de Grade e Gerenciador de Tenant.



== Melhorias no Grid Manager



=== Configurar o melhoramento das regiões

A página Regiões no Gerenciador de Grade agora inclui uma guia *região padrão*. Você pode usar essa guia para alterar a região padrão definida para buckets do S3. link:../ilm/configuring-regions-optional-and-s3-only.html["Saiba mais"].
