---
permalink: upgrade/whats-new.html 
sidebar: sidebar 
keywords: what is new in StorageGRID 12.0 
summary: Esta versão do StorageGRID introduz os seguintes recursos e alterações funcionais. 
---
= Novidades no StorageGRID 12.0
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esta versão do StorageGRID introduz os seguintes recursos e alterações funcionais.



== Aparelhos

* A capacidade de armazenamento e a eficiência de custos aumentaram significativamente.
* Atualizações automatizadas de firmware de unidade aumentam a confiabilidade do sistema e reduzem a sobrecarga de manutenção.




== Inteligência artificial (IA) e aprendizado de máquina (ML)

* link:../tenant/what-is-branch-bucket.html["Baldes de galhos"]permitir versões pontuais de buckets que facilitam a recuperação mais rápida de ransomware e conjuntos de dados isolados para testes e experimentação.
* Uma camada de cache S3 melhora o desempenho do treinamento de IA/ML.




== Capacidade

O StorageGRID agora suporta um trilhão de objetos, o que é mais que o dobro do limite anterior.  Consulte o https://fusion.netapp.com/["Ferramenta NetApp Fusion"^] para dimensionar e projetar o StorageGRID.



== Atualizações de Cassandra

O StorageGRID agora usa uma versão mais recente do Cassandra para armazenamento de metadados.  Esta versão do Cassandra usa o espaço em disco de forma mais eficiente para armazenar mais metadados.

Depois de vocêlink:../upgrade/index.html["atualização do StorageGRID 11.9 para 12.0"] , uma atualização do formato de metadados ocorrerá em segundo plano por um a três dias.  Durante esse período, certos procedimentos de manutenção que envolvem streaming de metadados, como expansão, serão desabilitados.

Consulte link:../upgrade/performing-upgrade.html#upgrade-other-nodes["Atualizar outros nós"] .



== Federação

* Agora você podelink:../admin/managing-users.html#import-federated-users["importar até 100 usuários federados"] em StorageGRID.
* Agora você podelink:../ilm/configuring-regions-optional-and-s3-only.html["modificar a região padrão"] para buckets S3.  Esse recurso oferece maior flexibilidade no gerenciamento de localidade e conformidade de dados.
* Agora você pode configurar a replicação entre grades entre buckets com o S3 Object Lock ativado. Consulte link:../admin/grid-federation-what-is-cross-grid-replication.html#cgr-with-ol["Replicação entre grades com bloqueio de objeto S3"] .
+
A NetApp recomenda usar esse recurso somente entre os buckets de origem e destino do StorageGRID 12.0.  No entanto, esse recurso é suportado entre buckets de origem do StorageGRID 11.9 com o S3 Object Lock desabilitado e buckets de destino do StorageGRID 12.0 com o S3 Object Lock habilitado.





== Gerenciabilidade

* Melhoroulink:../maintain/decommission-procedure.html["procedimento de descomissionamento"] reduz o tempo e a complexidade para aumentar a eficiência operacional.
* O comportamento aprimorado para consistência global forte fornece tolerância a falhas de site para solicitações de clientes quando as grades têm três ou mais sites.
+
** Novas instalações do StorageGRID 12.0 e posteriores usarão por padrão a semântica do Quorum quandolink:../s3/consistency.html["consistência global forte"] está definido.
** Se você atualizar do StorageGRID 11.9 para o StorageGRID 12.0, as grades atualizadas manterão o comportamento anterior para uma consistência global forte.





NOTE: Se você precisar reverter para o comportamento anterior para consistência global forte, consulte https://kb.netapp.com/hybrid/StorageGRID/Object_Mgmt/Configuring_StorageGRID_quorum_semantics_for_strong-global_consistency["Configurando a semântica do StorageGRID Quorum para consistência global forte"^] para obter instruções.

* A capacidade de iniciar uploads de log paralink:../admin/configure-autosupport-grid-manager.html["AutoSupport"] ajuda a melhorar a capacidade de resposta do suporte.
* Reduzido https://docs.netapp.com/us-en/storagegrid-appliances/index.html["aparelho"^] O tempo de reinicialização minimiza o tempo de inatividade para melhorar a disponibilidade geral do sistema.
* link:../maintain/move-adc-service.html["A capacidade de mover o serviço ADC"]para outro nó de armazenamento aumenta a flexibilidade e a resiliência no gerenciamento de nós de armazenamento que hospedam o serviço ADC.  Você pode mover o serviço ADC antes de desativar um nó de armazenamento ou converter um nó de armazenamento em um nó somente de dados.
* Para maximizar a capacidade de armazenamento de dados, você podelink:../maintain/convert-to-data-only-node.html["converter um nó de armazenamento em um nó somente de dados"] , o que faz com que os metadados nesse nó sejam migrados para nós de armazenamento combinados ou somente de metadados.
* A capacidade de qualquer nó de administraçãolink:../maintain/selecting-node-recovery-procedure.html["recuperar qualquer outro nó"] (exceto o nó administrativo primário) melhora a recuperação do sistema e a tolerância a falhas, melhorando a confiabilidade geral.
* Os usuários agora podem usar um bucket S3 paralink:../monitor/configure-log-management.html#use-a-bucket["armazenar logs de auditoria por um longo período de tempo"] .




== Segurança

* Criptografia de dados mais forte e proteção de integridade proporcionam segurança e desempenho aprimorados.
* O aumento da segurança das senhas armazenadas reduz o risco de acesso não autorizado.
* link:../admin/manage-external-ssh-access.html["SSH é bloqueado por padrão"]para aumentar a segurança e, ao mesmo tempo, permitir acesso controlado.




== Grupos de inquilinos

* Agora você podelink:../tenant/manage-groups.html["configurar uma nova política de confiança S3"] para dar suporte à API AssumeRole.  A função AssumeRole fornece credenciais de curto prazo para maior segurança e controle de acesso flexível.
* A cota de contagem de objetos por bucket permite melhor controle e gerenciamento dos recursos de armazenamento.




== Interface do usuário

* As configurações de tema escuro e tema do sistema estão disponíveis no menu Usuário do Grid Manager e do Tenant Manager.
* A página do servidor de auditoria e syslog, renomeadalink:../monitor/configure-log-management.html["Gerenciamento de logs"] , foi refatorado, com adições para armazenar logs em um bucket do sistema para fins de backup.
* A página Topologia de grade legada foi removida.  Nas últimas versões do StorageGRID , as operações e métricas disponíveis nessa página foram migradas para outras páginas no Grid Manager, especialmente para alink:../monitor/viewing-nodes-page.html["Página de nós"] .

