---
permalink: ubuntu/automating-installation.html 
sidebar: sidebar 
keywords: how to automate ubuntu or debian installation 
summary: Você pode automatizar a instalação do serviço de host StorageGRID e a configuração de nós de grade. 
---
= Automatize a instalação (Ubuntu ou Debian)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode automatizar a instalação do serviço de host StorageGRID e a configuração de nós de grade.

.Sobre esta tarefa
Automatizar a implantação pode ser útil em qualquer um dos seguintes casos:

* Você já usa uma estrutura de orquestração padrão, como Ansible, Puppet ou Chef, para implantar e configurar hosts físicos ou virtuais.
* Você pretende implantar várias instâncias do StorageGRID.
* Você está implantando uma instância grande e complexa do StorageGRID.


O serviço de host do StorageGRID é instalado por um pacote e impulsionado por arquivos de configuração que podem ser criados interativamente durante uma instalação manual ou preparados com antecedência (ou programaticamente) para permitir a instalação automatizada usando estruturas de orquestração padrão. O StorageGRID fornece scripts Python opcionais para automatizar a configuração de dispositivos StorageGRID e todo o sistema StorageGRID (a "grade"). Você pode usar esses scripts diretamente ou inspecioná-los para saber como usar a API REST de instalação do StorageGRID nas ferramentas de implantação e configuração de grade que você mesmo desenvolve.



== Automatize a instalação e a configuração do serviço de host StorageGRID

É possível automatizar a instalação do serviço de host StorageGRID usando estruturas de orquestração padrão, como Ansible, Puppet, Chef, Fabric ou SaltStack.

O serviço de host StorageGRID é empacotado em um DEB e é conduzido por arquivos de configuração que podem ser preparados com antecedência (ou programaticamente) para habilitar a instalação automatizada. Se você já usa uma estrutura de orquestração padrão para instalar e configurar o Ubuntu ou Debian, adicionar StorageGRID aos seus playbooks ou receitas deve ser simples.

Você pode automatizar estas tarefas:

. Instalando o Linux
. Configurando o Linux
. Configuração de interfaces de rede de host para atender aos requisitos do StorageGRID
. Configuração do storage de host para atender aos requisitos do StorageGRID
. Instalando o Docker
. Instalar o serviço de host StorageGRID
. Criando arquivos de configuração do nó StorageGRID em `/etc/storagegrid/nodes`
. Validando arquivos de configuração de nó do StorageGRID
. Iniciando o serviço de host do StorageGRID




=== Exemplo de função e manual de estratégia do Ansible

Exemplo de função do Ansible e manual de estratégia são fornecidos com o arquivo de instalação `/extras` na pasta. O manual de estratégia do Ansible mostra como a `storagegrid` função prepara os hosts e instala o StorageGRID nos servidores de destino. Você pode personalizar a função ou o manual de estratégia conforme necessário.



== Automatize a configuração do StorageGRID

Depois de implantar os nós de grade, você pode automatizar a configuração do sistema StorageGRID.

.Antes de começar
* Você sabe a localização dos seguintes arquivos do arquivo de instalação.
+
[cols="1a,1a"]
|===
| Nome do ficheiro | Descrição 


| configure-StorageGRID.py  a| 
Script Python usado para automatizar a configuração



| configure-StorageGRID.sample.json  a| 
Exemplo de arquivo de configuração para uso com o script



| configure-StorageGRID.blank.json  a| 
Arquivo de configuração em branco para uso com o script

|===
* Criou um `configure-storagegrid.json` ficheiro de configuração. Para criar este ficheiro, pode modificar o ficheiro de configuração de exemplo (`configure-storagegrid.sample.json`) ou o ficheiro de configuração em branco (`configure-storagegrid.blank.json`).


.Sobre esta tarefa
Você pode usar o `configure-storagegrid.py` script Python e o `configure-storagegrid.json` arquivo de configuração para automatizar a configuração do seu sistema StorageGRID.


NOTE: Você também pode configurar o sistema usando o Gerenciador de Grade ou a API de Instalação.

.Passos
. Faça login na máquina Linux que você está usando para executar o script Python.
. Mude para o diretório onde você extraiu o arquivo de instalação.
+
Por exemplo:

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
 `platform`onde está `debs`, `rpms`, `vsphere` ou .

. Execute o script Python e use o arquivo de configuração que você criou.
+
Por exemplo:

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.Resultado
Um arquivo do Pacote de recuperação `.zip` é gerado durante o processo de configuração e é baixado para o diretório onde você está executando o processo de instalação e configuração. Você deve fazer backup do arquivo do pacote de recuperação para que você possa recuperar o sistema StorageGRID se um ou mais nós de grade falhar. Por exemplo, copie-o para um local de rede seguro e de backup e para um local seguro de armazenamento em nuvem.


CAUTION: O arquivo do pacote de recuperação deve ser protegido porque contém chaves de criptografia e senhas que podem ser usadas para obter dados do sistema StorageGRID.

Se você especificou que senhas aleatórias devem ser geradas, abra o `Passwords.txt` arquivo e procure as senhas necessárias para acessar seu sistema StorageGRID.

[listing]
----
######################################################################
##### The StorageGRID "Recovery Package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
O sistema StorageGRID é instalado e configurado quando é apresentada uma mensagem de confirmação.

[listing]
----
StorageGRID has been configured and installed.
----
.Informações relacionadas
link:overview-of-installation-rest-api.html["API REST de instalação"]
