---
permalink: ubuntu/configuring-host-storage.html 
sidebar: sidebar 
keywords: how to configure host storage 
summary: Você deve alocar volumes de storage de bloco a cada host. 
---
= Configurar o armazenamento do host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve alocar volumes de storage de bloco a cada host.

.Antes de começar
Você revisou os tópicos a seguir, que fornecem informações necessárias para realizar esta tarefa:

* link:storage-and-performance-requirements.html["Requisitos de storage e desempenho"]
* link:node-container-migration-requirements.html["Requisitos de migração de contêiner de nós"]


.Sobre esta tarefa
Ao alocar LUNs (Block Storage volumes) para hosts, use as tabelas em "requisitos de armazenamento" para determinar o seguinte:

* Número de volumes necessários para cada host (com base no número e nos tipos de nós que serão implantados nesse host)
* Categoria de storage para cada volume (ou seja, dados do sistema ou dados de objeto)
* Tamanho de cada volume


Você usará essas informações, bem como o nome persistente atribuído pelo Linux a cada volume físico quando implantar nós do StorageGRID no host.


NOTE: Você não precisa particionar, formatar ou montar qualquer um desses volumes; você só precisa garantir que eles sejam visíveis para os hosts.


NOTE: Somente um LUN de dados de objeto é necessário para nós de storage somente de metadados.

Evite usar arquivos de dispositivo especiais "brutos" (`/dev/sdb`, por exemplo) ao compor sua lista de nomes de volume. Esses arquivos podem mudar através das reinicializações do host, o que afetará o funcionamento adequado do sistema. Se você estiver usando iSCSI LUNs e Device Mapper Multipathing, considere usar alias de multipath no `/dev/mapper` diretório, especialmente se a topologia SAN incluir caminhos de rede redundantes para o armazenamento compartilhado. Em alternativa, pode utilizar as ligações virtuais criadas pelo sistema em `/dev/disk/by-path/` para os nomes de dispositivos persistentes.

Por exemplo:

[listing]
----
ls -l
$ ls -l /dev/disk/by-path/
total 0
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:00:07.1-ata-2 -> ../../sr0
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0 -> ../../sda
lrwxrwxrwx 1 root root 10 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:1:0 -> ../../sdb
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:2:0 -> ../../sdc
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:3:0 -> ../../sdd
----
Os resultados serão diferentes para cada instalação.

Atribua nomes amigáveis a cada um desses volumes de storage de bloco para simplificar a instalação inicial do StorageGRID e os procedimentos de manutenção futuros. Se você estiver usando o driver multipath de mapeamento de dispositivos para acesso redundante a volumes de armazenamento compartilhados, você poderá usar o `alias` campo em `/etc/multipath.conf` seu arquivo.

Por exemplo:

[listing]
----
multipaths {
     multipath {
          wwid 3600a09800059d6df00005df2573c2c30
          alias docker-storage-volume-hostA
     }
     multipath {
          wwid 3600a09800059d6df00005df3573c2c30
          alias sgws-adm1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df4573c2c30
          alias sgws-adm1-audit-logs
     }
     multipath {
          wwid 3600a09800059d6df00005df5573c2c30
          alias sgws-adm1-tables
     }
     multipath {
          wwid 3600a09800059d6df00005df6573c2c30
          alias sgws-gw1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df7573c2c30
          alias sgws-sn1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df7573c2c30
          alias sgws-sn1-rangedb-0
     }
     …
----
Usar o campo alias dessa forma faz com que os aliases apareçam como dispositivos de bloco `/dev/mapper` no diretório do host, permitindo que você especifique um nome amigável e facilmente validado sempre que uma operação de configuração ou manutenção exigir a especificação de um volume de armazenamento de bloco.

Se você estiver configurando o armazenamento compartilhado para suportar a migração de nós do StorageGRID e usando multipathing do Mapeador de dispositivos, você poderá criar e instalar um comum `/etc/multipath.conf` em todos os hosts localizados. Apenas certifique-se de usar um volume de armazenamento Docker diferente em cada host. Usar aliases e incluir o nome de host de destino no alias para cada LUN de volume de armazenamento do Docker tornará isso fácil de lembrar e é recomendado.


NOTE: O suporte para Docker como o mecanismo de contentor para implantações somente de software está obsoleto. O Docker será substituído por outro mecanismo de contentor em uma versão futura.

.Informações relacionadas
* link:storage-and-performance-requirements.html["Requisitos de storage e desempenho"]
* link:node-container-migration-requirements.html["Requisitos de migração de contêiner de nós"]

