---
permalink: ubuntu/cpu-and-ram-requirements.html 
sidebar: sidebar 
keywords: cpu, ram, cpu cores 
summary: Antes de instalar o software StorageGRID, verifique e configure o hardware para que ele esteja pronto para suportar o sistema StorageGRID. 
---
= Requisitos de CPU e RAM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar o software StorageGRID, verifique e configure o hardware para que ele esteja pronto para suportar o sistema StorageGRID.

Cada nó do StorageGRID requer os seguintes recursos mínimos:

* Núcleos de CPU: 8 por nó
* RAM: Depende do total de RAM disponível e da quantidade de software que não seja StorageGRID executado no sistema
+
** Geralmente, pelo menos 24 GB por nó e 2 a 16 GB menos do que a RAM total do sistema
** Um mínimo de 64 GB para cada locatário que terá aproximadamente 5.000 buckets




Certifique-se de que o número de nós de StorageGRID que você planeja executar em cada host físico ou virtual não exceda o número de núcleos de CPU ou a RAM física disponível. Se os hosts não forem dedicados à execução do StorageGRID (não recomendado), certifique-se de considerar os requisitos de recursos dos outros aplicativos.


CAUTION: Monitore regularmente o uso da CPU e da memória para garantir que esses recursos continuem a acomodar sua carga de trabalho. Por exemplo, duplicar a alocação de RAM e CPU para nós de storage virtual forneceria recursos semelhantes aos fornecidos para nós de dispositivos StorageGRID. Além disso, se a quantidade de metadados por nó exceder 500 GB, considere aumentar a RAM por nó para 48 GB ou mais. Para obter informações sobre como gerenciar o armazenamento de metadados de objetos, aumentar a configuração espaço reservado de metadados e monitorar o uso da CPU e da memória, consulte as instruções para link:../admin/index.html["administrar"], link:../monitor/index.html["monitorização"]e link:../upgrade/index.html["a atualizar"]StorageGRID.

Se o hyperthreading estiver habilitado nos hosts físicos subjacentes, você poderá fornecer 8 núcleos virtuais (4 núcleos físicos) por nó. Se o hyperthreading não estiver habilitado nos hosts físicos subjacentes, você deverá fornecer 8 núcleos físicos por nó.

Se você estiver usando máquinas virtuais como hosts e tiver controle sobre o tamanho e o número de VMs, use uma única VM para cada nó do StorageGRID e dimensione a VM de acordo.

Para implantações de produção, você não deve executar vários nós de storage no mesmo hardware de storage físico ou host virtual. Cada nó de storage em uma única implantação do StorageGRID deve estar em seu próprio domínio de falha isolado. Você pode maximizar a durabilidade e a disponibilidade dos dados de objetos se garantir que uma única falha de hardware só pode afetar um único nó de storage.

Consulte também link:storage-and-performance-requirements.html["Requisitos de storage e desempenho"].
