---
permalink: ubuntu/example-node-configuration-files.html 
sidebar: sidebar 
keywords: example node configuration files 
summary: Você pode usar os arquivos de configuração de nó de exemplo para ajudar a configurar os arquivos de configuração de nó para o seu sistema StorageGRID. Os exemplos mostram arquivos de configuração de nós para todos os tipos de nós de grade. 
---
= Exemplo de arquivos de configuração de nó
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar os arquivos de configuração de nó de exemplo para ajudar a configurar os arquivos de configuração de nó para o seu sistema StorageGRID. Os exemplos mostram arquivos de configuração de nós para todos os tipos de nós de grade.

Para a maioria dos nós, você pode adicionar informações de endereçamento de rede de administrador e cliente (IP, máscara, gateway, etc.) ao configurar a grade usando o Gerenciador de Grade ou a API de instalação. A exceção é o nó de administração principal. Se você quiser navegar até o IP de rede Admin do nó de administração principal para concluir a configuração da grade (porque a rede de grade não está roteada, por exemplo), você deve configurar a conexão de rede Admin para o nó de administração principal em seu arquivo de configuração de nó. Isso é mostrado no exemplo.


NOTE: Nos exemplos, o destino rede cliente foi configurado como uma prática recomendada, mesmo que a rede cliente esteja desativada por padrão.



== Exemplo para nó de administração principal

* Exemplo de nome de arquivo*: `/etc/storagegrid/nodes/dc1-adm1.conf`

* Exemplo de conteúdo do arquivo:*

[listing]
----
NODE_TYPE = VM_Admin_Node
ADMIN_ROLE = Primary
TEMPORARY_PASSWORD_TYPE = Use custom password
CUSTOM_TEMPORARY_PASSWORD = Passw0rd
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-adm1-var-local
BLOCK_DEVICE_AUDIT_LOGS = /dev/mapper/dc1-adm1-audit-logs
BLOCK_DEVICE_TABLES = /dev/mapper/dc1-adm1-tables
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003

GRID_NETWORK_IP = 10.1.0.2
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1

ADMIN_NETWORK_CONFIG = STATIC
ADMIN_NETWORK_IP = 192.168.100.2
ADMIN_NETWORK_MASK = 255.255.248.0
ADMIN_NETWORK_GATEWAY = 192.168.100.1
ADMIN_NETWORK_ESL = 192.168.100.0/21,172.16.0.0/21,172.17.0.0/21
----


== Exemplo para nó de storage

* Exemplo de nome do arquivo:* `/etc/storagegrid/nodes/dc1-sn1.conf`

* Exemplo de conteúdo do arquivo:*

[listing]
----
NODE_TYPE = VM_Storage_Node
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-sn1-var-local
BLOCK_DEVICE_RANGEDB_00 = /dev/mapper/dc1-sn1-rangedb-0
BLOCK_DEVICE_RANGEDB_01 = /dev/mapper/dc1-sn1-rangedb-1
BLOCK_DEVICE_RANGEDB_02 = /dev/mapper/dc1-sn1-rangedb-2
BLOCK_DEVICE_RANGEDB_03 = /dev/mapper/dc1-sn1-rangedb-3
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003

GRID_NETWORK_IP = 10.1.0.3
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----


== Exemplo para Gateway Node

* Exemplo de nome do arquivo:* `/etc/storagegrid/nodes/dc1-gw1.conf`

* Exemplo de conteúdo do arquivo:*

[listing]
----
NODE_TYPE = VM_API_Gateway
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-gw1-var-local
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003
GRID_NETWORK_IP = 10.1.0.5
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----


== Exemplo para um nó de administração não primário

* Exemplo de nome do arquivo:* `/etc/storagegrid/nodes/dc1-adm2.conf`

* Exemplo de conteúdo do arquivo:*

[listing]
----
NODE_TYPE = VM_Admin_Node
ADMIN_ROLE = Non-Primary
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-adm2-var-local
BLOCK_DEVICE_AUDIT_LOGS = /dev/mapper/dc1-adm2-audit-logs
BLOCK_DEVICE_TABLES = /dev/mapper/dc1-adm2-tables
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003

GRID_NETWORK_IP = 10.1.0.6
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----