---
permalink: ubuntu/installing-linux.html 
sidebar: sidebar 
keywords: how to install Linux 
summary: Você deve instalar o StorageGRID em todos os hosts de grade Ubuntu ou Debian. Para obter uma lista de versões suportadas, utilize a ferramenta de Matriz de interoperabilidade do NetApp. 
---
= Instale o Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve instalar o StorageGRID em todos os hosts de grade Ubuntu ou Debian. Para obter uma lista de versões suportadas, utilize a ferramenta de Matriz de interoperabilidade do NetApp.

.Antes de começar
Certifique-se de que seu sistema operacional atenda aos requisitos mínimos de versão do kernel do StorageGRID, conforme listado abaixo. Use o comando `uname -r` para obter a versão do kernel do seu sistema operacional ou consulte o fornecedor do seu sistema operacional.

*Nota:* o suporte para Ubuntu versões 18,04 e 20,04 foi obsoleto e será removido em uma versão futura.

[cols="1a,2a,3a"]
|===
| Versão Ubuntu | Versão mínima do kernel | Nome do pacote do kernel 


 a| 
18.04.6 (obsoleto)
 a| 
5,4.0-150-genérico
 a| 
linux-image-5,4.0-150-generic/bionic-updates, bionic-security, agora 5,4.0-150,167-18.04.1



 a| 
20.04.5 (obsoleto)
 a| 
5,4.0-131-genérico
 a| 
linux-image-5,4.0-131-generic/focal-updates, agora 5,4.0-131,147



 a| 
22.04.1
 a| 
5.15.0-47-genérico
 a| 
linux-image-5.15.0-47-generic/jammy-updates, jammy-security, agora 5.15.0-47,51



 a| 
24,04
 a| 
6,8.0-31-genérico
 a| 
linux-image-6,8.0-31-generic/noble, agora 6,8.0-31,31

|===
*Nota:* o suporte para a versão 11 do Debian foi obsoleto e será removido em uma versão futura.

[cols="1a,2a,2a"]
|===
| Versão Debian | Versão mínima do kernel | Nome do pacote do kernel 


 a| 
11 (obsoleto)
 a| 
5.10.0-18-amd64
 a| 
linux-image-5.10.0-18-amd64/estável, agora 5.10.150-1



 a| 
12
 a| 
6,1.0-9-amd64
 a| 
linux-image-6,1.0-9-amd64/stable, agora 6,1.27-1

|===
.Passos
. Instale o Linux em todos os hosts de grade física ou virtual de acordo com as instruções do distribuidor ou seu procedimento padrão.
+

NOTE: Não instale nenhum ambiente de desktop gráfico. Ao instalar o Ubuntu, você deve selecionar *utilitários de sistema padrão*. Selecionar *OpenSSH Server* é recomendado para habilitar o acesso ssh aos seus hosts Ubuntu. Todas as outras opções podem permanecer limpas.

. Certifique-se de que todos os hosts tenham acesso aos repositórios de pacotes Ubuntu ou Debian.
. Se a troca estiver ativada:
+
.. Execute o seguinte comando: `$ sudo swapoff --all`
.. Remova todas as entradas de troca de `/etc/fstab` para persistir as configurações.
+

NOTE: A falha ao desativar completamente a troca pode reduzir drasticamente o desempenho.




