---
permalink: ubuntu/understanding-apparmor-profile-installation.html 
sidebar: sidebar 
keywords: how to install AppArmor profile 
summary: Se você estiver operando em um ambiente Ubuntu auto-implantado e usando o sistema de controle de acesso obrigatório AppArmor, os perfis AppArmor associados aos pacotes instalados no sistema base podem ser bloqueados pelos pacotes correspondentes instalados com o StorageGRID. 
---
= Compreender a instalação do perfil AppArmor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você estiver operando em um ambiente Ubuntu auto-implantado e usando o sistema de controle de acesso obrigatório AppArmor, os perfis AppArmor associados aos pacotes instalados no sistema base podem ser bloqueados pelos pacotes correspondentes instalados com o StorageGRID.

Por padrão, os perfis AppArmor são instalados para os pacotes que você instala no sistema operacional base. Quando você executa esses pacotes a partir do contentor do sistema StorageGRID, os perfis AppArmor são bloqueados. Os pacotes base DHCP, MySQL, NTP e tcdump entram em conflito com o AppArmor, e outros pacotes básicos também podem entrar em conflito.

Você tem duas opções para lidar com perfis AppArmor:

* Desative perfis individuais para os pacotes instalados no sistema base que se sobrepõem aos pacotes no contentor do sistema StorageGRID. Quando você desativa perfis individuais, uma entrada aparece nos arquivos de log do StorageGRID indicando que AppArmor está habilitado.
+
Use os seguintes comandos:

+
[listing]
----
sudo ln -s /etc/apparmor.d/<profile.name> /etc/apparmor.d/disable/
sudo apparmor_parser -R /etc/apparmor.d/<profile.name>
----
+
*Exemplo:*

+
[listing]
----
sudo ln -s /etc/apparmor.d/bin.ping /etc/apparmor.d/disable/
sudo apparmor_parser -R /etc/apparmor.d/bin.ping
----
* Desative o AppArmor completamente. Para o Ubuntu 9,10 ou posterior, siga as instruções na comunidade online do Ubuntu: https://help.ubuntu.com/community/AppArmor#Disable_AppArmor_framework["Desativar AppArmor"^]. Desabilitar o AppArmor por completo pode não ser possível em versões mais recentes do Ubuntu.
+
Depois de desativar o AppArmor, nenhuma entrada indicando que o AppArmor está habilitado aparecerá nos arquivos de log do StorageGRID.


