---
permalink: network/external-communications.html 
sidebar: sidebar 
keywords: storagegrid, network port, external communications, ports, TCP, UDP, client communications 
summary: Os clientes precisam se comunicar com nós de grade para obter e recuperar conteúdo. As portas usadas dependem dos protocolos de storage de objetos escolhidos. Essas portas precisam estar acessíveis ao cliente. 
---
= Comunicações externas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os clientes precisam se comunicar com nós de grade para obter e recuperar conteúdo. As portas usadas dependem dos protocolos de storage de objetos escolhidos. Essas portas precisam estar acessíveis ao cliente.



== Acesso restrito às portas

Se as políticas de rede empresarial restringirem o acesso a qualquer uma das portas, você poderá fazer um dos seguintes procedimentos:

* link:../admin/configuring-load-balancer-endpoints.html["pontos de extremidade do balanceador de carga"]Utilize para permitir o acesso em portas definidas pelo utilizador.
* Remapear portas ao implantar nós. No entanto, você não deve remapear os pontos de extremidade do balanceador de carga. Consulte as informações sobre o mapeamento de portas para o nó StorageGRID:
+
** link:../rhel/creating-node-configuration-files.html#port-remap-keys["As chaves de remapa de porta para StorageGRID no Red Hat Enterprise Linux"]
** link:../ubuntu/creating-node-configuration-files.html#port-remap-keys["Port Remap chaves para StorageGRID no Ubuntu ou Debian"]
** link:../vmware/deploying-storagegrid-node-as-virtual-machine.html#vmware-remap-ports["Remapear portas para StorageGRID no VMware"]
** https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/optional-remapping-network-ports-for-appliance.html["Opcional: Remapear as portas de rede para o dispositivo"^]






== Portas usadas para comunicações externas

A tabela a seguir mostra as portas usadas para tráfego nos nós.


NOTE: Esta lista não inclui portas que possam ser configuradas como link:../admin/configuring-load-balancer-endpoints.html["pontos de extremidade do balanceador de carga"].

[cols="1a,1a,1a,1a,1a,4a"]
|===
| Porta | TCP ou UDP | Protocolo | De | Para | Detalhes 


 a| 
22
 a| 
TCP
 a| 
SSH
 a| 
Serviço de laptop
 a| 
Todos os nós
 a| 
SSH ou acesso ao console é necessário para procedimentos com etapas do console. Opcionalmente, você pode usar a porta 2022 em vez de 22.



 a| 
25
 a| 
TCP
 a| 
SMTP
 a| 
Nós de administração
 a| 
Servidor de e-mail
 a| 
Usado para alertas e AutoSupport baseados em e-mail. Você pode substituir a configuração de porta padrão de 25 usando a página servidores de e-mail.



 a| 
53
 a| 
TCP/UDP
 a| 
DNS
 a| 
Todos os nós
 a| 
Servidores DNS
 a| 
Usado para DNS.



 a| 
67
 a| 
UDP
 a| 
DHCP
 a| 
Todos os nós
 a| 
Serviço DHCP
 a| 
Usado opcionalmente para suportar a configuração de rede baseada em DHCP. O serviço dhclient não é executado para grades configuradas estaticamente.



 a| 
68
 a| 
UDP
 a| 
DHCP
 a| 
Serviço DHCP
 a| 
Todos os nós
 a| 
Usado opcionalmente para suportar a configuração de rede baseada em DHCP. O serviço dhclient não é executado para grades que usam endereços IP estáticos.



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
Navegador
 a| 
Nós de administração
 a| 
A porta 80 redireciona para a porta 443 para a interface de usuário do nó de administrador.



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
Navegador
 a| 
Aparelhos
 a| 
A porta 80 redireciona para a porta 8443 para o instalador do dispositivo StorageGRID.



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
Nós de storage com ADC
 a| 
AWS
 a| 
Usado para mensagens de serviços de plataforma enviadas para a AWS ou outros serviços externos que usam HTTP. Os locatários podem substituir a configuração padrão de porta HTTP de 80 ao criar um endpoint.



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
Nós de storage
 a| 
AWS
 a| 
As solicitações do Cloud Storage Pools enviadas para destinos da AWS que usam HTTP. Os administradores de grade podem substituir a configuração padrão de porta HTTP de 80 ao configurar um pool de armazenamento em nuvem.



 a| 
111
 a| 
TCP/UDP
 a| 
RPCBind
 a| 
Cliente NFS
 a| 
Nós de administração
 a| 
Usado pela exportação de auditoria baseada em NFS (portmap).

*Nota:* esta porta é necessária apenas se a exportação de auditoria baseada em NFS estiver ativada.

*Observação:* o suporte para NFS foi obsoleto e será removido em uma versão futura.



 a| 
123
 a| 
UDP
 a| 
NTP
 a| 
Nós NTP primários
 a| 
NTP externo
 a| 
Serviço de protocolo de tempo de rede. Os nós selecionados como fontes NTP primárias também sincronizam os horários do relógio com as fontes de hora NTP externas.



 a| 
161
 a| 
TCP/UDP
 a| 
SNMP
 a| 
Cliente SNMP
 a| 
Todos os nós
 a| 
Usado para polling SNMP. Todos os nós fornecem informações básicas; os nós de administração também fornecem dados de alerta. O padrão é a porta UDP 161 quando configurada.

*Nota:* esta porta só é necessária e só é aberta no firewall do nó se o SNMP estiver configurado. Se você pretende usar SNMP, você pode configurar portas alternativas.

*Observação:* para obter informações sobre como usar o SNMP com o StorageGRID, entre em Contato com o representante da conta do NetApp.



 a| 
162
 a| 
TCP/UDP
 a| 
Notificações SNMP
 a| 
Todos os nós
 a| 
Destinos de notificação
 a| 
Notificações e traps SNMP de saída padrão para a porta UDP 162.

*Nota:* esta porta só é necessária se o SNMP estiver ativado e os destinos de notificação estiverem configurados. Se você pretende usar SNMP, você pode configurar portas alternativas.

*Observação:* para obter informações sobre como usar o SNMP com o StorageGRID, entre em Contato com o representante da conta do NetApp.



 a| 
389
 a| 
TCP/UDP
 a| 
LDAP
 a| 
Nós de storage com ADC
 a| 
Ative Directory/LDAP
 a| 
Usado para conetar-se a um servidor ative Directory ou LDAP para Federação de identidade.



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
Navegador
 a| 
Nós de administração
 a| 
Usado por navegadores da Web e clientes de API de gerenciamento para acessar o Gerenciador de Grade e o Gerenciador de Tenant.

*Nota*: Se você fechar as portas 443 ou 8443 do Gerenciador de Grade, qualquer usuário conetado atualmente em uma porta bloqueada, incluindo você, perderá o acesso ao Gerenciador de Grade, a menos que seu endereço IP tenha sido adicionado à lista de endereços privilegiados. link:../admin/configure-firewall-controls.html["Configurar controles de firewall"]Consulte para configurar endereços IP privilegiados.



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
Nós de administração
 a| 
Ative Directory
 a| 
Usado por nós de administração que se conetam ao ative Directory se o logon único (SSO) estiver ativado.



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
Nós de storage com ADC
 a| 
AWS
 a| 
Usado para mensagens de serviços de plataforma enviadas para a AWS ou outros serviços externos que usam HTTPS. Os locatários podem substituir a configuração padrão de porta HTTP de 443 ao criar um endpoint.



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
Nós de storage
 a| 
AWS
 a| 
Solicitações do Cloud Storage Pools enviadas para destinos da AWS que usam HTTPS. Os administradores de grade podem substituir a configuração padrão de porta HTTPS de 443 ao configurar um pool de armazenamento em nuvem.



 a| 
903
 a| 
TCP
 a| 
NFS
 a| 
Cliente NFS
 a| 
Nós de administração
 a| 
Usado pela exportação de auditoria baseada em NFS (`rpc.mountd`).

*Nota:* esta porta é necessária apenas se a exportação de auditoria baseada em NFS estiver ativada.

*Observação:* o suporte para NFS foi obsoleto e será removido em uma versão futura.



 a| 
2022
 a| 
TCP
 a| 
SSH
 a| 
Serviço de laptop
 a| 
Todos os nós
 a| 
SSH ou acesso ao console é necessário para procedimentos com etapas do console. Opcionalmente, você pode usar a porta 22 em vez de 2022.



 a| 
2049
 a| 
TCP
 a| 
NFS
 a| 
Cliente NFS
 a| 
Nós de administração
 a| 
Usado pela exportação de auditoria baseada em NFS (NFS).

*Nota:* esta porta é necessária apenas se a exportação de auditoria baseada em NFS estiver ativada.

*Observação:* o suporte para NFS foi obsoleto e será removido em uma versão futura.



 a| 
5353
 a| 
UDP
 a| 
MDNS
 a| 
Todos os nós
 a| 
Todos os nós
 a| 
Fornece o serviço de DNS multicast (mDNS) que é usado para alterações de IP de grade completa e para descoberta de nó de administrador principal durante a instalação, expansão e recuperação.



 a| 
5696
 a| 
TCP
 a| 
KMIP
 a| 
Aparelho
 a| 
KMS
 a| 
Tráfego externo KMIP (Key Management Interoperability Protocol) de dispositivos configurados para criptografia de nó para o servidor de gerenciamento de chaves (KMS), a menos que uma porta diferente seja especificada na página de configuração KMS do instalador do dispositivo StorageGRID.



 a| 
8022
 a| 
TCP
 a| 
SSH
 a| 
Serviço de laptop
 a| 
Todos os nós
 a| 
O SSH na porta 8022 concede acesso ao sistema operacional básico em plataformas de appliance e nó virtual para suporte e solução de problemas. Essa porta não é usada para nós baseados em Linux (bare metal) e não é necessária para ser acessível entre nós de grade ou durante operações normais.



 a| 
8443
 a| 
TCP
 a| 
HTTPS
 a| 
Navegador
 a| 
Nós de administração
 a| 
Opcional. Usado por navegadores da Web e clientes de API de gerenciamento para acessar o Gerenciador de Grade. Pode ser usado para separar as comunicações do Grid Manager e do Tenant Manager.

*Nota*: Se você fechar as portas 443 ou 8443 do Gerenciador de Grade, qualquer usuário conetado atualmente em uma porta bloqueada, incluindo você, perderá o acesso ao Gerenciador de Grade, a menos que seu endereço IP tenha sido adicionado à lista de endereços privilegiados. link:../admin/configure-firewall-controls.html["Configurar controles de firewall"]Consulte para configurar endereços IP privilegiados.



 a| 
9022
 a| 
TCP
 a| 
SSH
 a| 
Serviço de laptop
 a| 
Aparelhos
 a| 
Concede acesso a dispositivos StorageGRID no modo de pré-configuração para suporte e solução de problemas. Esta porta não é necessária para estar acessível entre nós de grade ou durante operações normais.



 a| 
9091
 a| 
TCP
 a| 
HTTPS
 a| 
Serviço Grafana externo
 a| 
Nós de administração
 a| 
Usado por serviços externos Grafana para acesso seguro ao serviço StorageGRID Prometheus.

*Nota:* esta porta só é necessária se o acesso Prometheus baseado em certificado estiver ativado.



 a| 
9092
 a| 
TCP
 a| 
Kafka
 a| 
Nós de storage com ADC
 a| 
Cluster Kafka
 a| 
Usado para mensagens de serviços de plataforma enviadas para um cluster Kafka. Os locatários podem substituir a configuração padrão de porta Kafka de 9092 ao criar um endpoint.



 a| 
9443
 a| 
TCP
 a| 
HTTPS
 a| 
Navegador
 a| 
Nós de administração
 a| 
Opcional. Usado por navegadores da Web e clientes de API de gerenciamento para acessar o Gerenciador de locatários. Pode ser usado para separar as comunicações do Grid Manager e do Tenant Manager.



 a| 
18082
 a| 
TCP
 a| 
HTTPS
 a| 
S3 clientes
 a| 
Nós de storage
 a| 
Tráfego de clientes de S3 U diretamente para nós de storage (HTTPS).



 a| 
18083
 a| 
TCP
 a| 
HTTPS
 a| 
Clientes Swift
 a| 
Nós de storage
 a| 
Tráfego de cliente ágil diretamente para nós de storage (HTTPS).



 a| 
18084
 a| 
TCP
 a| 
HTTP
 a| 
S3 clientes
 a| 
Nós de storage
 a| 
Tráfego de cliente S3 diretamente para nós de storage (HTTP).



 a| 
18085
 a| 
TCP
 a| 
HTTP
 a| 
Clientes Swift
 a| 
Nós de storage
 a| 
Tráfego de cliente rápido diretamente para nós de armazenamento (HTTP).



 a| 
23000-23999
 a| 
TCP
 a| 
HTTPS
 a| 
Todos os nós na grade de origem para replicação entre grade
 a| 
Nós de administração e nós de gateway na grade de destino para replicação entre grade
 a| 
Esse intervalo de portas é reservado para conexões de federação de grade. Ambas as grades em uma determinada conexão usam a mesma porta.

|===