= Encontre o nome do host para nĂł de armazenamento
:allow-uri-read: 




[[find-hostname-for-storage-node]]
== Encontre o nome do host para nĂł de armazenamento

. Efetue login em qualquer nĂł de administraĂ§ĂŁo:
+
.. Introduza o seguinte comando: `ssh admin@_primary_Admin_Node_IP_`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
.. Digite o seguinte comando para mudar para root: `su -`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
+
Quando vocĂȘ estiver conetado como root, o prompt mudarĂĄ de `$` para `#`.



. Use o `/etc/hosts` arquivo para encontrar o nome do host do nĂł de armazenamento para os volumes de armazenamento restaurados. Para ver uma lista de todos os nĂłs na grade, digite o seguinte `cat /etc/hosts`: .




[[repair-data-if-all-volumes-have-failed]]
== Repare os dados se todos os volumes tiverem falhado

Se todos os volumes de armazenamento tiverem falhado, repare o nĂł inteiro. Siga as instruĂ§Ă”es para *dados replicados*, *dados codificados por apagamento (EC)* ou ambos, com base se vocĂȘ usa dados replicados, dados codificados por apagamento (EC) ou ambos.

Se apenas alguns volumes tiverem falhado, vĂĄ para <<Repare os dados se apenas alguns volumes tiverem falhado>>.


NOTE: NĂŁo Ă© possĂ­vel executar `repair-data` operaĂ§Ă”es para mais de um nĂł ao mesmo tempo. Para recuperar vĂĄrios nĂłs, entre em Contato com o suporte tĂ©cnico.

[role="tabbed-block"]
====
.Dados replicados
--
Se sua grade incluir dados replicados, use o `repair-data start-replicated-node-repair` comando com a `--nodes` opĂ§ĂŁo, onde `--nodes` estĂĄ o nome do host (nome do sistema), para reparar todo o nĂł de armazenamento.

Este comando repara os dados replicados em um nĂł de storage chamado SG-DC-SN3:

`repair-data start-replicated-node-repair --nodes SG-DC-SN3`


NOTE: Conforme os dados do objeto sĂŁo restaurados, o alerta *Objetos Perdidos* Ă© acionado se o sistema StorageGRID nĂŁo conseguir localizar os dados do objeto replicados.  Alertas podem ser disparados em nĂłs de armazenamento em todo o sistema.  VocĂȘ deve determinar a causa da perda e se a recuperaĂ§ĂŁo Ă© possĂ­vel. Ver link:../troubleshoot/investigating-potentially-lost-objects.html["Investigar objetos potencialmente perdidos"] .

--
.Dados codificados por apagamento (EC)
--
Se sua grade contiver dados codificados por apagamento, use o `repair-data start-ec-node-repair` comando com a `--nodes` opĂ§ĂŁo, onde `--nodes` estĂĄ o nome do host (nome do sistema), para reparar todo o nĂł de armazenamento.

Este comando repara os dados codificados por apagamento em um nĂł de storage chamado SG-DC-SN3:

`repair-data start-ec-node-repair --nodes SG-DC-SN3`

A operaĂ§ĂŁo retorna um Ășnico `repair ID` que identifica esta `repair_data` operaĂ§ĂŁo. Utilize esta `repair ID` opĂ§ĂŁo para monitorizar o progresso e o resultado `repair_data` da operaĂ§ĂŁo. Nenhum outro feedback Ă© retornado Ă  medida que o processo de recuperaĂ§ĂŁo Ă© concluĂ­do.

As reparaĂ§Ă”es de dados codificados por apagamento podem comeĂ§ar enquanto alguns nĂłs de storage estĂŁo offline. O reparo serĂĄ concluĂ­do depois que todos os nĂłs estiverem disponĂ­veis.

--
====


[[repair-data-if-only-some-volumes-have-failed]]
== Repare os dados se apenas alguns volumes tiverem falhado

Se apenas alguns dos volumes tiverem falhado, repare os volumes afetados. Siga as instruĂ§Ă”es para *dados replicados*, *dados codificados por apagamento (EC)* ou ambos, com base se vocĂȘ usa dados replicados, dados codificados por apagamento (EC) ou ambos.

Se todos os volumes tiverem falhado, vĂĄ para <<Repare os dados se todos os volumes tiverem falhado>>.

Introduza as IDs de volume em hexadecimal. Por exemplo, `0000` Ă© o primeiro volume e `000F` Ă© o dĂ©cimo sexto volume. VocĂȘ pode especificar um volume, um intervalo de volumes ou vĂĄrios volumes que nĂŁo estĂŁo em uma sequĂȘncia.

Todos os volumes devem estar no mesmo nĂł de storage. Se precisar restaurar volumes para mais de um nĂł de storage, entre em Contato com o suporte tĂ©cnico.

[role="tabbed-block"]
====
.Dados replicados
--
Se sua grade contiver dados replicados, use o `start-replicated-volume-repair` comando com a `--nodes` opĂ§ĂŁo para identificar o nĂł (onde `--nodes` estĂĄ o nome do host do nĂł). Em seguida, adicione a `--volumes` opĂ§ĂŁo ou `--volume-range`, como mostrado nos exemplos a seguir.

* Volume Ășnico*: Este comando restaura dados replicados para o volume `0002` em um nĂł de armazenamento chamado SG-DC-SN3:

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volumes 0002`

*Intervalo de volumes*: Este comando restaura dados replicados para todos os volumes no intervalo `0003` para `0009` um nĂł de armazenamento chamado SG-DC-SN3:

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volume-range 0003,0009`

*VĂĄrios volumes nĂŁo em uma sequĂȘncia*: Este comando restaura dados replicados para volumes `0001`, `0005` e `0008` em um nĂł de armazenamento chamado SG-DC-SN3:

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volumes 0001,0005,0008`


NOTE: Ă medida que os dados do objeto sĂŁo restaurados, o alerta *objetos perdidos* Ă© acionado se o sistema StorageGRID nĂŁo conseguir localizar dados de objeto replicados. Os alertas podem ser acionados em nĂłs de storage em todo o sistema. Observe a descriĂ§ĂŁo do alerta e as aĂ§Ă”es recomendadas para determinar a causa da perda e se a recuperaĂ§ĂŁo Ă© possĂ­vel.

--
.Dados codificados por apagamento (EC)
--
Se sua grade contiver dados codificados por apagamento, use o `start-ec-volume-repair` comando com a `--nodes` opĂ§ĂŁo para identificar o nĂł (onde `--nodes` estĂĄ o nome do host do nĂł). Em seguida, adicione a `--volumes` opĂ§ĂŁo ou `--volume-range`, como mostrado nos exemplos a seguir.

* Volume Ășnico*: Este comando restaura os dados codificados por apagamento para o volume `0007` em um nĂł de storage chamado SG-DC-SN3:

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volumes 0007`

*Intervalo de volumes*: Este comando restaura dados codificados por apagamento para todos os volumes no intervalo `0004` para `0006` um nĂł de armazenamento chamado SG-DC-SN3:

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volume-range 0004,0006`

*VĂĄrios volumes nĂŁo em uma sequĂȘncia*: Este comando restaura dados codificados por apagamento para volumes `000A`, `000C` e `000E` em um nĂł de armazenamento chamado SG-DC-SN3:

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volumes 000A,000C,000E`

A `repair-data` operaĂ§ĂŁo retorna um Ășnico `repair ID` que identifica esta `repair_data` operaĂ§ĂŁo. Utilize esta `repair ID` opĂ§ĂŁo para monitorizar o progresso e o resultado `repair_data` da operaĂ§ĂŁo. Nenhum outro feedback Ă© retornado Ă  medida que o processo de recuperaĂ§ĂŁo Ă© concluĂ­do.


NOTE: As reparaĂ§Ă”es de dados codificados por apagamento podem comeĂ§ar enquanto alguns nĂłs de storage estĂŁo offline. O reparo serĂĄ concluĂ­do depois que todos os nĂłs estiverem disponĂ­veis.

--
====