---
permalink: tenant/configuring-event-notifications.html 
sidebar: sidebar 
keywords: how to configure event notifications, bucket notification 
summary: Você ativa notificações para um bucket criando XML de configuração de notificação e usando o Gerenciador de locatário para aplicar o XML a um bucket. 
---
= Configurar notificações de eventos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você ativa notificações para um bucket criando XML de configuração de notificação e usando o Gerenciador de locatário para aplicar o XML a um bucket.

.Antes de começar
* Os serviços de plataforma foram ativados para sua conta de locatário por um administrador do StorageGRID.
* Você já criou um bucket para agir como a fonte das notificações.
* O endpoint que você pretende usar como destino para notificações de eventos já existe, e você tem sua URNA.
* Você pertence a um grupo de usuários que tem o link:tenant-management-permissions.html["Gerencie todos os buckets ou permissão de acesso root"]. Essas permissões substituem as configurações de permissão nas políticas de grupo ou bucket ao configurar o bucket usando o Gerenciador do locatário.


.Sobre esta tarefa
Você configura notificações de eventos associando o XML de configuração de notificação a um bucket de origem.  O XML de configuração de notificação segue as convenções do S3 para configurar notificações de bucket, com o tópico de destino do Amazon SNS, o tópico do Kafka ou o endpoint do webhook especificado como o URN de um endpoint.

Para obter informações gerais sobre notificações de eventos e como configurá-las, consulte o https://docs.aws.amazon.com/s3/["Documentação da Amazon"^]. Para obter informações sobre como o StorageGRID implementa a API de configuração de notificação de bucket do S3, consulte o link:../s3/index.html["Instruções para a implementação de aplicativos cliente S3"].

Observe os seguintes requisitos e caraterísticas ao configurar notificações de eventos para um bucket:

* Quando você cria e aplica XML de configuração de notificação válida, ele deve usar a URN de um endpoint de notificações de eventos para cada destino.
* Embora a notificação de evento possa ser configurada em um bucket com o bloqueio de objeto S3 ativado, os metadados do bloqueio de objeto S3 (incluindo o status reter até a data e retenção legal) dos objetos não serão incluídos nas mensagens de notificação.
* Após configurar as notificações de eventos, sempre que um evento especificado ocorrer para um objeto no bucket de origem, uma notificação será gerada e enviada ao tópico do Amazon SNS, ao tópico do Kafka ou ao endpoint do webhook usado como destino.
* Se você ativar notificações de eventos para um bucket que contém objetos, as notificações serão enviadas apenas para ações executadas após a configuração de notificação ser salva.


.Passos
. Ativar notificações para o intervalo de origem:
+
** Use um editor de texto para criar a configuração de notificação XML necessário para habilitar notificações de eventos, conforme especificado na API de notificação S3.
** Ao configurar o XML, use a URNA de um endpoint de notificações de eventos como o tópico de destino.
+
[listing]
----
<NotificationConfiguration>
  <TopicConfiguration>
     <Id>Image-created</Id>
     <Filter>
        <S3Key>
          <FilterRule>
            <Name>prefix</Name>
            <Value>images/</Value>
          </FilterRule>
        </S3Key>
    </Filter>
    <Topic>arn:aws:sns:us-east-1:050340950352:sgws-topic</Topic>
    <Event>s3:ObjectCreated:*</Event>
   </TopicConfiguration>
 </NotificationConfiguration>
----


. No Gerenciador do Locatário, selecione *STORAGE (S3)* > *Buckets*.
. Selecione o nome do intervalo de origem.
+
É apresentada a página de detalhes do balde.

. Selecione *Serviços de plataforma* > *notificações de eventos*.
. Marque a caixa de seleção *Ativar notificações de eventos*.
. Cole o XML de configuração de notificação na caixa de texto e selecione *Salvar alterações*.
+

NOTE: Os serviços de plataforma devem estar habilitados para cada conta de locatário por um administrador do StorageGRID usando o Gerenciador de Grade ou a API de Gerenciamento de Grade. Contacte o administrador do StorageGRID se ocorrer um erro ao guardar o XML de configuração.

. Verifique se as notificações de eventos estão configuradas corretamente:
+
.. Execute uma ação em um objeto no bucket de origem que atenda aos requisitos para acionar uma notificação conforme configurado no XML de configuração.
+
No exemplo, uma notificação de evento é enviada sempre que um objeto é criado com o `images/` prefixo.

.. Confirme se uma notificação foi entregue ao tópico de destino do Amazon SNS, tópico do Kafka ou endpoint do webhook.
+
Por exemplo, se o tópico de destino estiver hospedado no Amazon SNS, você poderá configurar o serviço para enviar um e-mail quando a notificação for entregue.

+
[listing]
----
{
   "Records":[
      {
         "eventVersion":"2.0",
         "eventSource":"sgws:s3",
         "eventTime":"2017-08-08T23:52:38Z",
         "eventName":"ObjectCreated:Put",
         "userIdentity":{
            "principalId":"1111111111111111111"
         },
         "requestParameters":{
            "sourceIPAddress":"193.51.100.20"
         },
         "responseElements":{
            "x-amz-request-id":"122047343"
         },
         "s3":{
            "s3SchemaVersion":"1.0",
            "configurationId":"Image-created",
            "bucket":{
               "name":"test1",
               "ownerIdentity":{
                  "principalId":"1111111111111111111"
               },
               "arn":"arn:sgws:s3:::test1"
            },
            "object":{
               "key":"images/cat.jpg",
               "size":0,
               "eTag":"d41d8cd98f00b204e9800998ecf8427e",
               "sequencer":"14D90402421461C7"
            }
         }
      }
   ]
}
----
+
Se a notificação for recebida no tópico de destino, você configurou com êxito o bucket de origem para notificações do StorageGRID.





.Informações relacionadas
* link:understanding-notifications-for-buckets.html["Entenda as notificações para buckets"]
* link:../s3/index.html["USE A API REST DO S3"]
* link:creating-platform-services-endpoint.html["Criar endpoint de serviços de plataforma"]

