---
permalink: tenant/creating-another-users-s3-access-keys.html 
sidebar: sidebar 
keywords: how to create other user S3 access key 
summary: Se você estiver usando um locatário do S3 e tiver a permissão apropriada, poderá criar chaves de acesso do S3 para outros usuários, como aplicativos que precisam de acesso a buckets e objetos. 
---
= Crie as chaves de acesso S3 de outro usuário
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você estiver usando um locatário do S3 e tiver a permissão apropriada, poderá criar chaves de acesso do S3 para outros usuários, como aplicativos que precisam de acesso a buckets e objetos.

.Antes de começar
* Você está conetado ao Gerenciador do Locatário usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
* Você pertence a um grupo de usuários que tem o link:tenant-management-permissions.html["Permissão de acesso à raiz"].


.Sobre esta tarefa
Você pode criar uma ou mais chaves de acesso S3 para outros usuários para que eles possam criar e gerenciar buckets para sua conta de locatário. Depois de criar uma nova chave de acesso, atualize a aplicação com a nova ID da chave de acesso e chave de acesso secreta. Para segurança, não crie mais chaves do que o usuário precisa e exclua as chaves que não estão sendo usadas. Se você tiver apenas uma chave e ela estiver prestes a expirar, crie uma nova chave antes que a antiga expire e, em seguida, exclua a antiga.

Cada chave pode ter um tempo de expiração específico ou nenhuma expiração. Siga estas diretrizes para o tempo de expiração:

* Defina um tempo de expiração para as teclas para limitar o acesso do usuário a um determinado período de tempo. Definir um tempo de expiração curto pode ajudar a reduzir o risco se o ID da chave de acesso e a chave de acesso secreta forem acidentalmente expostos. As chaves expiradas são removidas automaticamente.
* Se o risco de segurança em seu ambiente for baixo e você não precisar criar periodicamente novas chaves, você não precisa definir um tempo de expiração para as chaves. Se você decidir mais tarde criar novas chaves, exclua as chaves antigas manualmente.



CAUTION: Os buckets e objetos do S3 pertencentes a um usuário podem ser acessados usando o ID da chave de acesso e a chave de acesso secreta exibidos para esse usuário no Gerenciador do locatário. Por esse motivo, proteja as chaves de acesso como faria com uma senha. Gire as chaves de acesso regularmente, remova quaisquer chaves não utilizadas da conta e nunca as compartilhe com outros usuários.

.Passos
. Selecione *GERENCIAMENTO DE ACESSO* > *usuários*.
. Selecione o usuário cujas chaves de acesso S3 você deseja gerenciar.
+
É apresentada a página de detalhes do utilizador.

. Selecione *teclas de acesso* e, em seguida, selecione *criar chave*.
. Execute um dos seguintes procedimentos:
+
** Selecione *não defina um tempo de expiração* para criar uma chave que não expire. (Predefinição)
** Selecione *defina um tempo de expiração* e defina a data e a hora de expiração.
+

NOTE: A data de validade pode ser um máximo de cinco anos a partir da data atual. O tempo de expiração pode ser um mínimo de um minuto a partir do tempo atual.



. Selecione *criar chave de acesso*.
+
A caixa de diálogo Download Access Key (Transferir chave de acesso) é exibida, listando o ID da chave de acesso e a chave de acesso secreta.

. Copie o ID da chave de acesso e a chave de acesso secreta para um local seguro ou selecione *Transferir .csv* para guardar um ficheiro de folha de cálculo que contenha a ID da chave de acesso e a chave de acesso secreta.
+

CAUTION: Não feche esta caixa de diálogo até que você tenha copiado ou baixado essas informações. Não é possível copiar ou transferir chaves depois de a caixa de diálogo ter sido fechada.

. Selecione *Finish*.
+
A nova chave está listada na guia teclas de acesso da página de detalhes do usuário.

. Se a sua conta de locatário tiver a permissão *Use Grid Federation Connection*, opcionalmente use a API de Gerenciamento do locatário para clonar manualmente as chaves de acesso S3 do locatário na grade de origem para o locatário na grade de destino. link:grid-federation-clone-keys-with-api.html["Clonar chaves de acesso S3 usando a API"]Consulte .

