---
permalink: tenant/enable-cross-origin-resource-sharing-for-management-interface.html 
sidebar: sidebar 
keywords: how to configure cross-origin resource sharing, cors, management, api, domain 
summary: 'Você pode habilitar o compartilhamento de recursos entre origens (CORS) para solicitações de API de gerenciamento para o StorageGRID, se quiser que os dados no StorageGRID sejam acessíveis usando APIs de gerenciamento para outro domínio.' 
---
= Ative o StorageGRID CORS para uma interface de gerenciamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode habilitar o compartilhamento de recursos entre origens (CORS) para solicitações de API de gerenciamento para o StorageGRID, se quiser que os dados no StorageGRID sejam acessíveis usando APIs de gerenciamento para outro domínio.

.Antes de começar
* Você está conetado ao Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
* O link:tenant-management-permissions.html["Permissão de acesso à raiz"] fornece acesso a todas as solicitações de configuração do CORS.


.Sobre esta tarefa
O CORS é um mecanismo de segurança que permite que aplicativos web clientes em um domínio acessem recursos em um domínio diferente. Por exemplo, suponha que você queira criar um painel de monitoramento para o StorageGRID no domínio `\http://www.example.com`. Ao ativar o CORS no StorageGRID for `\http://www.example.com` e "Gerenciador de Grade", o domínio StorageGRID responde às solicitações de API de Gerenciamento de Grade `\http://www.example.com` do .

As solicitações de API de gerenciamento (mgmt-api) com `application/json` ou `multipart/formdata` solicitações para `Content-Type` são compatíveis com CORS.

.Passos
. Em *rede* na página Configuração do StorageGRID, selecione *Configurações do CORS da interface de gerenciamento*.
. Selecione *Grid Manager*, *Tenant Manager* ou ambas as opções.
+
** *Grid Manager*: Habilita o CORS para solicitações de API de gerenciamento de grade entre domínios.
** *Tenant Manager*: Habilita o CORS para solicitações de API de gerenciamento de locatários entre domínios.


. Insira o URL do outro domínio no campo *domínios*.
+
Selecione *Adicionar outro domínio* se quiser ativar o CORS no StorageGRID para mais de um domínio.

. Selecione *Guardar*.


.Informações relacionadas
link:configuring-cross-origin-resource-sharing-for-buckets-and-objects.html["Configurar StorageGRID CORS para buckets e objetos"]
