---
permalink: tenant/guidelines-for-configuring-openldap-server.html 
sidebar: sidebar 
keywords: how to configure open ldap 
summary: Se você quiser usar um servidor OpenLDAP para federação de identidade, você deve configurar configurações específicas no servidor OpenLDAP. 
---
= Diretrizes para configurar o servidor OpenLDAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você quiser usar um servidor OpenLDAP para federação de identidade, você deve configurar configurações específicas no servidor OpenLDAP.



== Sobreposições de Memberof e refint

As sobreposições membranadas e refinadas devem ser ativadas. Para obter mais informações, consulte as instruções para manutenção de associação reversa em grupo no _OpenLDAP Software Administrator's Guide_.



== Indexação

Você deve configurar os seguintes atributos OpenLDAP com as palavras-chave de índice especificadas:

[listing]
----
olcDbIndex: objectClass eq
olcDbIndex: uid eq,pres,sub
olcDbIndex: cn eq,pres,sub
olcDbIndex: entryUUID eq
----
Além disso, certifique-se de que os campos mencionados na ajuda do Nome de usuário sejam indexados para um desempenho ideal.

Consulte as informações sobre a manutenção da associação de grupo reverso no _OpenLDAP Software Administrator's Guide_.
