---
permalink: tenant/index.html 
sidebar: sidebar 
keywords: use tenant account 
summary: 'Uma conta de locatário permite que você use a API REST do Simple Storage Service (S3) para armazenar e recuperar objetos em um sistema StorageGRID .' 
---
= Use uma conta de locatário
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Uma conta de locatário permite que você use a API REST do Simple Storage Service (S3) para armazenar e recuperar objetos em um sistema StorageGRID.



== O que é uma conta de locatário?

Cada conta de locatário tem seus próprios grupos federados ou locais, usuários, buckets do S3 e objetos.

As contas de inquilino podem ser usadas para segregar objetos armazenados por diferentes entidades. Por exemplo, várias contas de inquilino podem ser usadas para qualquer um desses casos de uso:

* *Caso de uso corporativo:* se o sistema StorageGRID estiver sendo usado dentro de uma empresa, o armazenamento de objetos da grade pode ser segregado pelos diferentes departamentos da organização. Por exemplo, pode haver contas de inquilino para o departamento de marketing, o departamento de suporte ao cliente, o departamento de recursos humanos e assim por diante.
+

NOTE: Se você usar o protocolo de cliente S3, também poderá usar buckets e políticas de bucket do S3 para segregar objetos entre os departamentos de uma empresa.  Você não precisa criar contas de inquilino separadas.  Veja as instruções para implementaçãolink:../s3/use-access-policies.html["Buckets e políticas de buckets do S3"] para mais informações.

* * Caso de uso do provedor de serviços:* se o sistema StorageGRID estiver sendo usado por um provedor de serviços, o armazenamento de objetos da grade pode ser segregado pelas diferentes entidades que alugam o armazenamento. Por exemplo, pode haver contas de inquilino para a empresa A, empresa B, empresa C e assim por diante.




== Como criar uma conta de locatário

As contas de inquilino são criadas por um link:../admin/managing-tenants.html["Administrador de grade do StorageGRID usando o Gerenciador de grade"]. Ao criar uma conta de locatário, o administrador da grade especifica o seguinte:

* Informações básicas, incluindo o nome do locatário, o tipo de cliente (S3) e a cota de armazenamento opcional.
* Permissões para a conta de locatário, como se a conta de locatário pode usar os serviços da plataforma S3, configurar sua própria origem de identidade, usar S3 Select ou usar uma conexão de federação de grade.
* O acesso raiz inicial para o locatário, com base se o sistema StorageGRID usa grupos e usuários locais, federação de identidade ou logon único (SSO).


Além disso, os administradores de grade podem ativar a configuração bloqueio de objeto S3 para o sistema StorageGRID se as contas de locatário S3 precisarem cumprir os requisitos regulamentares. Quando o bloqueio de objeto S3 está ativado, todas as contas de locatário do S3 podem criar e gerenciar buckets compatíveis.



=== Configurar locatários do S3

Depois de um link:../admin/creating-tenant-account.html["S3 conta de locatário é criada"], você pode acessar o Gerenciador do Locatário para executar tarefas como as seguintes:

* Configurar federação de identidade (a menos que a origem de identidade seja compartilhada com a grade)
* Gerenciar grupos e usuários
* Use a federação de grade para clone de conta e replicação entre grade
* Gerenciar S3 chaves de acesso
* Crie e gerencie buckets do S3
* Use os serviços da plataforma S3
* Utilize S3 Select (Selecionar)
* Monitorar o uso do storage



TIP: Embora você possa criar e gerenciar buckets do S3 com o Gerenciador do locatário, use um link:../s3/index.html["Cliente S3"] ou link:use-s3-console.html["S3 Console"] para obter e gerenciar objetos.
