---
permalink: tenant/manage-branch-buckets.html 
sidebar: sidebar 
keywords: how to create branch bucket 
summary: Um bucket de ramificação fornece acesso a objetos em um bucket como eles existiam em um determinado momento, desde que eles ainda existam no bucket. Use o Gerenciador do Locatário para criar e exibir buckets de ramificações. 
---
= Gerenciar buckets de filiais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um bucket de ramificação fornece acesso a objetos em um bucket como eles existiam em um determinado momento, desde que eles ainda existam no bucket. Use o Gerenciador do Locatário para criar e exibir buckets de ramificações.

Um bucket de filial fornece acesso a dados protegidos, mas não serve como backup. Para continuar a proteger os dados, use esses recursos nos buckets básicos:

* link:../tenant/using-s3-object-lock.html["S3 bloqueio de objetos"]
* link:../admin/grid-federation-what-is-cross-grid-replication.html["Replicação entre grade"] para baldes de base
* link:../tenant/manage-bucket-policy.html["Políticas do bucket"] para buckets versionados para limpar versões antigas de objetos


.Sobre esta tarefa
Você cria um bucket de ramificação a partir de um bucket existente. Depois de criar um bucket de ramificação, o bucket original do qual ele foi criado é chamado de bucket base. Além disso, você pode criar um bucket de ramificação a partir de outro bucket de ramificação. Quando você executa operações no bucket da base, os resultados no bucket da ramificação dependem da operação e do tipo de bucket da ramificação que você criou.

Você pode usar um bucket de ramificação para remover objetos corrompidos criando um bucket de ramificação de um ponto no tempo antes da corrupção ocorrer e, em seguida, apontando aplicativos para o bucket de ramificação em vez de para o bucket base que contém objetos corrompidos.


CAUTION: Um bucket de filial não serve como um backup, mas fornece acesso a dados protegidos. Você deve continuar a usar link:../ilm/managing-objects-with-s3-object-lock.html["S3 bloqueio de objetos"] ou link:../admin/grid-federation-what-is-cross-grid-replication.html["replicação entre grade"]proteger os dados.

A replicação entre grade não é suportada para buckets de ramificação.

.Antes de começar
* Iniciou sessão no Gestor do Locatário utilizando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
* Você pertence a um grupo de usuários que tem o acesso raiz ou Gerenciar todos os buckets link:tenant-management-permissions.html["permissão"]. Essas permissões substituem as configurações de permissões em políticas de grupo ou bucket.
* O bucket base do qual você deseja criar um Branch tem link:../tenant/changing-bucket-versioning.html["controle de versão ativado"].
* Você é o proprietário do balde base.
+

NOTE: As permissões para definir ou modificar as propriedades de bloqueio de objetos S3D de buckets ou objetos podem ser concedidas pelo link:../s3/bucket-and-group-access-policies.html["política de bucket ou política de grupo"].





== Crie um bucket de ramificação

.Passos
. Selecione *View buckets* no painel ou selecione *STORAGE (S3)* > *Buckets*.
. Selecione o bucket do qual deseja criar um Branch (o "bucket base").
. Na página de detalhes do bucket, selecione *branches* > *Create Branch bucket*.
+
O botão *Create Branch bucket* será desativado se o bucket base não tiver o controle de versão habilitado.





== Introduza os detalhes

.Passos
. Insira os detalhes do intervalo da filial.
+
[cols="1a,3a"]
|===
| Campo | Descrição 


 a| 
Nome do bucket do ramo
 a| 
Um nome para o bucket do ramo que está em conformidade com estas regras:

** Deve ser exclusivo em cada sistema StorageGRID (não apenas exclusivo na conta do locatário).
** Deve ser compatível com DNS.
** Deve conter pelo menos 3 e não mais de 63 carateres.
** Cada rótulo deve começar e terminar com uma letra minúscula ou um número e só pode usar letras minúsculas, números e hífens.
** Não deve conter períodos em solicitações de estilo hospedadas virtuais. Os períodos causarão problemas com a verificação do certificado curinga do servidor.


Para obter mais informações, consulte https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html["Documentação da Amazon Web Services (AWS) sobre regras de nomenclatura de bucket"^] .

*Nota*: Não é possível alterar o nome depois de criar o intervalo de ramificação.



 a| 
Região (não é possível modificar para buckets de ramificação)
 a| 
A região do balde do ramo.

A região do bucket de ramificação deve corresponder à região do bucket de base, portanto, esse campo está desativado para buckets de ramificação.



 a| 
Antes do tempo
 a| 
O tempo de corte para versões de objetos criadas no bucket da base para serem acessíveis a partir do bucket do ramo. O intervalo de ramificação fornece acesso a versões de objeto criadas antes do tempo.



 a| 
Tipo de balde de ramificação
 a| 
** *Leitura-escrita*: Você pode adicionar ou excluir objetos ou versões de objetos no intervalo de ramificação.
** *Somente leitura*: Não é possível modificar objetos no intervalo de ramificação.


|===
. Selecione *continuar*.




== Gerir definições

As configurações de um bucket de ramificação não afetam as versões do objeto no bucket de base.

.Passos
. Se a configuração global S3 Object Lock estiver ativada, ative opcionalmente o S3 Object Lock para o bucket de ramificação. Para ativar o bloqueio de objetos S3D, o bucket do ramo deve ser um bucket de leitura e gravação.
+
Ative o bloqueio de objetos S3D para um bucket de ramificação somente se você precisar manter objetos por um período fixo de tempo, por exemplo, para atender a certos requisitos regulatórios. S3 Object Lock é uma configuração permanente que ajuda a evitar que objetos sejam excluídos ou substituídos por um período fixo de tempo ou indefinidamente.

+

CAUTION: Depois que a configuração S3 Object Lock estiver ativada para um bucket, ele não poderá ser desativado. Qualquer pessoa com as permissões corretas pode adicionar objetos ao intervalo de ramificação que não podem ser alterados. Você pode não ser capaz de excluir esses objetos ou o próprio bucket do ramo.

. Se você selecionou *Enable Object Lock* (Ativar bloqueio de objetos S3), opcionalmente, ative *Default retension* (retenção padrão) para o intervalo de ramificação.
+

NOTE: O administrador da grade deve dar permissão link:../tenant/using-s3-object-lock.html["Use recursos específicos do S3 Object Lock"]ao .

+
Quando *retenção padrão* estiver ativada, novos objetos adicionados ao bucket do Branch serão automaticamente protegidos contra exclusão ou substituição. A configuração *retenção padrão* não se aplica a objetos que tenham seus próprios períodos de retenção.

+
.. Se *retenção padrão* estiver ativada, especifique um *modo de retenção padrão* para o intervalo de ramificação.
+
[cols="1a,2a"]
|===
| Modo de retenção predefinido | Descrição 


 a| 
Governança
 a| 
*** Os usuários com `s3:BypassGovernanceRetention` permissão podem usar o `x-amz-bypass-governance-retention: true` cabeçalho de solicitação para ignorar as configurações de retenção.
*** Esses usuários podem excluir uma versão de objeto antes de sua data de retenção ser alcançada.
*** Esses usuários podem aumentar, diminuir ou remover a data de retenção até um objeto.




 a| 
Conformidade
 a| 
*** O objeto não pode ser excluído até que sua data de retenção seja alcançada.
*** O retent-until-date do objeto pode ser aumentado, mas não pode ser diminuído.
*** A data de retenção do objeto não pode ser removida até que essa data seja atingida.


*Nota*: O administrador da grade deve permitir que você use o modo de conformidade.

|===
.. Se *retenção padrão* estiver ativada, especifique o *período de retenção padrão* para o intervalo de ramificação.
+
O *período de retenção padrão* indica quanto tempo novos objetos adicionados ao intervalo de ramificação devem ser retidos, a partir do momento em que são ingeridos. Especifique um valor menor ou igual ao período máximo de retenção para o locatário, conforme definido pelo administrador da grade.

+
Um período de retenção _máximo_, que pode ser um valor de 1 dia a 100 anos, é definido quando o administrador da grade cria o locatário. Quando você define um período de retenção _default_, ele não pode exceder o valor definido para o período de retenção máximo. Se necessário, peça ao administrador da grade para aumentar ou diminuir o período máximo de retenção.



. [[Capacity-Limit]]opcionalmente, selecione *Enable Capacity Limit*.
+
O limite de capacidade é a capacidade máxima disponível para o bucket da filial. Este valor representa uma quantidade lógica (tamanho do objeto), não uma quantidade física (tamanho no disco).

+
Se nenhum limite for definido, a capacidade para o bucket do ramo é ilimitada. link:../tenant/understanding-tenant-manager-dashboard.html#bucket-capacity-usage["Uso do limite de capacidade"]Consulte para obter mais informações.

+

NOTE: Essa configuração se aplica somente a objetos diretamente ingeridos no bucket do ramo e não aos objetos que são visíveis do bucket da base através do bucket do ramo.

. Opcionalmente, selecione *Ativar limite de contagem de objetos*.
+
O limite de contagem de objetos é o número máximo de objetos que o intervalo de ramificação pode conter. Este valor representa uma quantidade lógica (contagem de objetos). Se nenhum limite for definido, a contagem de objetos será ilimitada.

+

NOTE: Essa configuração se aplica somente a objetos diretamente ingeridos no bucket do ramo e não aos objetos que são visíveis do bucket da base através do bucket do ramo.

. Selecione *criar bucket*.
+
O bucket do Branch é criado e adicionado à tabela na página Buckets.

. Opcionalmente, selecione *ir para a página de detalhes do bucket* link:viewing-s3-bucket-details.html["veja os detalhes do bucket da filial"]e execute configurações adicionais.
+
Na página Detalhes do balde, algumas opções de configuração relacionadas à modificação de objetos são desativadas para intervalos somente leitura.


