---
permalink: tenant/viewing-another-users-s3-access-keys.html 
sidebar: sidebar 
keywords: how to view other user access key 
summary: Se você estiver usando um locatário do S3 e tiver permissões apropriadas, poderá visualizar as chaves de acesso do S3 de outro usuário. Você pode classificar a lista por tempo de expiração para determinar quais chaves expirarão em breve. Conforme necessário, você pode criar novas chaves e excluir chaves que não estão mais em uso. 
---
= Veja as S3 chaves de acesso de outro usuário
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você estiver usando um locatário do S3 e tiver permissões apropriadas, poderá visualizar as chaves de acesso do S3 de outro usuário. Você pode classificar a lista por tempo de expiração para determinar quais chaves expirarão em breve. Conforme necessário, você pode criar novas chaves e excluir chaves que não estão mais em uso.

.Antes de começar
* Você está conetado ao Gerenciador do Locatário usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
* Você tem o link:tenant-management-permissions.html["Permissão de acesso à raiz"].



CAUTION: Os buckets e objetos do S3 pertencentes a um usuário podem ser acessados usando o ID da chave de acesso e a chave de acesso secreta exibidos para esse usuário no Gerenciador do locatário. Por esse motivo, proteja as chaves de acesso como faria com uma senha. Gire as chaves de acesso regularmente, remova quaisquer chaves não utilizadas da conta e nunca as compartilhe com outros usuários.

.Passos
. Selecione *Gerenciamento de acesso* > *Usuários*.
. Na página usuários, selecione o usuário cujas teclas de acesso S3 você deseja exibir.
. Na página Detalhes do usuário, selecione *teclas de acesso*.
. Classifique as chaves por *tempo de expiração* ou *ID da chave de acesso*.
. Conforme necessário, crie novas chaves e exclua manualmente as chaves que não estiverem mais em uso.
+
Se você criar novas chaves antes que as chaves existentes expirem, o usuário pode começar a usar as novas chaves sem perder temporariamente o acesso aos objetos na conta.

+
As chaves expiradas são removidas automaticamente.



.Informações relacionadas
* link:creating-another-users-s3-access-keys.html["Crie as chaves de acesso S3 de outro usuário"]
* link:deleting-another-users-s3-access-keys.html["Eliminar as S3 chaves de acesso de outro utilizador"]

