---
permalink: rhel/automating-installation.html 
sidebar: sidebar 
keywords: how to automate red hat linux installation 
summary: Você pode automatizar a instalação do serviço de host StorageGRID e a configuração de nós de grade. 
---
= Automatize a instalação do StorageGRID no Red Hat Enterprise Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode automatizar a instalação do serviço de host StorageGRID e a configuração de nós de grade.

Automatizar a implantação pode ser útil em qualquer um dos seguintes casos:

* Você já usa uma estrutura de orquestração padrão, como Ansible, Puppet ou Chef, para implantar e configurar hosts físicos ou virtuais.
* Você pretende implantar várias instâncias do StorageGRID.
* Você está implantando uma instância grande e complexa do StorageGRID.


O serviço de host StorageGRID é instalado por um pacote e conduzido por arquivos de configuração. Você pode criar os arquivos de configuração usando um destes métodos:

* link:creating-node-configuration-files.html["Crie os arquivos de configuração"] interativamente durante uma instalação manual.
* Prepare os arquivos de configuração com antecedência (ou programaticamente) para habilitar a instalação automatizada usando estruturas de orquestração padrão, como descrito neste artigo.
+
O StorageGRID fornece scripts Python opcionais para automatizar a configuração de dispositivos StorageGRID e todo o sistema StorageGRID (a "grade"). Você pode usar esses scripts diretamente ou inspecioná-los para aprender a usar as link:overview-of-installation-rest-api.html["API REST de instalação do StorageGRID"]ferramentas de implantação e configuração da grade que você mesmo desenvolve.





== Automatize a instalação e a configuração do serviço de host StorageGRID

É possível automatizar a instalação do serviço de host StorageGRID usando estruturas de orquestração padrão, como Ansible, Puppet, Chef, Fabric ou SaltStack.

O serviço de host do StorageGRID é empacotado em RPM e é conduzido por arquivos de configuração que podem ser preparados com antecedência (ou programaticamente) para habilitar a instalação automatizada. Se você já usa uma estrutura de orquestração padrão para instalar e configurar o RHEL, adicionar StorageGRID aos seus playbooks ou receitas deve ser simples.

Veja o exemplo de função e manual do Ansible `/extras` na pasta fornecida com o arquivo de instalação. O manual de estratégia do Ansible mostra como a `storagegrid` função prepara o host e instala o StorageGRID nos servidores de destino. Você pode personalizar a função ou o manual de estratégia conforme necessário.


NOTE: O manual de estratégia de exemplo não inclui as etapas necessárias para criar dispositivos de rede antes de iniciar o serviço de host StorageGRID. Adicione estas etapas antes de finalizar e usar o manual de estratégia.

Você pode automatizar todas as etapas para preparar os hosts e implantar nós de grade virtual.



=== Exemplo de função e manual de estratégia do Ansible

Exemplo de função do Ansible e manual de estratégia são fornecidos com o arquivo de instalação `/extras` na pasta. O manual de estratégia do Ansible mostra como a `storagegrid` função prepara os hosts e instala o StorageGRID nos servidores de destino. Você pode personalizar a função ou o manual de estratégia conforme necessário.

As tarefas de instalação no exemplo de função fornecido `storagegrid` usam o `ansible.builtin.dnf` módulo para executar a instalação a partir dos arquivos RPM locais ou de um repositório Yum remoto. Se o módulo não estiver disponível ou não for compatível, talvez seja necessário editar as tarefas apropriadas do Ansible nos arquivos a seguir para usar o `yum` módulo ou `ansible.builtin.yum`:

* `roles/storagegrid/tasks/rhel_install_from_repo.yml`
* `roles/storagegrid/tasks/rhel_install_from_local.yml`




== Automatize a configuração do StorageGRID

Depois de implantar os nós de grade, você pode automatizar a configuração do sistema StorageGRID.

.Antes de começar
* Você sabe a localização dos seguintes arquivos do arquivo de instalação.
+
[cols="1a,1a"]
|===
| Nome do ficheiro | Descrição 


| configure-StorageGRID.py  a| 
Script Python usado para automatizar a configuração



| configure-StorageGRID.sample.json  a| 
Exemplo de arquivo de configuração para uso com o script



| configure-StorageGRID.blank.json  a| 
Arquivo de configuração em branco para uso com o script

|===
* Criou um `configure-storagegrid.json` ficheiro de configuração. Para criar este ficheiro, pode modificar o ficheiro de configuração de exemplo (`configure-storagegrid.sample.json`) ou o ficheiro de configuração em branco (`configure-storagegrid.blank.json`).



CAUTION: Armazene a senha de gerenciamento e a senha de provisionamento da seção senhas do arquivo de configuração modificado `configure-storagegrid.json` em um local seguro. Essas senhas são necessárias para procedimentos de instalação, expansão e manutenção. Você também deve fazer backup do arquivo de configuração modificado `configure-storagegrid.json` e armazená-lo em um local seguro.

.Sobre esta tarefa
Você pode usar o `configure-storagegrid.py` script Python e o `configure-storagegrid.json` arquivo de configuração para automatizar a configuração do seu sistema StorageGRID.


NOTE: Você também pode configurar o sistema usando o Gerenciador de Grade ou a API de Instalação.

.Passos
. Faça login na máquina Linux que você está usando para executar o script Python.
. Mude para o diretório onde você extraiu o arquivo de instalação.
+
Por exemplo:

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
 `platform`onde está `debs`, `rpms`, `vsphere` ou .

. Execute o script Python e use o arquivo de configuração que você criou.
+
Por exemplo:

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.Resultado
Um arquivo de pacote de recuperação `.zip` é gerado durante o processo de configuração e é baixado para o diretório onde você está executando o processo de instalação e configuração. É necessário fazer backup do arquivo do pacote de recuperação para que você possa recuperar o sistema StorageGRID se um ou mais nós de grade falhar. Por exemplo, copie-o para um local de rede seguro e de backup e para um local seguro de armazenamento em nuvem.


CAUTION: O arquivo do pacote de recuperação deve ser protegido porque contém chaves de criptografia e senhas que podem ser usadas para obter dados do sistema StorageGRID.

Se você especificou que senhas aleatórias serão geradas, abra o `Passwords.txt` arquivo e procure as senhas necessárias para acessar seu sistema StorageGRID.

[listing]
----
######################################################################
##### The StorageGRID "Recovery Package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
O sistema StorageGRID é instalado e configurado quando é apresentada uma mensagem de confirmação.

[listing]
----
StorageGRID has been configured and installed.
----
.Informações relacionadas
link:overview-of-installation-rest-api.html["API REST de instalação"]
