---
permalink: rhel/configuring-docker-storage-volume.html 
sidebar: sidebar 
keywords: how to configure container engine storage volume, Docker, Podman 
summary: 'Antes de instalar o mecanismo de contentor (Docker ou Podman), talvez seja necessário formatar o volume de armazenamento e montá-lo.' 
---
= Configure o volume de armazenamento do motor do recipiente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar o mecanismo de contentor (Docker ou Podman), talvez seja necessário formatar o volume de armazenamento e montá-lo.


NOTE: O suporte para Docker como o mecanismo de contentor para implantações somente de software está obsoleto. O Docker será substituído por outro mecanismo de contentor em uma versão futura.

.Sobre esta tarefa
Você pode ignorar essas etapas se você planeja usar o armazenamento local para o volume de armazenamento Docker ou Podman e tem espaço suficiente disponível na partição do host que contém `/var/lib/docker` para Docker e `/var/lib/containers` Podman.


NOTE: O Podman é suportado apenas no Red Hat Enterprise Linux (RHEL).

.Passos
. Crie um sistema de arquivos no volume de armazenamento do mecanismo de contentor:
+
[listing]
----
sudo mkfs.ext4 container-engine-storage-volume-device
----
. Monte o volume de armazenamento do motor do recipiente:
+
** Para Docker:
+
[listing]
----
sudo mkdir -p /var/lib/docker
sudo mount container-storage-volume-device /var/lib/docker
----
** Para Podman:
+
[listing]
----
sudo mkdir -p /var/lib/containers
sudo mount container-storage-volume-device /var/lib/containers
----


. Adicione uma entrada para container-storage-volume-volume-device ao /etc/fstab.
+
Essa etapa garante que o volume de storage seja remontado automaticamente após a reinicialização do host.





== Instale o Docker

O sistema StorageGRID é executado no Red Hat Enterprise Linux como uma coleção de contentores. Se você optou por usar o mecanismo de contentor Docker, siga estas etapas para instalar o Docker. Caso contrário<<Instale o Podman,Instale o Podman>>, .

.Passos
. Instale o Docker seguindo as instruções para sua distribuição Linux.
+

NOTE: Se o Docker não estiver incluído na sua distribuição Linux, você poderá baixá-lo a partir do site do Docker.

. Certifique-se de que o Docker foi ativado e iniciado executando os dois comandos a seguir:
+
[listing]
----
sudo systemctl enable docker
----
+
[listing]
----
sudo systemctl start docker
----
. Confirme que instalou a versão esperada do Docker inserindo o seguinte:
+
[listing]
----
sudo docker version
----
+
As versões Cliente e servidor devem ser 1.11.0 ou posterior.





== Instale o Podman

O sistema StorageGRID é executado no Red Hat Enterprise Linux como uma coleção de contentores. Se você escolheu usar o motor de contentor Podman, siga estas etapas para instalar o Podman. Caso contrário<<Instale o Docker,Instale o Docker>>, .


NOTE: O Podman é suportado apenas no Red Hat Enterprise Linux (RHEL).

.Passos
. Instale o Podman e o Podman-Docker seguindo as instruções para sua distribuição Linux.
+

NOTE: Você também deve instalar o pacote Podman-Docker quando instalar o Podman.

. Confirme que instalou a versão esperada do Podman e do Podman-Docker inserindo o seguinte:
+
[listing]
----
sudo docker version
----
+

NOTE: O pacote Podman-Docker permite que você use comandos Docker.

+
As versões Cliente e servidor devem ser 3.2.3 ou posterior.

+
[listing]
----
Version: 3.2.3
API Version: 3.2.3
Go Version: go1.15.7
Built: Tue Jul 27 03:29:39 2021
OS/Arch: linux/amd64
----

