---
permalink: rhel/installing-linux.html 
sidebar: sidebar 
keywords: how to install on red hat linux 
summary: Você deve instalar o StorageGRID em todos os hosts de grade do Red Hat Enterprise Linux. Para obter uma lista de versões suportadas, utilize a ferramenta de Matriz de interoperabilidade do NetApp. 
---
= Instale o Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve instalar o StorageGRID em todos os hosts de grade do Red Hat Enterprise Linux. Para obter uma lista de versões suportadas, utilize a ferramenta de Matriz de interoperabilidade do NetApp.

.Antes de começar
Certifique-se de que seu sistema operacional atenda aos requisitos mínimos de versão do kernel do StorageGRID, conforme listado abaixo. Use o comando `uname -r` para obter a versão do kernel do seu sistema operacional ou consulte o fornecedor do seu sistema operacional.

[cols="1a,2a,2a"]
|===
| Versão Red Hat Enterprise Linux | Versão mínima do kernel | Nome do pacote do kernel 


 a| 
8,8 (obsoleto)
 a| 
4.18.0-477.10.1.el8_8.x86_64
 a| 
kernel-4.18.0-477.10.1.el8_8.x86_64



 a| 
8,10
 a| 
4.18.0-553.el8_10.x86_64
 a| 
kernel-4.18.0-553.el8_10.x86_64



 a| 
9,0 (obsoleto)
 a| 
5.14.0-70.22.1.el9_0.x86_64
 a| 
kernel-5.14.0-70.22.1.el9_0.x86_64



 a| 
9,2 (obsoleto)
 a| 
5.14.0-284.11.1.el9_2.x86_64
 a| 
kernel-5.14.0-284.11.1.el9_2.x86_64



 a| 
9,4
 a| 
5.14.0-427.18.1.el9_4.x86_64
 a| 
kernel-5.14.0-427.18.1.el9_4.x86_64

|===
.Passos
. Instale o Linux em todos os hosts de grade física ou virtual de acordo com as instruções do distribuidor ou seu procedimento padrão.
+

NOTE: Se você estiver usando o instalador padrão do Linux, selecione a configuração do software "nó de computação", se disponível, ou o ambiente base "instalação mínima". Não instale nenhum ambiente de desktop gráfico.

. Certifique-se de que todos os hosts tenham acesso aos repositórios de pacotes, incluindo o canal Extras.
+
Você pode precisar desses pacotes adicionais mais tarde neste procedimento de instalação.

. Se a troca estiver ativada:
+
.. Execute o seguinte comando: `$ sudo swapoff --all`
.. Remova todas as entradas de troca de `/etc/fstab` para persistir as configurações.


+

NOTE: A falha ao desativar completamente a troca pode reduzir drasticamente o desempenho.


