---
permalink: admin/change-ssh-access-passwords.html 
sidebar: sidebar 
keywords: ssh access keys, change ssh access keys 
summary: Alterar as senhas de acesso SSH para nós de administrador também atualiza os conjuntos exclusivos de chaves SSH internas para cada nó na grade. O nó Admin principal usa essas chaves SSH para acessar nós usando autenticação segura e sem senha. 
---
= Alterar senhas de acesso SSH para nós de administrador
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Alterar as senhas de acesso SSH para nós de administrador também atualiza os conjuntos exclusivos de chaves SSH internas para cada nó na grade. O nó Admin principal usa essas chaves SSH para acessar nós usando autenticação segura e sem senha.

Use uma chave SSH para fazer login em um nó como `admin` ou para o usuário raiz em uma VM ou conexão de console físico.

.Antes de começar
* Você está conetado ao Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
* Você tem o link:admin-group-permissions.html["Permissão de manutenção ou acesso root"].
* Você tem a senha de provisionamento atual.


.Sobre esta tarefa
As novas senhas de acesso para nós de administração e as novas chaves internas para cada nó são armazenadas `Passwords.txt` no arquivo no Pacote de recuperação. As chaves são listadas na coluna Senha nesse arquivo.

Existem senhas de acesso SSH separadas para as chaves SSH usadas para comunicação entre nós. Estes não são alterados por este procedimento.



== Acesse o assistente

.Passos
. Selecione *CONFIGURATION* > *Access control* > *Grid passwords*.
. Em *alterar chaves SSH*, selecione *fazer uma alteração*.




== [[download-current]]Baixe o pacote de recuperação atual

Antes de alterar as chaves de acesso SSH, faça o download do Pacote de recuperação atual. Você pode usar as chaves neste arquivo se o processo de mudança de chave falhar para qualquer nó.

.Passos
. Introduza a frase-passe de aprovisionamento da grelha.
. Selecione *Baixar pacote de recuperação*.
. Copie o arquivo do pacote de recuperação (`.zip`) para dois locais seguros, seguros e separados.
+

CAUTION: O arquivo do pacote de recuperação deve ser protegido porque contém chaves de criptografia e senhas que podem ser usadas para obter dados do sistema StorageGRID.

. Selecione *continuar*.
. Quando a caixa de diálogo de confirmação for exibida, selecione *Sim* se estiver pronto para começar a alterar as chaves de acesso SSH.
+

CAUTION: Não é possível cancelar este processo após o início.





== Alterar chaves de acesso SSH

Quando o processo alterar chaves de acesso SSH é iniciado, um novo Pacote de recuperação é gerado que inclui as novas chaves. Em seguida, as chaves são atualizadas em cada nó.

.Passos
. Aguarde que o novo pacote de recuperação seja gerado, o que pode levar alguns minutos.
. Quando o botão Transferir novo pacote de recuperação estiver ativado, selecione *Transferir novo pacote de recuperação* e guarde o novo ficheiro do pacote de recuperação (`.zip`) em dois locais seguros, seguros e separados.
. Quando o download for concluído:
+
.. Abra o `.zip` ficheiro.
.. Confirme que você pode acessar o conteúdo, incluindo o `Passwords.txt` arquivo, que contém as novas chaves de acesso SSH.
.. Copie o novo arquivo do pacote de recuperação (`.zip`) para dois locais seguros, seguros e separados.
+

CAUTION: Não substitua o pacote de recuperação antigo.

+
O arquivo do pacote de recuperação deve ser protegido porque contém chaves de criptografia e senhas que podem ser usadas para obter dados do sistema StorageGRID.



. Aguarde que as chaves sejam atualizadas em cada nó, o que pode levar alguns minutos.
+
Se as chaves forem alteradas para todos os nós, um banner verde de sucesso será exibido.

+
Se houver um erro durante o processo de atualização, uma mensagem de banner lista o número de nós que não conseguiram alterar suas chaves. O sistema tentará automaticamente o processo em qualquer nó que não tenha sua chave alterada. Se o processo terminar com alguns nós ainda não tendo uma chave alterada, o botão *Repetir* será exibido.

+
Se a atualização da chave falhar para um ou mais nós:

+
.. Reveja as mensagens de erro listadas na tabela.
.. Resolva os problemas.
.. Selecione *Repetir*.
+
Tentar novamente altera apenas as chaves de acesso SSH nos nós que falharam durante tentativas anteriores de alteração de chave.



. Depois que as chaves de acesso SSH tiverem sido alteradas para todos os nós, exclua o <<download-current,Primeiro pacote de recuperação que você baixou>>.
. Opcionalmente, selecione *MAINTENANCE* > *System* > *Recovery package* para transferir uma cópia adicional do novo Recovery Package.

