---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: Cada nó na sua grade tem uma senha de console do nó, que você usa para efetuar login no nó.  Por padrão, cada nó tem uma senha exclusiva.  Você pode alterar cada senha para uma nova senha exclusiva ou pode alterar a senha de cada nó para usar uma senha global.  As senhas são armazenadas no pacote de recuperação. 
---
= Altere as senhas do console do nó
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada nó na sua grade tem uma senha de console do nó, que você usa para efetuar login no nó.  Por padrão, cada nó tem uma senha exclusiva.  Você pode alterar cada senha para uma nova senha exclusiva ou pode alterar a senha de cada nó para usar uma senha global.  As senhas são armazenadas no pacote de recuperação.

.Antes de começar
* Você está conetado ao Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
* Você tem o link:admin-group-permissions.html["Permissão de manutenção ou acesso root"].
* Você tem a senha de provisionamento atual.


.Sobre esta tarefa
Use uma senha de console de nó para efetuar login em um nó como "admin" usando SSH ou como usuário root em uma conexão de console físico/VM.  Você pode alterar as senhas do console do nó usando uma destas opções:

* Aplicar automaticamente senhas aleatórias a cada nó
* Especifique e aplique uma senha global a todos os nós
* Especifique e aplique uma senha exclusiva a um ou mais nós


As senhas são armazenadas em um arquivo atualizado `Passwords.txt` arquivo no pacote de recuperação.  As senhas são listadas na coluna Senha no arquivo.


NOTE: Olink:../admin/change-ssh-access-passwords.html["Senhas de acesso SSH"] para as chaves SSH usadas para comunicação entre nós são separadas das senhas do console do nó.  Este procedimento não altera as senhas de acesso SSH.



== Acesse o assistente

.Passos
. Selecione *Configuração* > *Controle de acesso* > *Senhas de grade*.
. Em *alterar senhas de console de nó*, selecione *fazer uma alteração*.




== [[download-current]]Baixe o pacote de recuperação atual

Antes de alterar as senhas do console do nó, baixe o pacote de recuperação atual.  Você pode usar as senhas neste arquivo se o processo de alteração de senha falhar para qualquer nó.

.Passos
. Introduza a frase-passe de aprovisionamento da grelha.
. Selecione *Baixar pacote de recuperação*.
. Copie o arquivo do pacote de recuperação(`.zip` ) para dois locais seguros, protegidos e separados.
+

CAUTION: O arquivo do pacote de recuperação deve ser protegido porque contém chaves de criptografia e senhas que podem ser usadas para obter dados do sistema StorageGRID .

. Selecione *continuar*.




== Forneça novas senhas

. Selecione o método de alteração de senha que você deseja usar.
+
** *Automático*: O StorageGRID atribui automaticamente uma nova senha de console aleatória a todos os nós.
** *Personalizado*: Você fornece senhas de console.




[role="tabbed-block"]
====
.Automático
--
. Selecione *continuar*.


--
.Personalizado
--
. Selecione uma das seguintes opções:
+
** *Senha global do console*: Aplique a mesma senha do console a todos os nós.
** *Senhas de console exclusivas*: Aplique uma senha diferente em um ou mais nós.


. Se você selecionou *Senha do console global*, insira a senha que deseja usar para todos os nós.
. Se você selecionou *Senhas exclusivas do console*, insira uma senha exclusiva para um ou mais nós.
. Selecione *continuar*.


--
====


== Conclua a alteração da senha

. Quando a caixa de diálogo de confirmação aparecer, selecione *Sim* se estiver pronto para que o StorageGRID comece a alterar as senhas do console do nó.
+

NOTE: Não é possível cancelar este processo após o início.

+
O StorageGRID gera um novo pacote de recuperação contendo a nova senha.

. Quando o novo pacote de recuperação estiver pronto, selecione *Baixar novo pacote de recuperação* e salve o pacote de recuperação.
. Abra o `.zip` ficheiro.
. Confirme se você pode acessar o conteúdo, incluindo o `Passwords.txt` arquivo, que contém as novas senhas do console do nó.
. Copie o novo arquivo do pacote de recuperação(`.zip` ) para dois locais seguros, protegidos e separados.
+

CAUTION: Não substitua o pacote de recuperação antigo.

+
Você deve proteger o arquivo de recuperação, porque ele contém chaves de criptografia e senhas que podem ser usadas para obter dados do sistema StorageGRID .

. Marque a caixa de seleção para indicar que você baixou o novo pacote de recuperação e verificou o conteúdo.
. Selecione *continuar*.
+
O StorageGRID atualiza a senha para cada nó.

+
Se houver um erro durante o processo de atualização, a barra de progresso listará o número de nós que não tiveram suas senhas alteradas.  O sistema repetirá automaticamente o processo em qualquer nó cuja senha não tenha sido alterada.  Se o processo terminar com alguns nós ainda sem uma senha alterada, o botão *Repetir* será exibido.

. Se a atualização da palavra-passe tiver falhado para um ou mais nós:
+
.. Reveja as mensagens de erro listadas na tabela.
.. Resolva os problemas.
.. Selecione *Repetir*.
+

NOTE: A tentativa de novo altera apenas as senhas do console do nó nos nós que falharam durante tentativas anteriores de alteração de senha.



. Quando a barra de progresso indicar que não há atualizações restantes, selecione *Concluir*.
. Depois que as senhas do console do nó forem alteradas para todos os nós, exclua o<<download-current,primeiro pacote de recuperação que você baixou>> .

