---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: Cada nó da grade tem uma senha de console de nó, que você usa para fazer login no nó. Por padrão, cada nó tem uma senha exclusiva. Pode alterar cada palavra-passe para uma nova palavra-passe exclusiva ou pode alterar a palavra-passe de cada nó para utilizar uma palavra-passe global. As senhas são armazenadas no pacote de recuperação. 
---
= Altere as senhas do console do nó
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada nó da grade tem uma senha de console de nó, que você usa para fazer login no nó. Por padrão, cada nó tem uma senha exclusiva. Pode alterar cada palavra-passe para uma nova palavra-passe exclusiva ou pode alterar a palavra-passe de cada nó para utilizar uma palavra-passe global. As senhas são armazenadas no pacote de recuperação.

.Antes de começar
* Você está conetado ao Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
* Você tem o link:admin-group-permissions.html["Permissão de manutenção ou acesso root"].
* Você tem a senha de provisionamento atual.


.Sobre esta tarefa
Você usa uma senha do console de nó para fazer login em um nó como "admin" usando SSH, ou para o usuário raiz em uma conexão VM/console físico. Você pode alterar as senhas do console do nó usando uma destas opções:

* Aplique automaticamente senhas aleatórias a cada nó
* Especifique e aplique uma senha global a todos os nós
* Especifique e aplique uma senha exclusiva a um ou mais nós


As senhas são armazenadas em um arquivo atualizado `Passwords.txt` no pacote de recuperação. As senhas são listadas na coluna Senha no arquivo.


NOTE: As link:../admin/change-ssh-access-passwords.html["Senhas de acesso SSH"]chaves SSH usadas para comunicação entre nós são separadas das senhas do console do nó. Este procedimento não altera as senhas de acesso SSH.



== Acesse o assistente

.Passos
. Selecione *CONFIGURATION* > *Access control* > *Grid passwords*.
. Em *alterar senhas de console de nó*, selecione *fazer uma alteração*.




== [[download-current]]Baixe o pacote de recuperação atual

Antes de alterar as senhas do console do nó, baixe o pacote de recuperação atual. Você pode usar as senhas neste arquivo se o processo de alteração de senha falhar em qualquer nó.

.Passos
. Introduza a frase-passe de aprovisionamento da grelha.
. Selecione *Baixar pacote de recuperação*.
. Copie o arquivo do pacote de recuperação (`.zip`) para dois locais seguros, seguros e separados.
+

CAUTION: O arquivo do pacote de recuperação deve ser protegido porque contém chaves de criptografia e senhas que podem ser usadas para obter dados do sistema StorageGRID.

. Selecione *continuar*.




== Forneça novas senhas

. Selecione o método de alteração de palavra-passe que pretende utilizar.
+
** *Automático*: O StorageGRID atribui automaticamente uma nova senha de console aleatório a todos os nós.
** *Custom*: Você fornece senhas de console.




[role="tabbed-block"]
====
.Automático
--
. Selecione *continuar*.


--
.Personalizado
--
. Selecione uma das seguintes opções:
+
** *Senha do console global*: Aplique a mesma senha do console a todos os nós.
** *Senhas exclusivas do console*: Aplique uma senha diferente em um ou mais nós.


. Se você selecionou *Senha do console global*, digite a senha que deseja usar para todos os nós.
. Se você selecionou *senhas exclusivas do console*, insira uma senha exclusiva para um ou mais nós.
. Selecione *continuar*.


--
====


== Conclua a alteração da palavra-passe

. Quando a caixa de diálogo de confirmação for exibida, selecione *Sim* se estiver pronto para o StorageGRID começar a alterar as senhas do console do nó.
+

NOTE: Não é possível cancelar este processo após o início.

+
O StorageGRID gera um novo pacote de recuperação contendo a nova senha.

. Quando o novo pacote de recuperação estiver pronto, selecione *Download de novo pacote de recuperação* e salve o pacote de recuperação.
. Abra o `.zip` ficheiro.
. Confirme se você pode acessar o conteúdo, incluindo o `Passwords.txt` arquivo, que contém as novas senhas do console do nó.
. Copie o novo arquivo do pacote de recuperação (`.zip`) para dois locais seguros, seguros e separados.
+

CAUTION: Não substitua o pacote de recuperação antigo.

+
Você deve proteger o arquivo de recuperação, porque ele contém chaves de criptografia e senhas que podem ser usadas para obter dados do sistema StorageGRID.

. Marque a caixa de seleção para indicar que você baixou o novo pacote de recuperação e verificou o conteúdo.
. Selecione *continuar*.
+
O StorageGRID atualiza a senha para cada nó.

+
Se houver um erro durante o processo de atualização, a barra de progresso lista o número de nós que não conseguiram alterar suas senhas. O sistema irá tentar novamente automaticamente o processo em qualquer nó que não tenha a sua palavra-passe alterada. Se o processo terminar com alguns nós ainda não tendo uma senha alterada, o botão *Repetir* será exibido.

. Se a atualização da palavra-passe tiver falhado para um ou mais nós:
+
.. Reveja as mensagens de erro listadas na tabela.
.. Resolva os problemas.
.. Selecione *Repetir*.
+

NOTE: A tentativa de novo altera apenas as senhas do console do nó nos nós que falharam durante tentativas anteriores de alteração de senha.



. Quando a barra de progresso indicar que não há atualizações restantes, selecione *Finish*.
. Depois que as senhas do console do nó tiverem sido alteradas para todos os nós, exclua o <<download-current,primeiro pacote de recuperação que você baixou>>.

