---
permalink: admin/changing-your-password.html 
sidebar: sidebar 
keywords: change password, grid manager password 
summary: Se você é um usuário local do Gerenciador de Grade, você pode alterar sua própria senha. 
---
= Altere a sua palavra-passe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você é um usuário local do Gerenciador de Grade, você pode alterar sua própria senha.

.Antes de começar
Você está conetado ao Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].

.Sobre esta tarefa
Se você entrar no StorageGRID como um usuário federado ou se o logon único (SSO) estiver ativado, não será possível alterar sua senha no Gerenciador de Grade. Em vez disso, você deve alterar sua senha na fonte de identidade externa, por exemplo, ative Directory ou OpenLDAP.

.Passos
. No cabeçalho do Gerenciador de Grade, selecione *_your name_* > *Change password*.
. Introduza a sua palavra-passe atual.
. Introduza uma nova palavra-passe.
+
Sua senha deve conter pelo menos 8 e não mais de 32 carateres. As senhas diferenciam maiúsculas de minúsculas.

. Volte a introduzir a nova palavra-passe.
. Selecione *Guardar*.

