---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: Cada nó na sua grade tem uma senha exclusiva do console de nó, que você precisa fazer login no nó. Siga estas etapas para alterar a senha do console do nó para cada nó na grade. As senhas são armazenadas no Pacote de recuperação. 
---
= Altere as senhas do console do nó
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada nó na sua grade tem uma senha exclusiva do console de nó, que você precisa fazer login no nó. Use estas etapas para alterar cada senha exclusiva do console de nó para cada nó na grade.

.Antes de começar
* Você está conetado ao Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
* Você tem o link:admin-group-permissions.html["Permissão de manutenção ou acesso root"].
* Você tem a senha de provisionamento atual.


.Sobre esta tarefa
Use a senha do console do nó para fazer login em um nó como "admin" usando SSH, ou para o usuário raiz em uma conexão VM/console físico. O processo de alteração de senha do console do nó cria novas senhas para cada nó na grade e armazena as senhas em um arquivo atualizado `Passwords.txt` no Pacote de recuperação. As senhas são listadas na coluna Senha no arquivo Passwords.txt.


NOTE: Existem senhas de acesso SSH separadas para as chaves SSH usadas para comunicação entre nós. As senhas de acesso SSH não são alteradas por este procedimento.



== Acesse o assistente

.Passos
. Selecione *CONFIGURATION* > *Access control* > *Grid passwords*.
. Em *alterar senhas de console de nó*, selecione *fazer uma alteração*.




== Introduza a frase-passe de aprovisionamento

.Passos
. Introduza a frase-passe de aprovisionamento da grelha.
. Selecione *continuar*.




== [[download-current]]Baixe o pacote de recuperação atual

Antes de alterar as senhas do console do nó, baixe o Pacote de recuperação atual. Você pode usar as senhas neste arquivo se o processo de alteração de senha falhar em qualquer nó.

.Passos
. Selecione *Baixar pacote de recuperação*.
. Copie o arquivo do pacote de recuperação (`.zip`) para dois locais seguros, seguros e separados.
+

CAUTION: O arquivo do pacote de recuperação deve ser protegido porque contém chaves de criptografia e senhas que podem ser usadas para obter dados do sistema StorageGRID.

. Selecione *continuar*.
. Quando a caixa de diálogo de confirmação for exibida, selecione *Sim* se estiver pronto para começar a alterar as senhas do console do nó.
+
Não é possível cancelar este processo após o início.





== Altere as senhas do console do nó

Quando o processo de senha do console do nó é iniciado, um novo Pacote de recuperação é gerado que inclui as novas senhas. Em seguida, as senhas são atualizadas em cada nó.

.Passos
. Aguarde que o novo pacote de recuperação seja gerado, o que pode levar alguns minutos.
. Selecione *Transferir novo pacote de recuperação*.
. Quando o download for concluído:
+
.. Abra o `.zip` ficheiro.
.. Confirme se você pode acessar o conteúdo, incluindo o `Passwords.txt` arquivo, que contém as novas senhas do console do nó.
.. Copie o novo arquivo do pacote de recuperação (`.zip`) para dois locais seguros, seguros e separados.
+

CAUTION: Não substitua o pacote de recuperação antigo.

+
O arquivo do pacote de recuperação deve ser protegido porque contém chaves de criptografia e senhas que podem ser usadas para obter dados do sistema StorageGRID.



. Marque a caixa de seleção para indicar que você baixou o novo Pacote de recuperação e verificou o conteúdo.
. Selecione *alterar senhas do console de nós* e aguarde que todos os nós sejam atualizados com as novas senhas. Isso pode levar alguns minutos.
+
Se as senhas forem alteradas para todos os nós, um banner verde de sucesso será exibido. Vá para a próxima etapa.

+
Se houver um erro durante o processo de atualização, uma mensagem de banner lista o número de nós que não conseguiram alterar suas senhas. O sistema irá tentar novamente automaticamente o processo em qualquer nó que não tenha a sua palavra-passe alterada. Se o processo terminar com alguns nós ainda não tendo uma senha alterada, o botão *Repetir* será exibido.

+
Se a atualização da palavra-passe tiver falhado para um ou mais nós:

+
.. Reveja as mensagens de erro listadas na tabela.
.. Resolva os problemas.
.. Selecione *Repetir*.
+

NOTE: A tentativa de novo altera apenas as senhas do console do nó nos nós que falharam durante tentativas anteriores de alteração de senha.



. Depois que as senhas do console do nó tiverem sido alteradas para todos os nós, exclua o <<download-current,Primeiro pacote de recuperação que você baixou>>.
. Opcionalmente, use o link *Recovery package* para baixar uma cópia adicional do novo Recovery Package.

