---
permalink: admin/configure-sso.html 
sidebar: sidebar 
keywords: use sandbox mode for sso, how to test single sign-on 
summary: Você pode seguir o assistente Configurar SSO e entrar no modo sandbox para configurar e testar o logon único antes de habilitá-lo para todos os usuários do StorageGRID. Depois que o SSO estiver ativado, você poderá retornar ao modo sandbox quando necessário para alterar ou testar novamente a configuração. 
---
= Configurar SSO
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode seguir o assistente Configurar SSO e entrar no modo sandbox para configurar e testar o logon único (SSO) antes de habilitá-lo para todos os usuários do StorageGRID. Depois que o SSO for ativado, você poderá retornar ao modo sandbox quando necessário para alterar ou testar novamente a configuração.

.Antes de começar
* Você está conetado ao Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
* Você tem o link:admin-group-permissions.html["Permissão de acesso à raiz"].
* Você configurou a federação de identidade para o seu sistema StorageGRID.
* Para a federação de identidade *tipo de serviço LDAP*, você selecionou o ative Directory ou o Entra ID, com base no provedor de identidade SSO que você planeja usar.
+
[cols="1a,1a"]
|===
| Tipo de serviço LDAP configurado | Opções para provedor de identidade SSO 


 a| 
Serviço de Federação do ative Directory (AD FS)
 a| 
** Ative Directory
** ID entra
** PingFederate




 a| 
ID entra
 a| 
ID entra

|===


.Sobre esta tarefa
Quando o SSO está ativado e um usuário tenta entrar em um nó de administrador, o StorageGRID envia uma solicitação de autenticação para o provedor de identidade SSO. Por sua vez, o provedor de identidade SSO envia uma resposta de autenticação de volta ao StorageGRID, indicando se a solicitação de autenticação foi bem-sucedida. Para solicitações bem-sucedidas:

* A resposta do ative Directory ou PingFederate inclui um identificador universal único (UUID) para o usuário.
* A resposta do Entra ID inclui um Nome Principal de Usuário (UPN).


Para permitir que o StorageGRID (o provedor de serviços) e o provedor de identidade SSO se comuniquem com segurança sobre as solicitações de autenticação do usuário, você concluirá estas tarefas:

. Configure as definições no StorageGRID.
. Use o software do provedor de identidade SSO para criar uma confiança de parte confiável (AD FS), aplicativo empresarial (Entra ID) ou provedor de serviços (PingFederate) para cada nó de administração.
. Retorne ao StorageGRID para ativar o SSO.


O modo Sandbox facilita a execução desta configuração de back-and-forth e testar todas as suas configurações antes de ativar o SSO. Quando você está usando o modo sandbox, os usuários não podem entrar usando SSO.



== Acesse o assistente

.Passos
. Selecione *CONFIGURATION* > *access control* > *Single sign-on*. É apresentada a página de início de sessão único.
+

NOTE: Se o botão Configurar definições SSO estiver desativado, confirme que configurou o fornecedor de identidade como a origem de identidade federada. link:requirements-for-sso.html["Requisitos e considerações para logon único"]Consulte a .

. Selecione *Configure SSO settings*. A página fornecer detalhes do provedor de identidade é exibida.




== Forneça detalhes do provedor de identidade

.Passos
. Selecione o *SSO type* na lista suspensa.
. Se você selecionou o ative Directory como o tipo SSO, digite o *nome do serviço de Federação* para o provedor de identidade, exatamente como aparece no AD FS (Serviço de Federação do ative Directory).
+

NOTE: Para localizar o nome do serviço de federação, vá para Gerenciador do Windows Server. Selecione *Ferramentas* > *Gerenciamento do AD FS*. No menu Ação, selecione *Editar Propriedades do Serviço de Federação*. O Nome do Serviço de Federação é apresentado no segundo campo.

. Especifique qual certificado TLS será usado para proteger a conexão quando o provedor de identidade enviar informações de configuração SSO em resposta a solicitações StorageGRID.
+
** *Use o certificado CA do sistema operacional*: Use o certificado CA padrão instalado no sistema operacional para proteger a conexão.
** *Usar certificado CA personalizado*: Use um certificado CA personalizado para proteger a conexão.
+
Se você selecionar essa configuração, copie o texto do certificado personalizado e cole-o na caixa de texto *certificado CA*.

** *Não use TLS*: Não use um certificado TLS para proteger a conexão.
+

CAUTION: Se você alterar o certificado da CA, link:../maintain/starting-or-restarting-service.html["Reinicie o serviço mgmt-api nos nós de administração"]imediatamente e testar se há um SSO bem-sucedido no Gerenciador de Grade.



. Selecione *continuar*. A página fornecer identificador de parte dependente é exibida.




== [[Enter-sandbox-mode]]forneça identificador de entidade dependente

. Preencha os campos na página fornecer identificador de parte dependente com base no tipo SSO selecionado.
+
[role="tabbed-block"]
====
.Ative Directory
--
.. Especifique o *identificador de entidade dependente* para StorageGRID. Esse valor controla o nome que você usa para cada confiança de parte confiável no AD FS.
+
*** Por exemplo, se sua grade tiver apenas um nó Admin e você não antecipar a adição de mais nós Admin no futuro, digite `SG` ou `StorageGRID`.
*** Se sua grade incluir mais de um nó Admin, inclua a cadeia `[HOSTNAME]` no identificador. Por exemplo, `SG-[HOSTNAME]`. A inclusão dessa cadeia de carateres resulta em uma tabela que mostra o identificador de parte confiável para cada nó Admin na grade, com base no nome do host do nó.
+

NOTE: Você deve criar uma confiança de parte confiável para cada nó de administrador no seu sistema StorageGRID. Ter uma confiança de parte confiável para cada nó de administração garante que os usuários possam entrar e sair com segurança de qualquer nó de administração.



.. Selecione *Salvar e entre no modo sandbox*.


--
.ID entra
--
.. Na seção aplicativo empresarial, especifique o *Nome do aplicativo empresarial* para StorageGRID. Esse valor controla o nome usado para cada aplicativo corporativo no Entra ID.
+
*** Por exemplo, se sua grade tiver apenas um nó Admin e você não antecipar a adição de mais nós Admin no futuro, digite `SG` ou `StorageGRID`.
*** Se sua grade incluir mais de um nó Admin, inclua a cadeia `[HOSTNAME]` no identificador. Por exemplo, `SG-[HOSTNAME]`. A inclusão dessa cadeia de carateres resulta em uma tabela que mostra um nome de aplicativo corporativo para cada nó Admin no sistema, com base no nome do host do nó.
+

NOTE: Você deve criar um aplicativo empresarial para cada nó de administração no sistema StorageGRID. Ter um aplicativo corporativo para cada nó de administração garante que os usuários possam entrar e sair com segurança de qualquer nó de administração.



.. Siga as etapas em link:../admin/creating-enterprise-application-entra-id.html["Crie aplicações empresariais no Entra ID"] para criar um aplicativo corporativo para cada nó de administração listado na tabela.
.. No Entra ID, copie o URL de metadados de federação para cada aplicativo corporativo. Em seguida, cole esse URL no campo *URL de metadados de Federação* correspondente no StorageGRID.
.. Depois de copiar e colar um URL de metadados de federação para todos os nós de administração, selecione *Salvar e entrar no modo sandbox*.


--
.PingFederate
--
.. Na seção Fornecedor de Serviços (SP), especifique o *ID de conexão SP* para StorageGRID. Esse valor controla o nome que você usa para cada conexão SP no PingFederate.
+
*** Por exemplo, se sua grade tiver apenas um nó Admin e você não antecipar a adição de mais nós Admin no futuro, digite `SG` ou `StorageGRID`.
*** Se sua grade incluir mais de um nó Admin, inclua a cadeia `[HOSTNAME]` no identificador. Por exemplo, `SG-[HOSTNAME]`. A inclusão dessa cadeia de carateres resulta em uma tabela que mostra o ID de conexão do SP para cada nó de administrador no sistema, com base no nome do host do nó.
+

NOTE: Você deve criar uma conexão SP para cada nó de administração no sistema StorageGRID. Ter uma conexão SP para cada nó de administração garante que os usuários possam entrar e sair com segurança de qualquer nó de administração.



.. Especifique o URL de metadados de federação para cada nó Admin no campo *URL de metadados de Federação*.
+
Use o seguinte formato:

+
[listing]
----
https://<Federation Service Name>:<port>/pf/federation_metadata.ping?PartnerSpId=<SP Connection ID>
----
.. Selecione *Salvar e entre no modo sandbox*.


--
====




== Configurar trusts de terceiros confiáveis, aplicativos empresariais ou conexões SP

Depois de salvar a configuração e entrar no modo sandbox, você pode concluir e testar a configuração para o tipo SSO selecionado.

O StorageGRID pode permanecer no modo sandbox enquanto necessário. No entanto, somente usuários federados e usuários locais podem entrar.

[role="tabbed-block"]
====
.Ative Directory
--
.Passos
. Vá para Serviços de Federação do ative Directory (AD FS).
. Crie uma ou mais confianças de parte confiáveis para o StorageGRID, usando cada identificador de parte confiável mostrado na tabela na página Configurar SSO.
+
Você deve criar uma confiança para cada nó Admin mostrado na tabela.

+
Para obter instruções, vá link:../admin/creating-relying-party-trusts-in-ad-fs.html["Criar confiança de parte confiável no AD FS"]para .



--
.ID entra
--
.Passos
. Na página de logon único para o nó Admin ao qual você está conetado atualmente, selecione o botão para baixar e salvar os metadados SAML.
. Em seguida, para qualquer outro nó Admin na sua grade, repita estas etapas:
+
.. Faça login no nó.
.. Selecione *CONFIGURATION* > *access control* > *Single sign-on*.
.. Baixe e salve os metadados SAML para esse nó.


. Vá para o portal do Azure.
. Siga as etapas em link:../admin/creating-enterprise-application-entra-id.html["Crie aplicações empresariais no Entra ID"] para carregar o arquivo de metadados SAML para cada nó Admin em seu aplicativo empresarial Entra ID correspondente.


--
.PingFederate
--
.Passos
. Na página de logon único para o nó Admin ao qual você está conetado atualmente, selecione o botão para baixar e salvar os metadados SAML.
. Em seguida, para qualquer outro nó Admin na sua grade, repita estas etapas:
+
.. Faça login no nó.
.. Selecione *CONFIGURATION* > *access control* > *Single sign-on*.
.. Baixe e salve os metadados SAML para esse nó.


. Vá para PingFederate.
. link:../admin/creating-sp-connection-ping.html["Crie uma ou mais conexões de provedor de serviços (SP) para o StorageGRID"]. Use o ID de conexão do SP para cada nó de administrador (mostrado na tabela na página Configurar SSO) e os metadados SAML que você baixou para esse nó de administrador.
+
Você deve criar uma conexão SP para cada nó de administrador mostrado na tabela.



--
====


== [[test-sso]]Configuração do teste

Antes de aplicar o uso de logon único em todo o sistema StorageGRID, confirme se o logon único e o logout único estão configurados corretamente para cada nó de administração.

[role="tabbed-block"]
====
.Ative Directory
--
.Passos
. Na página Configurar SSO, localize o link na etapa testar configuração do assistente.
+
O URL é derivado do valor inserido no campo *Nome do serviço de Federação*.

. Selecione o link ou copie e cole o URL em um navegador para acessar a página de logon do provedor de identidade.
. Para confirmar que você pode usar o SSO para entrar no StorageGRID, selecione *entrar em um dos seguintes sites*, selecione o identificador de parte confiável para seu nó de administrador principal e selecione *entrar*.
. Introduza o seu nome de utilizador federado e a palavra-passe.
+
** Se as operações de login e logout SSO forem bem-sucedidas, uma mensagem de sucesso será exibida.
** Se a operação SSO não for bem-sucedida, será exibida uma mensagem de erro. Corrija o problema, limpe os cookies do navegador e tente novamente.


. Repita estas etapas para verificar a conexão SSO para cada nó Admin na grade.


--
.ID entra
--
.Passos
. Vá para a página de logon único no portal do Azure.
. Selecione *Teste este aplicativo*.
. Insira as credenciais de um usuário federado.
+
** Se as operações de login e logout SSO forem bem-sucedidas, uma mensagem de sucesso será exibida.
** Se a operação SSO não for bem-sucedida, será exibida uma mensagem de erro. Corrija o problema, limpe os cookies do navegador e tente novamente.


. Repita estas etapas para verificar a conexão SSO para cada nó Admin na grade.


--
.PingFederate
--
.Passos
. Na página Configurar SSO, selecione o primeiro link na mensagem do modo Sandbox.
+
Selecione e teste um link de cada vez.

. Insira as credenciais de um usuário federado.
+
** Se as operações de login e logout SSO forem bem-sucedidas, uma mensagem de sucesso será exibida.
** Se a operação SSO não for bem-sucedida, será exibida uma mensagem de erro. Corrija o problema, limpe os cookies do navegador e tente novamente.


. Selecione o próximo link para verificar a conexão SSO para cada nó Admin na grade.
+
Se você vir uma mensagem Página expirada, selecione o botão *voltar* no seu navegador e reenvie suas credenciais.



--
====


== Ative o logon único

Quando você confirmar que pode usar o SSO para fazer login em cada nó de administrador, você pode ativar o SSO para todo o seu sistema StorageGRID.


TIP: Quando o SSO está ativado, todos os usuários devem usar o SSO para acessar o Gerenciador de Grade, o Gerenciador de Locatário, a API de Gerenciamento de Grade e a API de Gerenciamento de Locatário. Os usuários locais não podem mais acessar o StorageGRID.

.Passos
. Na etapa testar configuração do assistente configurar SSO, selecione *Ativar SSO*.
. Revise a mensagem de aviso e selecione *Ativar SSO*.
+
O início de sessão único está agora ativado. A página de logon único aparece e agora inclui os detalhes do SSO que você acabou de configurar.

. Para editar a configuração, selecione *Editar*.
. Para desativar o logon único, selecione *Desativar SSO*.



TIP: Se você estiver usando o Portal do Azure e acessar o StorageGRID do mesmo computador que usa para acessar o ID do Entra, verifique se o usuário do portal do Azure também é um usuário autorizado do StorageGRID (um usuário em um grupo federado que foi importado para o StorageGRID ou sair do portal do Azure antes de tentar entrar no StorageGRID.
