---
permalink: admin/creating-enterprise-application-entra-id.html 
sidebar: sidebar 
keywords: enterprise application, entra id, single sign on, sso 
summary: Você usa o Entra ID para criar um aplicativo corporativo para cada nó de administração no sistema. 
---
= Crie aplicações empresariais no Entra ID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você usa o Entra ID para criar um aplicativo corporativo para cada nó de administração no sistema.

.Antes de começar
* Você começou a configurar o logon único para o StorageGRID e selecionou *Entra ID* como o tipo SSO.
* Você tem link:../admin/configure-sso.html#enter-sandbox-mode["entrou no modo sandbox"] no Gerenciador de Grade.
* Você tem o *Nome do aplicativo Enterprise* para cada nó Admin no seu sistema. Você pode copiar esses valores da tabela de detalhes do Admin Node na página Configurar SSO.
+

NOTE: Você deve criar um aplicativo empresarial para cada nó de administração no sistema StorageGRID. Ter um aplicativo corporativo para cada nó de administração garante que os usuários possam entrar e sair com segurança de qualquer nó de administração.

* Você tem experiência em criar aplicativos empresariais no Entra ID.
* Você tem uma conta do Azure com uma assinatura ativa.
* Você tem uma das seguintes funções na conta de ID do Entra: Administrador Global, Administrador de aplicativos em nuvem, Administrador de aplicativos ou proprietário do responsável do serviço.




== Aceder à ID Entra

.Passos
. Inicie sessão no https://portal.azure.com["Portal do Azure"^].
. Navegue até https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade["ID entra"^].
.  https://portal.azure.com/#blade/Microsoft_AAD_IAM/StartboardApplicationsMenuBlade/Overview/menuId/["Aplicações empresariais"^]Selecione .




== Crie aplicativos empresariais e salve a configuração SSO do StorageGRID

Para salvar a configuração SSO para o ID do Entra no StorageGRID, você deve usar o ID do Entra para criar um aplicativo corporativo para cada nó de administração. Você copiará os URLs de metadados da federação do ID do Entra e os colará nos campos *URL de metadados da Federação* correspondentes na página Configurar SSO.

.Passos
. Repita as etapas a seguir para cada nó Admin.
+
.. No painel Entra ID Enterprise Applications (aplicativos empresariais do ID do Entra), selecione *New Application* (novo aplicativo).
.. Selecione *Crie seu próprio aplicativo*.
.. Para o nome, digite o *Nome do aplicativo Enterprise* que você copiou da tabela de detalhes do Admin Node na página Configurar SSO.
.. Deixe o botão de opção *integrar qualquer outro aplicativo que você não encontrar na galeria (não galeria)* selecionado.
.. Selecione *criar*.
.. Selecione o link *Get Started* no *2. Configure a caixa Single Sign On* (Início de sessão único) ou selecione o link *Single Sign-On* (Início de sessão único) na margem esquerda.
.. Selecione a caixa *SAML*.
.. Copie o URL de metadados de Federação de aplicativos*, que você pode encontrar em *Etapa 3 certificado de assinatura SAML*.
.. Vá para a página Configurar SSO e cole o URL no campo *URL de metadados de Federação* que corresponde ao nome do aplicativo *Enterprise* usado.


. Depois de colar um URL de metadados de federação para cada nó de administrador e fazer todas as outras alterações necessárias na configuração SSO, selecione *Salvar* na página Configurar SSO.




== Faça o download dos metadados SAML para cada nó de administração

Depois que a configuração SSO for salva, você pode baixar um arquivo de metadados SAML para cada nó de administrador no sistema StorageGRID.

.Passos
. Repita estas etapas para cada nó Admin.
+
.. Inicie sessão no StorageGRID a partir do nó de administração.
.. Selecione *CONFIGURATION* > *access control* > *Single sign-on*.
.. Selecione o botão para baixar os metadados SAML para esse nó Admin.
.. Salve o arquivo, que você carregará no Entra ID.






== Carregue metadados SAML para cada aplicação empresarial

Depois de fazer o download de um arquivo de metadados SAML para cada nó de administrador do StorageGRID, execute as seguintes etapas no ID do Entra:

.Passos
. Retorne ao Portal do Azure.
. Repita estes passos para cada aplicação empresarial:
+

NOTE: Talvez seja necessário atualizar a página aplicativos empresariais para ver os aplicativos adicionados anteriormente na lista.

+
.. Vá para a página Propriedades do aplicativo corporativo.
.. Defina *atribuição necessária* como *não* (a menos que você queira configurar atribuições separadamente).
.. Aceda à página de início de sessão único.
.. Conclua a configuração SAML.
.. Selecione o botão *Upload metadata file* e selecione o arquivo de metadados SAML que você baixou para o Admin Node correspondente.
.. Depois que o arquivo for carregado, selecione *Save* e, em seguida, selecione *X* para fechar o painel. Você será retornado à página Configurar logon único com SAML.


. link:../admin/configure-sso.html#test-sso["Teste cada aplicação"].

