---
permalink: admin/editing-traffic-classification-policy.html 
sidebar: sidebar 
keywords: edit traffic classification policy 
summary: Você pode editar uma política de classificação de tráfego para alterar seu nome ou descrição, ou para criar, editar ou excluir quaisquer regras ou limites para a política. 
---
= Editar política de classificação de tráfego
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode editar uma política de classificação de tráfego para alterar seu nome ou descrição, ou para criar, editar ou excluir quaisquer regras ou limites para a política.

.Antes de começar
* Você está conetado ao Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
* Você tem o link:admin-group-permissions.html["Permissão de acesso à raiz"].


.Passos
. Selecione *CONFIGURATION* > *Network* > *Traffic Classification*.
+
A página políticas de classificação de tráfego é exibida e as políticas existentes são listadas em uma tabela.

. Edite a política usando o menu ações ou a página de detalhes. Consulte link:../admin/creating-traffic-classification-policies.html["crie políticas de classificação de tráfego"] para saber o que introduzir.
+
[role="tabbed-block"]
====
.Menu ações
--
.. Selecione a caixa de verificação da política.
.. Selecione *ações* > *Editar*.


--
.Página de detalhes
--
.. Selecione o nome da política.
.. Selecione o botão *Editar* ao lado do nome da política.


--
====
. Para a etapa Digite o nome da política, edite opcionalmente o nome ou a descrição da política e selecione *continuar*.
. Para a etapa Adicionar regras de correspondência, adicione uma regra ou edite o *tipo* e *valor de correspondência* da regra existente e selecione *continuar*.
. Para a etapa Definir limites, opcionalmente adicione, edite ou exclua um limite e selecione *continuar*.
. Revise a política atualizada e selecione *Salvar e continuar*.
+
As alterações feitas na política são salvas e o tráfego de rede é agora Tratado de acordo com as políticas de classificação de tráfego. Você pode visualizar gráficos de tráfego e verificar se as políticas estão aplicando os limites de tráfego esperados.


