---
permalink: admin/how-ha-groups-are-used.html 
sidebar: sidebar 
keywords: ha groups, high availability group 
summary: 'Você pode usar grupos de alta disponibilidade (HA) para fornecer conexões altamente disponíveis ao StorageGRID para dados de objetos e para uso administrativo.' 
---
= Como os grupos HA são usados?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar grupos de alta disponibilidade (HA) para fornecer conexões altamente disponíveis ao StorageGRID para dados de objetos e para uso administrativo.

* Um grupo de HA pode fornecer conexões administrativas altamente disponíveis ao Gerenciador de Grade ou ao Gerente do Locatário.
* Um grupo HA pode fornecer conexões de dados altamente disponíveis para clientes S3.
* Um grupo de HA que contém apenas uma interface permite fornecer muitos endereços VIP e definir explicitamente endereços IPv6.


Um grupo de HA poderá fornecer alta disponibilidade somente se todos os nós incluídos no grupo oferecerem os mesmos serviços. Ao criar um grupo de HA, adicione interfaces dos tipos de nós que fornecem os serviços de que você precisa.

* *Admin Nodes*: Inclua o serviço Load Balancer e habilite o acesso ao Grid Manager ou ao Tenant Manager.
* *Gateway Nodes*: Inclua o serviço Load Balancer.


[cols="1a,2a"]
|===
| Objetivo do grupo HA | Adicione nós desse tipo ao grupo de HA 


 a| 
Acesso ao Grid Manager
 a| 
* Nó de administração principal (*primário*)
* Nós de administração não primários


*Nota:* o nó de administração principal deve ser a interface principal. Alguns procedimentos de manutenção só podem ser executados a partir do nó de administração principal.



 a| 
Acesso apenas ao Gestor do Locatário
 a| 
* Nós de administração primários ou não primários




 a| 
Acesso ao cliente S3 -- Serviço de Load Balancer
 a| 
* Nós de administração
* Nós de gateway




 a| 
Acesso de cliente S3 para link:../admin/manage-s3-select-for-tenant-accounts.html["S3 Selecione"]
 a| 
* Aparelhos de serviços
* Nós de software baseados em VMware


*Nota*: Os GRUPOS HA são recomendados ao usar o S3 Select, mas não são necessários.

|===


== Limitações do uso de grupos de HA com Grid Manager ou Tenant Manager

Se um serviço do Grid Manager ou do Tenant Manager falhar, o failover do grupo HA não será acionado.

Se você estiver conetado ao Gerenciador de Grade ou ao Gerenciador de Locatário quando ocorrer failover, você será desconetado e deverá fazer login novamente para retomar sua tarefa.

Alguns procedimentos de manutenção não podem ser executados quando o nó Admin principal não está disponível. Durante o failover, você pode usar o Gerenciador de Grade para monitorar seu sistema StorageGRID.
