---
permalink: admin/manage-platform-services-for-tenants.html 
sidebar: sidebar 
keywords: platform service, cloudmirror replication, event notification, search integration service 
summary: Os serviços de plataforma incluem replicação do CloudMirror, notificações de eventos e o serviço de integração de pesquisa. 
---
= O que são serviços de plataforma?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os serviços de plataforma incluem replicação do CloudMirror, notificações de eventos e o serviço de integração de pesquisa.

Se você ativar os serviços de plataforma para contas de locatário do S3, configure sua grade para que os locatários possam acessar os recursos externos necessários para usar esses serviços.

Os serviços de plataforma não são suportados paralink:../tenant/what-is-branch-bucket.html["baldes de galhos"] .



== Replicação do CloudMirror

O serviço de replicação do StorageGRID CloudMirror é usado para espelhar objetos específicos de um bucket do StorageGRID para um destino externo especificado.

Por exemplo, você pode usar a replicação do CloudMirror para espelhar Registros específicos de clientes no Amazon S3 e aproveitar os serviços da AWS para realizar análises nos seus dados.

A replicação do CloudMirror tem algumas semelhanças e diferenças importantes com o recurso de replicação entre grades. Para saber mais, link:../admin/grid-federation-compare-cgr-to-cloudmirror.html["Compare a replicação entre redes e a replicação do CloudMirror"]consulte .


NOTE: A replicação do CloudMirror não é suportada se o bucket de origem tiver o S3 Object Lock habilitado.



== Notificações

Notificações de eventos por bucket são usadas para enviar notificações sobre ações específicas executadas em objetos para um cluster Kafka externo especificado, endpoint webhook ou Amazon Simple Notification Service.

Por exemplo, você pode configurar alertas para serem enviados aos administradores sobre cada objeto adicionado a um bucket, onde os objetos representam arquivos de log associados a um evento crítico do sistema.


NOTE: Embora a notificação de evento possa ser configurada em um bucket com o bloqueio de objeto S3 ativado, os metadados do bloqueio de objeto S3 (incluindo o status reter até a data e retenção legal) dos objetos não serão incluídos nas mensagens de notificação.



== Serviço de integração de pesquisa

O serviço de integração de pesquisa é usado para enviar metadados de objeto S3 para um índice Elasticsearch especificado, onde os metadados podem ser pesquisados ou analisados usando o serviço externo.

Por exemplo, você pode configurar seus buckets para enviar metadados de objeto S3 para um serviço Elasticsearch remoto. Você pode usar o Elasticsearch para realizar pesquisas entre buckets e realizar análises sofisticadas de padrões presentes nos metadados do objeto.


NOTE: Embora a integração do Elasticsearch possa ser configurada em um bucket com o bloqueio de objeto S3 ativado, os metadados do bloqueio de objeto S3 (incluindo o status reter até a data e retenção legal) dos objetos não serão incluídos nas mensagens de notificação.

Com os serviços de plataforma, os locatários têm a capacidade de usar recursos de storage externos, serviços de notificação e serviços de pesquisa ou análise com seus dados. Como o local de destino para serviços de plataforma geralmente é externo à implantação do StorageGRID, você deve decidir se deseja permitir que os locatários usem esses serviços. Se o fizer, você deverá habilitar o uso de serviços de plataforma quando criar ou editar contas de locatário. Você também deve configurar sua rede de modo que as mensagens de serviços de plataforma que os locatários geram possam chegar aos destinos deles.



== Recomendações para o uso de serviços de plataforma

Antes de usar os serviços da plataforma, esteja ciente das seguintes recomendações:

* Se um bucket do S3 no sistema StorageGRID tiver o controle de versão e a replicação do CloudMirror habilitado, você também deverá habilitar o controle de versão do bucket do S3 para o endpoint de destino. Isso permite que a replicação do CloudMirror gere versões de objetos semelhantes no endpoint.
* Você não deve usar mais de 100 locatários ativos com solicitações do S3 que exigem replicação, notificações e integração de pesquisa do CloudMirror. Ter mais de 100 inquilinos ativos ativos pode resultar em desempenho mais lento do cliente S3.
* As solicitações para um endpoint que não pode ser concluído serão enfileiradas para um máximo de 500.000 solicitações. Esse limite é compartilhado igualmente entre locatários ativos. Novos inquilinos podem exceder temporariamente este limite de 500.000 para que os inquilinos recém-criados não sejam injustamente penalizados.


.Informações relacionadas
* link:../tenant/what-platform-services-are.html["Gerenciar serviços de plataforma"]
* link:configuring-storage-proxy-settings.html["Configure as configurações de proxy de armazenamento"]
* link:../monitor/index.html["Monitore o StorageGRID"]

