---
permalink: admin/manually-triggering-autosupport-message.html 
sidebar: sidebar 
keywords: autosupport, how to send asup message 
summary: Para ajudar o suporte técnico na solução de problemas com o sistema StorageGRID, você pode acionar manualmente um pacote AutoSupport a ser enviado. 
---
= Acione manualmente um pacote AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para ajudar o suporte técnico na solução de problemas com o sistema StorageGRID, você pode acionar manualmente um pacote AutoSupport a ser enviado.

.Antes de começar
* Você está conetado ao Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
* Você tem permissão de acesso Root ou Outra configuração de grade.


.Passos
. Selecione *Suporte* > *Ferramentas* > * AutoSupport*.
. Na guia *ações*, selecione *Enviar AutoSupport acionado pelo usuário*.
+
O StorageGRID tenta enviar um pacote de AutoSupport para o site de suporte da NetApp .  Se a tentativa for bem-sucedida, os valores *Resultado mais recente* e *Última hora bem-sucedida* na guia *Resultados* serão atualizados.  Se houver um problema, o valor *Resultado mais recente* é atualizado para "Falha" e o StorageGRID não tenta enviar o pacote AutoSupport novamente.

. Após 1 minuto, atualize a página do AutoSupport no seu navegador para acessar os resultados mais recentes.



TIP: Além disso, você podelink:../monitor/collecting-log-files-and-system-data.html["coletar arquivos de log e dados do sistema mais extensos"] e envie-os para o site de suporte da NetApp .
