---
permalink: s3/index.html 
sidebar: sidebar 
keywords: about s3, s3 rest api, s3 overview 
summary: 'O StorageGRID oferece suporte Ă  API Simple Storage Service (S3), que Ă© implementada como um conjunto de serviĂ§os da Web de transferĂȘncia de Estado representacional (REST).' 
---
= VersĂ”es e atualizaĂ§Ă”es compatĂ­veis da API REST S3 do StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O StorageGRID oferece suporte Ă  API Simple Storage Service (S3), que Ă© implementada como um conjunto de serviĂ§os da Web de transferĂȘncia de Estado representacional (REST).

O suporte Ă  API REST do S3 permite conetar aplicativos orientados a serviĂ§os desenvolvidos para serviĂ§os da Web do S3 ao storage de objetos no local que usa o sistema StorageGRID. SĂŁo necessĂĄrias alteraĂ§Ă”es mĂ­nimas no uso atual de chamadas de API REST do aplicativo cliente S3.



[[supported-versions]]
== VersĂ”es suportadas

O StorageGRID oferece suporte Ă s seguintes versĂ”es especĂ­ficas de STS, S3 e HTTP:

[cols="1a,1a"]
|===
| Item | VersĂŁo 


 a| 
EspecificaĂ§ĂŁo da API STS AssumeRole
 a| 
https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html["DocumentaĂ§ĂŁo da Amazon Web Services (AWS): ReferĂȘncia da API do Amazon Assumerole"^]

Para obter mais informaĂ§Ă”es sobre AssumeRole, consultelink:../tenant/manage-groups.html#set-up-assumerole["Configurar AssumeRole"] .



 a| 
EspecificaĂ§ĂŁo da API S3
 a| 
http://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html["DocumentaĂ§ĂŁo da AWS: ReferĂȘncia da API do Amazon Simple Storage Service"^]



 a| 
HTTP
 a| 
1,1

Para obter mais informaĂ§Ă”es sobre HTTP, consulte HTTP/1,1 (RFCs 7230-35).

https://datatracker.ietf.org/doc/html/rfc2616["IETF RFC 2616: Protocolo de transferĂȘncia de hipertexto (HTTP/1,1)"^]

*Nota*: O StorageGRID nĂŁo suporta a canalizaĂ§ĂŁo HTTP/1,1.

|===


[[updates-to-s3-rest-api-support]]
[[updates-to-rest-api-support]]
== AtualizaĂ§Ă”es para o suporte Ă  API REST do S3

[cols="1a,4a"]
|===
| Solte | ComentĂĄrios 


 a| 
12.1.0
 a| 
* `If-Match`
+
O  `If-Match`cabeĂ§alho se comporta de maneira diferente dependendo da sua configuraĂ§ĂŁo do StorageGRID. Fornecer este cabeĂ§alho pode retornar uma mensagem de erro (501 Not Implemented). Se o  `If-Match`cabeĂ§alho for aceito, mas nĂŁo funcional, um alerta pode ser acionado com instruĂ§Ă”es sobre como habilitar o comportamento de erro mais rigoroso 501 Not Implemented.

* `If-None-Match`
+
O  `If-None-Match`cabeĂ§alho se comporta de maneira diferente dependendo da sua configuraĂ§ĂŁo do StorageGRID. Fornecer este cabeĂ§alho pode retornar uma mensagem de erro (501 Not Implemented). Se o  `If-None-Match`cabeĂ§alho for aceito, mas nĂŁo funcional, um alerta pode ser acionado com instruĂ§Ă”es sobre como habilitar o comportamento de erro mais rigoroso 501 Not Implemented.

* Adicionado suporte para valores de checksum prĂ©-calculados para as seguintes requisiĂ§Ă”es e cabeĂ§alhos suportados:
+
** CompleteMultipartUpload: `x-amz-checksum-crc32`, `x-amz-checksum-crc32c`, e `x-amz-checksum-crc64nvme`
** CreateMultipartUpload: `CRC32`, `CRC32C`, e `CRC64NVME` para `x-amz-checksum-algorithm`
** CopyObject: `CRC32`, `CRC32C`, `CRC64NVME`, e `SHA256` para `x-amz-checksum-algorithm`
** PutObject: `x-amz-checksum-crc32`, `x-amz-checksum-crc32c`, e `x-amz-checksum-crc64nvme`
** UploadPart: `x-amz-checksum-crc32`, `x-amz-checksum-crc32c`, e `x-amz-checksum-crc64nvme`


* Adicionado suporte para  `x-amz-checksum-type` para CreateMultipartUpload e CompleteMultipartUpload.
* Adicionado suporte para a  `s3:x-amz-copy-source` chave de condiĂ§ĂŁo da polĂ­tica.
* Permitir que o bloqueio de objetos do S3 seja ativado em buckets existentes.




 a| 
12,0
 a| 
* Adicionado suporte para compartilhamento de recursos entre origens (CORS) para uma interface de gerenciamento, o que permite que outro domĂ­nio acesse dados no StorageGRID usando APIs de gerenciamento. link:../admin/enable-cross-origin-resource-sharing-for-management-interface.html["Saiba mais"] .
* Adicionado suporte para STS AssumeRole e polĂ­tica de sessĂŁo. Consulte link:../s3/example-session-policies.html["um exemplo de uma polĂ­tica de sessĂŁo"]. VocĂȘ pode configurar AssumeRole em grupos de locatĂĄrios.




 a| 
11,9
 a| 
* Adicionado suporte para valores de checksum SHA-256 prĂ©-calculados para as seguintes solicitaĂ§Ă”es e cabeĂ§alhos suportados. VocĂȘ pode usar esse recurso para verificar a integridade dos objetos carregados:
+
** CompleteMultipartUpload: `x-amz-checksum-sha256`
** CreateMultipartUpload: `x-amz-checksum-algorithm`
** GetObject: `x-amz-checksum-mode`
** Objeto cabeĂ§alho: `x-amz-checksum-mode`
** ListParts
** Objeto Put: `x-amz-checksum-sha256`
** UploadPart: `x-amz-checksum-sha256`


* Adicionada a capacidade de o administrador da grade controlar as configuraĂ§Ă”es de retenĂ§ĂŁo e conformidade no nĂ­vel do locatĂĄrio. Estas definiĂ§Ă”es afetam as definiĂ§Ă”es de bloqueio de objetos do S3.
+
** Modo de retenĂ§ĂŁo padrĂŁo do bucket e modo de retenĂ§ĂŁo de objetos: GovernanĂ§a ou conformidade, se permitido pelo administrador da grade.
** PerĂ­odo de retenĂ§ĂŁo padrĂŁo do bucket e data atĂ© retenĂ§ĂŁo do objeto: Deve ser menor ou igual ao permitido pelo perĂ­odo de retenĂ§ĂŁo mĂĄximo definido pelo administrador da grade.


* Suporte aprimorado para `aws-chunked` codificaĂ§ĂŁo de conteĂșdo e valores de streaming `x-amz-content-sha256`. LimitaĂ§Ă”es:
+
** Se presente, `chunk-signature` Ă© opcional e nĂŁo validado
** Se presente, `x-amz-trailer` o conteĂșdo Ă© ignorado






 a| 
11,8
 a| 
Atualizado os nomes das operaĂ§Ă”es S3 para corresponder aos nomes usados no http://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html["DocumentaĂ§ĂŁo do Amazon Web Services (AWS): ReferĂȘncia da API do Amazon Simple Storage Service"^].



 a| 
11,7
 a| 
* Adicionado link:../s3/quick-reference-support-for-aws-apis.html["ReferĂȘncia rĂĄpida: SolicitaĂ§Ă”es de API S3 suportadas"].
* Adicionado suporte para usar o modo DE GOVERNANĂA com o bloqueio de objetos S3.
* Adicionado suporte para o cabeĂ§alho de resposta especĂ­fico do StorageGRID `x-ntap-sg-cgr-replication-status` para OBTER solicitaĂ§Ă”es DE objeto e objeto PRINCIPAL. Este cabeĂ§alho fornece o status de replicaĂ§ĂŁo de um objeto para replicaĂ§ĂŁo entre grade.
* As solicitaĂ§Ă”es SelectObjectContent agora suportam objetos Parquet.




 a| 
11,6
 a| 
* Adicionado suporte para o uso do `partNumber` parĂąmetro Request em solicitaĂ§Ă”es GET Object e HEAD Object.
* Adicionado suporte para um modo de retenĂ§ĂŁo padrĂŁo e um perĂ­odo de retenĂ§ĂŁo padrĂŁo no nĂ­vel do bucket para o bloqueio de objetos S3.
* Adicionado suporte para a `s3:object-lock-remaining-retention-days` chave de condiĂ§ĂŁo de polĂ­tica para definir o intervalo de perĂ­odos de retenĂ§ĂŁo permitidos para seus objetos.
* Alterado o tamanho mĂĄximo _recommended_ para uma Ășnica operaĂ§ĂŁo PUT Object para 5 GiB (5.368.709.120 bytes). Se vocĂȘ tiver objetos maiores que 5 GiB, use o upload multipart.




 a| 
11,5
 a| 
* Adicionado suporte para gerenciar a criptografia de bucket.
* Adicionado suporte para S3 Object Lock e solicitaĂ§Ă”es de conformidade legadas obsoletas.
* Adicionado suporte para o uso DE EXCLUIR vĂĄrios objetos em buckets versionados.
* O `Content-MD5` cabeĂ§alho de solicitaĂ§ĂŁo agora Ă© suportado corretamente.




 a| 
11,4
 a| 
* Adicionado suporte para EXCLUIR marcaĂ§ĂŁo de balde, OBTER marcaĂ§ĂŁo de balde e COLOCAR marcaĂ§ĂŁo de balde. As etiquetas de alocaĂ§ĂŁo de custos nĂŁo sĂŁo suportadas.
* Para buckets criados no StorageGRID 11,4, nĂŁo Ă© mais necessĂĄrio restringir nomes de chaves de objeto para atender Ă s prĂĄticas recomendadas de desempenho.
* Adicionado suporte para notificaĂ§Ă”es de intervalo no `s3:ObjectRestore:Post` tipo de evento.
* Os limites de tamanho da AWS para peĂ§as de vĂĄrias partes agora sĂŁo aplicados. Cada parte em um upload de vĂĄrias partes deve estar entre 5 MIB e 5 GiB. A Ășltima parte pode ser menor do que 5 MIB.
* Adicionado suporte para TLS 1,3




 a| 
11,3
 a| 
* Adicionado suporte para criptografia no lado do servidor de dados de objeto com chaves fornecidas pelo cliente (SSE-C).
* Adicionado suporte para as operaĂ§Ă”es DE ELIMINAĂĂO, OBTENĂĂO e COLOCAĂĂO do ciclo de vida do balde (apenas aĂ§ĂŁo de expiraĂ§ĂŁo) e para o `x-amz-expiration` cabeĂ§alho de resposta.
* PUT Object, put Object - Copy e Multipart Upload atualizados para descrever o impactos das regras ILM que usam o posicionamento sĂ­ncrono na ingestĂŁo.
* As cifras TLS 1,1 nĂŁo sĂŁo mais suportadas.




 a| 
11,2
 a| 
Adicionado suporte para restauraĂ§ĂŁo PĂS-objeto para uso com Cloud Storage Pools. Adicionado suporte para o uso da sintaxe da AWS para ARN, chaves de condiĂ§ĂŁo de polĂ­tica e variĂĄveis de polĂ­tica em polĂ­ticas de grupo e bucket. As polĂ­ticas de grupo e bucket existentes que usam a sintaxe StorageGRID continuarĂŁo a ser suportadas.

*ObservaĂ§ĂŁo:* os usos de ARN/URN em outra configuraĂ§ĂŁo JSON/XML, incluindo aqueles usados em recursos personalizados do StorageGRID, nĂŁo foram alterados.



 a| 
11,1
 a| 
Adicionado suporte para compartilhamento de recursos entre origens (CORS), HTTP para conexĂ”es de clientes S3 para nĂłs de grade e configuraĂ§Ă”es de conformidade em buckets.



 a| 
11,0
 a| 
Adicionado suporte para configuraĂ§ĂŁo de serviĂ§os de plataforma (replicaĂ§ĂŁo do CloudMirror, notificaĂ§Ă”es e integraĂ§ĂŁo de pesquisa do Elasticsearch) para buckets. TambĂ©m foi adicionado suporte para restriĂ§Ă”es de localizaĂ§ĂŁo de marcaĂ§ĂŁo de objetos para buckets e a consistĂȘncia disponĂ­vel.



 a| 
10,4
 a| 
Adicionado suporte para alteraĂ§Ă”es de verificaĂ§ĂŁo de ILM para controle de versĂŁo, atualizaĂ§Ă”es de pĂĄgina de nomes de domĂ­nio de endpoints, condiĂ§Ă”es e variĂĄveis em polĂ­ticas, exemplos de polĂ­ticas e a permissĂŁo PutOverwriteObject.



 a| 
10,3
 a| 
Adicionado suporte para controle de versĂŁo.



 a| 
10,2
 a| 
Adicionado suporte para polĂ­ticas de acesso de grupo e bucket, e para cĂłpia de vĂĄrias partes (Upload de peĂ§a - cĂłpia).



 a| 
10,1
 a| 
Adicionado suporte para upload multipart, solicitaĂ§Ă”es no estilo virtual-hosted e autenticaĂ§ĂŁo v4.



 a| 
10,0
 a| 
Suporte inicial da API REST S3 pelo sistema StorageGRID .  A versĂŁo atualmente suportada da _ReferĂȘncia da API do ServiĂ§o de Armazenamento Simples_ Ă© 2006-03-01.

|===