---
permalink: s3/put-object-copy.html 
sidebar: sidebar 
keywords: put object copy, CopyObject 
summary: VocĂŞ pode usar a solicitaĂ§ĂŁo S3 CopyObject para criar uma cĂłpia de um objeto que jĂĄ estĂĄ armazenado no S3. Uma operaĂ§ĂŁo CopyObject ĂŠ a mesma que executar um GET e depois um PUT. 
---
= Crie uma cĂłpia de um objeto no StorageGRID com a solicitaĂ§ĂŁo S3 CopyObject
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VocĂŞ pode usar a solicitaĂ§ĂŁo S3 CopyObject para criar uma cĂłpia de um objeto que jĂĄ estĂĄ armazenado no S3. Uma operaĂ§ĂŁo CopyObject ĂŠ a mesma que executar GetObject seguido por PutObject.



[[resolve-conflicts]]
== Resolver conflitos

As solicitaĂ§Ăľes de cliente conflitantes, como dois clientes escrevendo para a mesma chave, sĂŁo resolvidas com base em "vitĂłrias mais recentes". O tempo para a avaliaĂ§ĂŁo "Ăşltimos ganhos" ĂŠ baseado em quando o sistema StorageGRID completa uma determinada solicitaĂ§ĂŁo e nĂŁo em quando os clientes S3 comeĂ§am uma operaĂ§ĂŁo.



[[object-size]]
== Tamanho do objeto

O tamanho mĂĄximo _recomendado_ para uma Ăşnica operaĂ§ĂŁo PutObject ĂŠ de 5 GiB (5.368.709.120 bytes). Se vocĂŞ tiver objetos maiores que 5 GiB, use link:operations-for-multipart-uploads.html["carregamento multipart"] em vez disso.

O tamanho mĂĄximo _suportado_ para uma Ăşnica operaĂ§ĂŁo PutObject ĂŠ de 5 TIB (5.497.558.138.880 bytes).


NOTE: Se vocĂŞ atualizou do StorageGRID 11,6 ou anterior, o alerta COLOCAR tamanho do objeto muito grande S3 serĂĄ acionado se vocĂŞ tentar carregar um objeto que exceda 5 GiB. Se vocĂŞ tiver uma nova instalaĂ§ĂŁo do StorageGRID 11,7 ou 11,8, o alerta nĂŁo serĂĄ acionado neste caso. No entanto, para se alinhar com o padrĂŁo AWS S3, futuras versĂľes do StorageGRID nĂŁo suportarĂŁo uploads de objetos maiores que 5 GiB.



[[utf-8-characters-in-user-metadata]]
== UTF-8 carateres em metadados do usuĂĄrio

Se uma solicitaĂ§ĂŁo incluir valores UTF-8 (nĂŁo escapados) no nome da chave ou valor dos metadados definidos pelo usuĂĄrio, o comportamento do StorageGRID ĂŠ indefinido.

O StorageGRID nĂŁo analisa nem interpreta carateres UTF-8 escapados incluĂ­dos no nome da chave ou no valor dos metadados definidos pelo usuĂĄrio. Os carateres UTF-8 escapados sĂŁo tratados como carateres ASCII:

* As solicitaĂ§Ăľes sĂŁo bem-sucedidas se os metadados definidos pelo usuĂĄrio incluĂ­rem carateres UTF-8 escapados.
* O StorageGRID nĂŁo retorna o `x-amz-missing-meta` cabeĂ§alho se o valor interpretado do nome ou valor da chave incluir carateres nĂŁo imprimĂ­veis.




[[supported-request-headers]]
== CabeĂ§alhos de solicitaĂ§ĂŁo suportados

Os seguintes cabeĂ§alhos de solicitaĂ§ĂŁo sĂŁo suportados:

* `Content-Type`
* `x-amz-copy-source`
* `x-amz-copy-source-if-match`
* `x-amz-copy-source-if-none-match`
* `x-amz-copy-source-if-unmodified-since`
* `x-amz-copy-source-if-modified-since`
* `x-amz-meta-`, seguido por um par de nome-valor contendo metadados definidos pelo usuĂĄrio
* `x-amz-metadata-directive`: O valor padrĂŁo ĂŠ `COPY`, que permite copiar o objeto e os metadados associados.
+
VocĂŞ pode especificar `REPLACE` para substituir os metadados existentes ao copiar o objeto ou para atualizar os metadados do objeto.

* `x-amz-storage-class`
* `x-amz-tagging-directive`: O valor padrĂŁo ĂŠ `COPY`, que permite copiar o objeto e todas as tags.
+
VocĂŞ pode especificar `REPLACE` para substituir as tags existentes ao copiar o objeto ou para atualizar as tags.

* S3 cabeĂ§alhos de solicitaĂ§ĂŁo de bloqueio de objetos:
+
** `x-amz-object-lock-mode`
** `x-amz-object-lock-retain-until-date`
** `x-amz-object-lock-legal-hold`
+
Se uma solicitaĂ§ĂŁo for feita sem esses cabeĂ§alhos, as configuraĂ§Ăľes de retenĂ§ĂŁo padrĂŁo do intervalo serĂŁo usadas para calcular o modo de versĂŁo do objeto e manter atĂŠ a data. link:use-s3-api-for-s3-object-lock.html["Use a API REST do S3 para configurar o bloqueio de objetos do S3"]Consulte .



* CabeĂ§alhos de pedido SSE:
+
** `x-amz-copy-sourceâ-server-sideâ-encryptionâ-customer-algorithm`
** `x-amz-copy-sourceâ-server-side-encryption-customer-key`
** `x-amz-copy-sourceâ-server-side-encryption-customer-key-MD5`
** `x-amz-server-side-encryption`
** `x-amz-server-side-encryption-customer-key-MD5`
** `x-amz-server-side-encryption-customer-key`
** `x-amz-server-side-encryption-customer-algorithm`
+
Consulte <<CabeĂ§alhos de solicitaĂ§ĂŁo para criptografia do lado do servidor>>







[[unsupported-request-headers]]
== CabeĂ§alhos de solicitaĂ§ĂŁo nĂŁo suportados

Os seguintes cabeĂ§alhos de solicitaĂ§ĂŁo nĂŁo sĂŁo suportados:

* `Cache-Control`
* `Content-Disposition`
* `Content-Encoding`
* `Content-Language`
* `Expires`
* `If-Match`
+
O  `If-Match header`ĂŠ aceito, mas nĂŁo funcional.

* `If-None-Match`
+
O  `If-None-Match header` ĂŠ aceito, mas nĂŁo funcional.

* `x-amz-checksum-algorithm`
+
Quando vocĂŞ copia um objeto, se o objeto de origem tiver um checksum, o StorageGRID nĂŁo copia esse valor de checksum para o novo objeto. Esse comportamento se aplica se vocĂŞ tentar ou nĂŁo `x-amz-checksum-algorithm` usar na solicitaĂ§ĂŁo de objeto.

* `x-amz-website-redirect-location`




[[storage-class-options]]
== OpĂ§Ăľes de classe de armazenamento

O `x-amz-storage-class` cabeĂ§alho de solicitaĂ§ĂŁo ĂŠ suportado e afeta quantas cĂłpias de objeto criadas pelo StorageGRID se a regra ILM correspondente usar o compromisso duplo ou equilibrado link:../ilm/data-protection-options-for-ingest.html["opĂ§ĂŁo de ingestĂŁo"].

* `STANDARD`
+
(PadrĂŁo) especifica uma operaĂ§ĂŁo de ingestĂŁo de commit duplo quando a regra ILM usa a opĂ§ĂŁo de commit duplo ou quando a opĂ§ĂŁo Balanced retorna Ă  criaĂ§ĂŁo de cĂłpias provisĂłrias.

* `REDUCED_REDUNDANCY`
+
Especifica uma operaĂ§ĂŁo de ingestĂŁo de commit Ăşnico quando a regra ILM usa a opĂ§ĂŁo de commit duplo ou quando a opĂ§ĂŁo Balanced retorna Ă  criaĂ§ĂŁo de cĂłpias provisĂłrias.

+

NOTE: Se vocĂŞ estiver ingerindo um objeto em um bucket com o S3 Object Lock ativado, a `REDUCED_REDUNDANCY` opĂ§ĂŁo serĂĄ ignorada. Se vocĂŞ estiver ingerindo um objeto em um bucket compatĂ­vel com legado, a `REDUCED_REDUNDANCY` opĂ§ĂŁo retornarĂĄ um erro. A StorageGRID sempre realizarĂĄ uma ingestĂŁo de confirmaĂ§ĂŁo dupla para garantir que os requisitos de conformidade sejam atendidos.





[[using-x-amz-copy-source-in-copyobject]]
== Usando x-amz-copy-source em CopyObject

Se o intervalo de origem e a chave, especificados no `x-amz-copy-source` cabeĂ§alho, forem diferentes do intervalo de destino e da chave, uma cĂłpia dos dados do objeto de origem serĂĄ gravada no destino.

Se a origem e o destino corresponderem e o `x-amz-metadata-directive` cabeĂ§alho for especificado como `REPLACE`, os metadados do objeto serĂŁo atualizados com os valores de metadados fornecidos na solicitaĂ§ĂŁo. Nesse caso, o StorageGRID nĂŁo reingere o objeto. Isto tem duas consequĂŞncias importantes:

* NĂŁo ĂŠ possĂ­vel usar CopyObject para criptografar um objeto existente no local ou para alterar a criptografia de um objeto existente no local. Se vocĂŞ fornecer o `x-amz-server-side-encryption` cabeĂ§alho ou o `x-amz-server-side-encryption-customer-algorithm` cabeĂ§alho, o StorageGRID rejeita a solicitaĂ§ĂŁo e retorna `XNotImplemented`.
* A opĂ§ĂŁo de comportamento de ingestĂŁo especificada na regra ILM correspondente nĂŁo ĂŠ usada. Quaisquer alteraĂ§Ăľes no posicionamento de objetos que sĂŁo acionadas pela atualizaĂ§ĂŁo sĂŁo feitas quando o ILM ĂŠ reavaliado por processos normais de ILM em segundo plano.
+
Isso significa que se a regra ILM usar a opĂ§ĂŁo estrita para o comportamento de ingestĂŁo, nenhuma aĂ§ĂŁo serĂĄ tomada se os posicionamentos de objeto necessĂĄrios nĂŁo puderem ser feitos (por exemplo, porque um local recĂŠm-exigido nĂŁo estĂĄ disponĂ­vel). O objeto atualizado mantĂŠm seu posicionamento atual atĂŠ que o posicionamento necessĂĄrio seja possĂ­vel.





[[request-headers-for-server-side-encryption]]
== CabeĂ§alhos de solicitaĂ§ĂŁo para criptografia do lado do servidor

Se link:using-server-side-encryption.html["use a criptografia do lado do servidor"]vocĂŞ , os cabeĂ§alhos de solicitaĂ§ĂŁo fornecidos dependem se o objeto de origem estĂĄ criptografado e se vocĂŞ planeja criptografar o objeto de destino.

* Se o objeto de origem for criptografado usando uma chave fornecida pelo cliente (SSE-C), vocĂŞ deve incluir os trĂŞs cabeĂ§alhos a seguir na solicitaĂ§ĂŁo CopyObject, para que o objeto possa ser descriptografado e copiado:
+
** `x-amz-copy-sourceâ-server-sideâ-encryptionâ-customer-algorithm`: Especificar `AES256`.
** `x-amz-copy-sourceâ-server-side-encryption-customer-key`: Especifique a chave de criptografia fornecida quando vocĂŞ criou o objeto de origem.
** `x-amz-copy-sourceâ-server-side-encryption-customer-key-MD5`: Especifique o resumo MD5 que vocĂŞ forneceu quando criou o objeto de origem.


* Se vocĂŞ quiser criptografar o objeto de destino (a cĂłpia) com uma chave exclusiva que vocĂŞ fornece e gerencia, inclua os trĂŞs cabeĂ§alhos a seguir:
+
** `x-amz-server-side-encryption-customer-algorithm`: Especificar `AES256`.
** `x-amz-server-side-encryption-customer-key`: Especifique uma nova chave de criptografia para o objeto de destino.
** `x-amz-server-side-encryption-customer-key-MD5`: Especifique o resumo MD5 da nova chave de criptografia.


+

CAUTION: As chaves de criptografia que vocĂŞ fornece nunca sĂŁo armazenadas. Se vocĂŞ perder uma chave de criptografia, perderĂĄ o objeto correspondente. Antes de usar chaves fornecidas pelo cliente para proteger os dados do objeto, revise as consideraĂ§Ăľes para link:using-server-side-encryption.html["usando criptografia do lado do servidor"].

* Se vocĂŞ quiser criptografar o objeto de destino (a cĂłpia) com uma chave exclusiva gerenciada pelo StorageGRID (SSE), inclua esse cabeĂ§alho na solicitaĂ§ĂŁo de CopyObject:
+
** `x-amz-server-side-encryption`
+

NOTE: O `server-side-encryption` valor do objeto nĂŁo pode ser atualizado. Em vez disso, faĂ§a uma cĂłpia com um novo `server-side-encryption` valor usando `x-amz-metadata-directive`: `REPLACE`.







[[versioning]]
== Controle de versĂŁo

Se o bucket de origem for versionado, vocĂŞ pode usar o `x-amz-copy-source` cabeĂ§alho para copiar a versĂŁo mais recente de um objeto. Para copiar uma versĂŁo especĂ­fica de um objeto, vocĂŞ deve especificar explicitamente a versĂŁo a ser copiada usando o `versionId` subrecurso. Se o intervalo de destino for versionado, a versĂŁo gerada serĂĄ retornada `x-amz-version-id` no cabeĂ§alho de resposta. Se o controle de versĂŁo estiver suspenso para o bucket de destino, `x-amz-version-id` retorna um valor "nulo".
