---
permalink: s3/upload-part-copy.html 
sidebar: sidebar 
keywords: UploadPart, UploadPartCopy, multipart uploads, uploads, 
summary: A operação UploadPartCopy carrega uma parte de um objeto copiando dados de um objeto existente como fonte de dados. 
---
= UploadPartCopy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A operação UploadPartCopy carrega uma parte de um objeto copiando dados de um objeto existente como fonte de dados.

A operação UploadPartCopy é implementada com todo o comportamento da API REST do Amazon S3. Sujeito a alterações sem aviso prévio.

Essa solicitação lê e grava os dados de objeto especificados no `x-amz-copy-source-range` sistema StorageGRID.

Os seguintes cabeçalhos de solicitação são suportados:

* `x-amz-copy-source-if-match`
* `x-amz-copy-source-if-none-match`
* `x-amz-copy-source-if-unmodified-since`
* `x-amz-copy-source-if-modified-since`




== Cabeçalhos de solicitação para criptografia do lado do servidor

Se você especificou criptografia SSE-C para a solicitação CreateMultipartUpload, você também deve incluir os seguintes cabeçalhos de solicitação em cada solicitação UploadPartCopy:

* `x-amz-server-side-encryption-customer-algorithm`: Especificar `AES256`.
* `x-amz-server-side-encryption-customer-key`: Especifique a mesma chave de criptografia fornecida na solicitação CreateMultipartUpload.
* `x-amz-server-side-encryption-customer-key-MD5`: Especifique o mesmo resumo MD5 que você forneceu na solicitação CreateMultipartUpload.


Se o objeto de origem for criptografado usando uma chave fornecida pelo cliente (SSE-C), você deve incluir os três cabeçalhos a seguir na solicitação UploadPartCopy, para que o objeto possa ser descriptografado e copiado:

* `x-amz-copy-source​-server-side​-encryption​-customer-algorithm`: Especificar `AES256`.
* `x-amz-copy-source​-server-side-encryption-customer-key`: Especifique a chave de criptografia fornecida quando você criou o objeto de origem.
* `x-amz-copy-source​-server-side-encryption-customer-key-MD5`: Especifique o resumo MD5 que você forneceu quando criou o objeto de origem.



CAUTION: As chaves de criptografia que você fornece nunca são armazenadas. Se você perder uma chave de criptografia, perderá o objeto correspondente. Antes de usar chaves fornecidas pelo cliente para proteger os dados do objeto, revise as considerações no link:using-server-side-encryption.html["Use a criptografia do lado do servidor"].



== Controle de versão

O upload de várias partes consiste em operações separadas para iniciar o upload, listar uploads, carregar peças, montar as peças carregadas e concluir o upload. Os objetos são criados (e versionados, se aplicável) quando a operação CompleteMultipartUpload é executada.
