---
permalink: s3/using-server-side-encryption.html 
sidebar: sidebar 
keywords: server side encryption, encryption, operations on objects, objects 
summary: A criptografia do lado do servidor permite proteger os dados do objeto em repouso. O StorageGRID criptografa os dados enquanto grava o objeto e descriptografa os dados quando você acessa o objeto. 
---
= Use a criptografia do lado do servidor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A criptografia do lado do servidor permite proteger os dados do objeto em repouso. O StorageGRID criptografa os dados enquanto grava o objeto e descriptografa os dados quando você acessa o objeto.

Se você quiser usar a criptografia do lado do servidor, você pode escolher uma das duas opções mutuamente exclusivas, com base em como as chaves de criptografia são gerenciadas:

* *SSE (criptografia do lado do servidor com chaves gerenciadas pelo StorageGRID)*: Quando você emite uma solicitação S3 para armazenar um objeto, o StorageGRID criptografa o objeto com uma chave exclusiva. Quando você emite uma solicitação S3 para recuperar o objeto, o StorageGRID usa a chave armazenada para descriptografar o objeto.
* *SSE-C (criptografia do lado do servidor com chaves fornecidas pelo cliente)*: Quando você emite uma solicitação S3 para armazenar um objeto, você fornece sua própria chave de criptografia. Quando você recupera um objeto, você fornece a mesma chave de criptografia como parte de sua solicitação. Se as duas chaves de criptografia corresponderem, o objeto será descriptografado e seus dados de objeto serão retornados.
+
Enquanto o StorageGRID gerencia todas as operações de criptografia e descriptografia de objetos, você deve gerenciar as chaves de criptografia fornecidas.

+

CAUTION: As chaves de criptografia que você fornece nunca são armazenadas. Se você perder uma chave de criptografia, perderá o objeto correspondente.

+

NOTE: Se um objeto for criptografado com SSE ou SSE-C, quaisquer configurações de criptografia no nível de bucket ou no nível de grade serão ignoradas.





== Use SSE

Para criptografar um objeto com uma chave exclusiva gerenciada pelo StorageGRID, use o seguinte cabeçalho de solicitação:

`x-amz-server-side-encryption`

O cabeçalho de solicitação SSE é suportado pelas seguintes operações de objeto:

* link:put-object.html["PutObject"]
* link:put-object-copy.html["CopyObject"]
* link:initiate-multipart-upload.html["CreateMultipartUpload"]




== Use SSE-C

Para criptografar um objeto com uma chave exclusiva que você gerencia, use três cabeçalhos de solicitação:

[cols="1a,2a"]
|===
| Cabeçalho da solicitação | Descrição 


 a| 
`x-amz-server-side​-encryption​-customer-algorithm`
 a| 
Especifique o algoritmo de criptografia. O valor da plataforma deve ser `AES256`.



 a| 
`x-amz-server-side​-encryption​-customer-key`
 a| 
Especifique a chave de criptografia que será usada para criptografar ou descriptografar o objeto. O valor da chave deve ser 256 bits, codificado em base64.



 a| 
`x-amz-server-side​-encryption​-customer-key-MD5`
 a| 
Especifique o resumo MD5 da chave de criptografia de acordo com a RFC 1321, que é usada para garantir que a chave de criptografia foi transmitida sem erros. O valor para o resumo MD5 deve ser base64-codificado 128-bit.

|===
Os cabeçalhos de solicitação SSE-C são suportados pelas seguintes operações de objeto:

* link:get-object.html["GetObject"]
* link:head-object.html["HeadObject"]
* link:put-object.html["PutObject"]
* link:put-object-copy.html["CopyObject"]
* link:initiate-multipart-upload.html["CreateMultipartUpload"]
* link:upload-part.html["UploadPart"]
* link:upload-part-copy.html["UploadPartCopy"]




== Considerações sobre o uso de criptografia no lado do servidor com chaves fornecidas pelo cliente (SSE-C)

Antes de usar SSE-C, esteja ciente das seguintes considerações:

* Você deve usar https.
+

CAUTION: O StorageGRID rejeita quaisquer solicitações feitas por http ao usar SSE-C. para considerações de segurança, você deve considerar qualquer chave que você enviar acidentalmente usando http para ser comprometida. Elimine a chave e rode-a conforme adequado.

* O ETag na resposta não é o MD5 dos dados do objeto.
* É necessário gerenciar o mapeamento de chaves de criptografia para objetos. O StorageGRID não armazena chaves de criptografia. Você é responsável por rastrear a chave de criptografia fornecida para cada objeto.
* Se seu bucket estiver habilitado para versionamento, cada versão do objeto deve ter sua própria chave de criptografia. Você é responsável por rastrear a chave de criptografia usada para cada versão do objeto.
* Como você gerencia chaves de criptografia no lado do cliente, você também deve gerenciar quaisquer proteções adicionais, como rotação de chaves, no lado do cliente.
+

CAUTION: As chaves de criptografia que você fornece nunca são armazenadas. Se você perder uma chave de criptografia, perderá o objeto correspondente.

* Se a replicação entre grade ou a replicação do CloudMirror estiver configurada para o bucket, você não poderá ingerir objetos SSE-C. A operação de ingestão falhará.


.Informações relacionadas
https://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html["Guia do usuário do Amazon S3: Usando criptografia do lado do servidor com chaves fornecidas pelo cliente (SSE-C)"^]
