---
permalink: monitor/collecting-log-files-and-system-data.html 
sidebar: sidebar 
keywords: how to collect system data, how to collect logs 
summary: Você pode recuperar arquivos de log do StorageGRID e dados do sistema, incluindo dados de configuração, e enviá-los ao suporte técnico. 
---
= Colete arquivos de log e dados do sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode recuperar arquivos de log do StorageGRID e dados do sistema, incluindo dados de configuração, e enviá-los ao suporte técnico.

.Antes de começar
* Você está conectado ao Grid Manager em qualquer nó de administração usando umlink:../admin/web-browser-requirements.html["navegador da web suportado"] .
* Você link:../admin/admin-group-permissions.html["permissões de acesso específicas"]tem .
* Você tem a senha de provisionamento.


.Sobre esta tarefa
Use o Grid Manager para reunirlink:logs-files-reference.html["ficheiros de registo"] , dados do sistema e dados de configuração de qualquer nó de grade para o período de tempo selecionado.  Os dados são coletados e arquivados em um `.tar.gz` arquivo que você pode baixar para seu computador local ou enviar para o suporte técnico.

Opcionalmente, você pode alterar o destino dos logs de auditoria e enviar informações de auditoria para um servidor syslog externo.  Os logs locais dos registros de auditoria continuam sendo gerados e armazenados quando um servidor syslog externo é configurado. Ver link:../monitor/configure-log-management.html["Configurar gerenciamento de log e servidor syslog externo"] .

.Passos
. Selecione *Suporte* > *Ferramentas* > *Coleta de logs*.  Uma tabela de nós é exibida.
. Selecione os nós de grade para os quais você deseja coletar arquivos de log.
+
Você pode classificar por nome do nó, site e tipo de nó.  As colunas Tipo de site e nó contêm filtros para seleção por sites e tipos de nós individuais.

. Selecione *continuar*.
. Selecione o intervalo de data e hora dos dados a serem incluídos nos arquivos de log.
+
Se você selecionar um período de tempo muito longo ou coletar logs de todos os nós em uma grade grande, o arquivo de log poderá se tornar grande demais para ser armazenado em um nó ou grande demais para ser coletado por um nó de administração para download.  Se qualquer um dos cenários ocorrer, reinicie a coleta de logs com um conjunto menor de dados.

. Selecione os tipos de registos que pretende recolher.
+
** *Logs de aplicativos*: logs específicos do aplicativo que o suporte técnico usa com mais frequência para solução de problemas.  Os logs coletados são um subconjunto dos logs de aplicativos disponíveis.
** *Registros de auditoria*: Registros contendo as mensagens de auditoria geradas durante a operação normal do sistema.
** *Rastreamento de rede*: Logs usados para depuração de rede.
** *Banco de dados Prometheus*: métricas de séries temporais dos serviços em todos os nós.


. Opcionalmente, use a caixa de texto *Notas* para inserir notas sobre os arquivos de log que você está coletando.
+
Você pode usar essas notas para fornecer informações de suporte técnico sobre o problema que o levou a coletar os arquivos de log. Suas anotações são adicionadas a um arquivo `info.txt` chamado , juntamente com outras informações sobre a coleção de arquivos de log. O `info.txt` ficheiro é guardado no pacote de arquivo de registo.

. Na caixa de texto *Senha de provisionamento*, insira a senha de provisionamento para seu sistema StorageGRID .
. Selecione *Coletar registros*.
+
Você pode usar a página Coleta de logs para monitorar o progresso da coleta de arquivos de log para cada nó da grade.

+
Se você receber uma mensagem de erro sobre o tamanho do log, tente coletar logs por um período de tempo menor ou por menos nós.

. Se a coleta de logs falhar:
+
** Se a mensagem "Falha na coleta de logs" for exibida, você poderá tentar coletar logs novamente ou encerrar a sessão sem tentar novamente.
** Se a mensagem "Falha parcial na coleta de logs" for exibida, você poderá tentar novamente a coleta de logs, finalizar a sessão, baixar o arquivo de log parcial ou enviá-lo ao AutoSupport.


. Quando a coleta do arquivo de log estiver concluída:
+
** Selecione *Download* para baixar o `.tar.gz` arquivo.
** Selecione *Enviar para AutoSupport* para enviar o `.tar.gz` envie o arquivo para o suporte técnico.
+
O `.tar.gz` arquivo contém todos os arquivos de log de todos os nós da grade onde a coleta de log foi bem-sucedida.  O combinado `.tar.gz` arquivo contém um arquivo de log para cada nó da grade.

+
O assunto do pacote AutoSupport é `USER_TRIGGERED_SUPPORT_BUNDLE` .



. Selecione *Finish*.
+

CAUTION: O `.tar.gz` o arquivo é excluído quando você seleciona *Concluir*.  Certifique-se de baixar ou enviar o arquivo primeiro.


