---
permalink: monitor/collecting-log-files-and-system-data.html 
sidebar: sidebar 
keywords: how to collect system data, how to collect logs 
summary: Você pode recuperar arquivos de log do StorageGRID e dados do sistema, incluindo dados de configuração, e enviá-los para o suporte técnico. 
---
= Colete arquivos de log e dados do sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode recuperar arquivos de log do StorageGRID e dados do sistema, incluindo dados de configuração, e enviá-los para o suporte técnico.

.Antes de começar
* Você está conetado ao Gerenciador de Grade no nó Admin principal usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
* Você link:../admin/admin-group-permissions.html["permissões de acesso específicas"]tem .
* Você tem a senha de provisionamento.


.Sobre esta tarefa
Use o Gerenciador de Grade para coletar link:logs-files-reference.html["ficheiros de registo"], dados do sistema e dados de configuração de qualquer nó de grade para o período de tempo selecionado. Os dados são coletados e arquivados em um `.tar.gz` arquivo que você pode baixar para seu computador local ou enviar para o suporte técnico.

Opcionalmente, você pode alterar o destino dos logs de auditoria e enviar informações de auditoria para um servidor syslog externo. Os logs locais dos Registros de auditoria continuam a ser gerados e armazenados quando um servidor syslog externo é configurado. link:../monitor/configure-audit-messages.html["Configurar mensagens de auditoria e servidor syslog externo"]Consulte .

.Passos
. Selecione *SUPPORT* > *Tools* > *Logs*. Uma tabela de nós é exibida.
. Selecione os nós de grade para os quais você deseja coletar arquivos de log.
+
Você pode classificar por nome de nó, site e tipo de nó. As colunas tipo Site e nó contêm filtros para seleção por sites individuais e tipos de nó.

. Selecione *continuar*.
. Selecione o intervalo de data e hora dos dados a serem incluídos nos arquivos de log.
+
Se você selecionar um período de tempo muito longo ou coletar logs de todos os nós em uma grade grande, o arquivo de log pode se tornar muito grande para ser armazenado em um nó ou muito grande para ser coletado para o nó de administração principal para download. Se ocorrer um dos cenários, reinicie a coleção de registos com um conjunto de dados mais pequeno.

. Selecione os tipos de registos que pretende recolher.
+
** *Logs de aplicativos*: Logs específicos de aplicativos que o suporte técnico utiliza com mais frequência para solução de problemas. Os registos recolhidos são um subconjunto dos registos de aplicações disponíveis.
** *Logs de auditoria*: Logs contendo as mensagens de auditoria geradas durante a operação normal do sistema.
** *Rastreamento de rede*: Logs usados para depuração de rede.
** * Prometheus database*: Métricas de séries temporais dos serviços em todos os nós.


. Opcionalmente, use a caixa de texto * Notas* para inserir notas sobre os arquivos de log que você está reunindo.
+
Você pode usar essas notas para fornecer informações de suporte técnico sobre o problema que o levou a coletar os arquivos de log. Suas anotações são adicionadas a um arquivo `info.txt` chamado , juntamente com outras informações sobre a coleção de arquivos de log. O `info.txt` ficheiro é guardado no pacote de arquivo de registo.

. Na caixa de texto *frase-passe de aprovisionamento*, introduza a frase-passe de aprovisionamento para o seu sistema StorageGRID.
. Selecione *Collect logs*.
+
Você pode usar a página Logs para monitorar o progresso da coleção de arquivos de log para cada nó de grade.

+
Se você receber uma mensagem de erro sobre o tamanho do log, tente coletar logs por um período de tempo menor ou por menos nós.

. Se a coleta de log falhar:
+
** Se for apresentada uma mensagem "Log Collection failed" (Falha na coleção de registos), pode tentar novamente a coleção de registos ou terminar a sessão sem tentar novamente.
** Se for apresentada uma mensagem "Registo de recolha parcialmente falhou", pode tentar novamente a coleção de registos, terminar a sessão, transferir o ficheiro de registo parcial ou enviar o ficheiro de registo parcial para o AutoSupport.


. Quando a coleção de ficheiros de registo estiver concluída:
+
** Selecione *Download* para baixar o `.tar.gz` arquivo.
** Selecione *Enviar para AutoSupport* para enviar o `.tar.gz` arquivo para o suporte técnico.
+
O `.tar.gz` arquivo contém todos os arquivos de log de todos os nós de grade onde a coleção de log foi bem-sucedida. O arquivo combinado `.tar.gz` contém um arquivo de log para cada nó de grade.

+
O assunto do pacote AutoSupport é `USER_TRIGGERED_SUPPORT_BUNDLE`.



. Selecione *Finish*.
+

CAUTION: O `.tar.gz` arquivo é excluído quando você seleciona *Finish*. Certifique-se de baixar ou enviar o arquivo primeiro.


