---
permalink: monitor/managing-alerts.html 
sidebar: sidebar 
keywords: alert rules, managing alerts, alerts, alert notifications. edit alert rules 
summary: O sistema de alerta fornece uma interface fácil de usar para detetar, avaliar e resolver os problemas que podem ocorrer durante a operação do StorageGRID. 
---
= Gerenciar alertas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O sistema de alerta fornece uma interface fácil de usar para detetar, avaliar e resolver os problemas que podem ocorrer durante a operação do StorageGRID.

Os alertas são acionados em níveis de gravidade específicos quando as condições das regras de alerta são consideradas verdadeiras. Quando um alerta é acionado, ocorrem as seguintes ações:

* Um ícone de gravidade de alerta é mostrado no painel do Gerenciador de Grade e a contagem de Alertas atuais é incrementada.
* O alerta é exibido na página de resumo *Nós* e na guia *Nós* > *_nó_* > *Visão geral*.
* Uma notificação por e-mail é enviada, supondo que você tenha configurado um servidor SMTP e fornecido endereços de e-mail para os destinatários.
* Uma notificação SNMP (Simple Network Management Protocol) é enviada, supondo que você tenha configurado o agente SNMP do StorageGRID.


Você pode criar alertas personalizados, editar ou desativar alertas e gerenciar notificações de alerta.

Para saber mais:

* Reveja os vídeos:
+
.Visão geral dos alertas
video::2eea81c5-8323-417f-b0a0-b1ff008506c1[panopto]
+
.Alertas personalizados
video::54af90c4-9a38-4136-9621-b1ff008604a3[panopto]
* Consulte olink:alerts-reference.html["Referência de alertas"] .

