---
permalink: monitor/manually-triggering-autosupport-message.html 
sidebar: sidebar 
keywords: autosupport, triggering autosupport, manually triggering autosupport, autosupport triggers 
summary: Para ajudar o suporte técnico na solução de problemas com o sistema StorageGRID, você pode acionar manualmente um pacote AutoSupport a ser enviado. 
---
= Acione manualmente um pacote AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para ajudar o suporte técnico na solução de problemas com o sistema StorageGRID, você pode acionar manualmente um pacote AutoSupport a ser enviado.

.Antes de começar
* Você está conetado ao Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
* Você tem a permissão de acesso root ou outra configuração de grade.


.Passos
. Selecione *SUPPORT* > *Tools* > *AutoSupport*.
. Na guia *ações*, selecione *Enviar AutoSupport acionado pelo usuário*.
+
O StorageGRID tenta enviar um pacote AutoSupport para o site de suporte da NetApp. Se a tentativa for bem-sucedida, os valores *resultado mais recente* e *último tempo bem-sucedido* na guia *resultados* serão atualizados. Se houver um problema, o valor *resultado mais recente* será atualizado para "Falha" e o StorageGRID não tentará enviar o pacote AutoSupport novamente.

. Após 1 minuto, atualize a página AutoSupport no seu navegador para acessar os resultados mais recentes.



TIP: Além disso, você pode link:../monitor/collecting-log-files-and-system-data.html["colete arquivos de log mais extensos e dados do sistema"] e enviá-los para o site de suporte da NetApp.
