---
permalink: maintain/all-node-types-replacing-linux-node.html 
sidebar: sidebar 
keywords: replace linux node 
summary: Se uma falha exigir que você implante um ou mais novos hosts físicos ou virtuais ou reinstale o Linux em um host existente, implante e configure o host de substituição antes que você possa recuperar o nó da grade. Este procedimento é uma etapa do processo de recuperação do nó de grade para todos os tipos de nós de grade. 
---
= Substituir um nó Linux no StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se uma falha exigir que você implante um ou mais novos hosts físicos ou virtuais ou reinstale o Linux em um host existente, implante e configure o host de substituição antes que você possa recuperar o nó da grade. Este procedimento é uma etapa do processo de recuperação do nó de grade para todos os tipos de nós de grade.

"Linux" refere-se a uma implantação do Red Hat® Enterprise Linux® (RHEL), Ubuntu® ou Debian®.  Para obter uma lista de versões suportadas, consulte o https://imt.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade NetApp (IMT)"^] .

Este procedimento só é executado como uma etapa no processo de recuperação de nós de storage baseados em software, nós de administração primários ou não primários ou nós de gateway. As etapas são idênticas independentemente do tipo de nó de grade que você está recuperando.

Se mais de um nó de grid estiver hospedado em um host Linux físico ou virtual, você pode recuperar os nós de grid em qualquer ordem. No entanto, se o nó de administração primário estiver presente, você deve recuperá-lo primeiro para evitar que a recuperação de outros nós de grid seja interrompida enquanto eles tentam contatar o nó de administração primário. Se você não puder recuperar o nó de administração primário primeiro e um nó de administração não primário estiver disponível, você pode usar esse nó de administração não primário para recuperar os nós em qualquer ordem.
