---
permalink: maintain/checking-storage-state-after-recovering-sga.html 
sidebar: sidebar 
keywords: storagegrid, recovery, node recovery, storage state 
summary: Depois de recuperar um nó de armazenamento de dispositivo, você deve verificar se o estado desejado do nó de armazenamento de dispositivo está definido como on-line e garantir que o estado estará on-line por padrão sempre que o servidor nó de armazenamento for reiniciado. 
---
= Verifique o estado de armazenamento após recuperar o nó de armazenamento do dispositivo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de recuperar um nó de armazenamento de dispositivo, você deve verificar se o estado desejado do nó de armazenamento de dispositivo está definido como on-line e garantir que o estado estará on-line por padrão sempre que o servidor nó de armazenamento for reiniciado.

.Antes de começar
* Você está conetado ao Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
* O nó de armazenamento foi recuperado e a recuperação de dados está concluída.


.Passos
. Selecione *NODES* > *_Storage Node_* > *Tasks*.
. Se a lista suspensa *Storage State* estiver definida como somente leitura ou Offline, selecione *Online*.
. Selecione *Guardar*.

