---
permalink: maintain/checking-storage-state-after-recovering-storage-volumes.html 
sidebar: sidebar 
keywords: storagegrid, storage volume recovery, storage state, storage volume 
summary: Depois de recuperar volumes de armazenamento, você deve verificar se o estado desejado do nó de armazenamento está definido como on-line e garantir que o estado estará on-line por padrão sempre que o servidor nó de armazenamento for reiniciado. 
---
= Verifique o estado do armazenamento depois de recuperar volumes de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de recuperar volumes de armazenamento, você deve verificar se o estado desejado do nó de armazenamento está definido como on-line e garantir que o estado estará on-line por padrão sempre que o servidor nó de armazenamento for reiniciado.

.Antes de começar
* Você está conetado ao Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
* O nó de armazenamento foi recuperado e a recuperação de dados está concluída.


.Passos
. Selecione *Nós* > *_Nó de Armazenamento_* > *Tarefas*.
. Se a lista suspensa *Estado de armazenamento* estiver definida como Somente leitura ou Offline, selecione *Online*.
. Selecione *Guardar*.

