---
permalink: maintain/checking-data-repair-jobs.html 
sidebar: sidebar 
keywords: storagegrid, data repair 
summary: Antes de desativar um nó de grade, você deve confirmar que nenhum trabalho de reparo de dados está ativo. Se alguma reparação tiver falhado, tem de as reiniciar e permitir que sejam concluídas antes de executar o procedimento de desativação. 
---
= Verifique os trabalhos de reparo de dados no StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de desativar ou expandir um nó de grade, você deve confirmar se não há trabalhos de reparo de dados ativos.  Se algum reparo falhar, você deve reiniciá-lo e esperar que ele seja concluído antes de executar o procedimento de descomissionamento.

* Consultelink:../expand/index.html["Tipos de expansão"] para obter detalhes sobre como expandir um nó de grade.
* Utilize o Grid Manager para monitorar os processos de restauração em andamento e visualizar o histórico de restaurações. Consulte estes procedimentos:
+
** link:../maintain/restoring-object-data-to-storage-volume-for-appliance.html["Restaure os dados de objeto para o volume de storage do dispositivo"]
** link:../maintain/restoring-object-data-to-storage-volume-where-system-drive-is-intact.html["Restaure os dados de objetos para o volume de storage em que a unidade do sistema esteja intacta"]
** link:../maintain/restoring-object-data-to-storage-volume.html["Restaurar dados de objetos para o volume de storage (falha na unidade do sistema)"]



