---
permalink: maintain/convert-to-data-only-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, stop services, power down host, power off host 
summary: Para aumentar o desempenho, você pode converter nós de armazenamento não ADC mais lentos em nós de armazenamento somente de dados. 
---
= Converta um nó de storage em um nó somente de dados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para aumentar o desempenho, você pode converter nós de armazenamento não ADC mais lentos em nós de armazenamento somente de dados.

O uso de um nó de storage exclusivo para dados pode fazer sentido se seus nós de storage tiverem características de desempenho diferentes. Por exemplo, para aumentar potencialmente a performance, você pode ter nós de storage de disco giratório somente de dados e alta capacidade acompanhados por nós de storage de alta performance somente de metadados.

Além disso, você pode obter mais capacidade de metadados removendo nós de baixa RAM do Cassandra, o que aumenta o limite de capacidade de metadados por nó. link:../admin/managing-object-metadata-storage.html["Gerenciar o storage de metadados de objetos"]Consulte a .

Ao instalar nós somente dados, a grade deve conter o seguinte:

* Um mínimo de dois nós de storage combinados ou somente de dados por grade
* Pelo menos um nó de storage combinado ou somente de dados por local
* Um mínimo de três nós de storage combinados ou somente de metadados por local


.Antes de começar
* Você está conetado ao Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
* Você tem o link:admin-group-permissions.html["Permissão de manutenção ou acesso root"].
* O nó de armazenamento que você deseja converter não contém o serviço ADC ou você tem link:../maintain/move-adc-service.html["Movido o serviço ADC"] que outro nó.
* O nó de storage não é um nó somente de metadados ou um nó somente de dados.
* Há espaço de metadados suficiente em outros nós no local para acomodar os metadados que migrarão do nó de storage que você está convertendo.


.Sobre esta tarefa
Use este procedimento para converter um ou mais nós de storage combinados ou somente metadados que não contêm o serviço ADC em nós somente de dados. Os nós de storage devem estar no mesmo local.

Além de converter o nó de armazenamento, este procedimento descompacta o Cassandra do nó. Todos os metadados são migrados para nós de storage combinados ou somente de metadados. Dependendo da quantidade de metadados que precisa migrar, esse procedimento pode levar até vários dias por nó para ser concluído.


TIP: Geralmente, você pode converter até 10 nós de cada vez se o uso de metadados por nó for inferior a 1 TB. Se o uso de metadados por nó for superior a 1 TB, converta até 5 nós por procedimento.

.Passos
. Registre as IDs de nó dos nós de armazenamento não ADC que você deseja converter.
. Na parte superior do Gerenciador de Grade, selecione o ícone de ajuda e selecione *Documentação da API*.
. Selecione *vá para a documentação da API privada*.
. Selecione a `POST /private/convert-to-data-only-node/start` operação. link:../admin/using-grid-management-api.html#issue-api-requests["Emitir solicitações de API"]Consulte para obter mais informações.
+
Cada nó reiniciará durante o procedimento.

. Pode utilizar `GET /private/convert-to-data-only-node` para monitorizar o procedimento. Se ocorrerem erros, `POST /private/convert-to-data-only-node/retry` selecione para tentar novamente o procedimento.
. link:../maintain/downloading-recovery-package.html["Baixe um pacote de recuperação"] depois de concluir este procedimento.

