---
permalink: maintain/convert-to-data-only-node.html 
sidebar: sidebar 
keywords: storagegrid, convert node, data-only node 
summary: Para aumentar o desempenho, você pode converter nós de armazenamento não ADC mais lentos em nós de armazenamento somente de dados. 
---
= Converter um nó de armazenamento em um nó somente de dados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para aumentar o desempenho, você pode converter nós de armazenamento não ADC mais lentos em nós de armazenamento somente de dados.

O uso de um nó de storage exclusivo para dados pode fazer sentido se seus nós de storage tiverem características de desempenho diferentes. Por exemplo, para aumentar potencialmente a performance, você pode ter nós de storage de disco giratório somente de dados e alta capacidade acompanhados por nós de storage de alta performance somente de metadados.

Além disso, você pode obter mais capacidade de metadados removendo nós com pouca RAM do Cassandra, o que aumenta o limite de capacidade de metadados por nó. Consulte link:../admin/managing-object-metadata-storage.html["Gerenciar o storage de metadados de objetos"] .

Ao converter nós somente de dados, a grade deve conter no mínimo três nós de armazenamento combinados ou somente de metadados por site.

.Antes de começar
* Você está conetado ao Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
* Você tem o link:../admin/admin-group-permissions.html["Permissão de manutenção ou acesso root"].
* O nó de armazenamento que você deseja converter não contém o serviço ADC ou você temlink:../maintain/move-adc-service.html["moveu o serviço ADC"] para outro nó.
* O nó de armazenamento não é um nó somente de metadados ou um nó somente de dados.
* O nó de armazenamento que você deseja converter não contém o serviço ADC ou você temlink:../maintain/move-adc-service.html["moveu o serviço ADC"] para outro nó.
* Há espaço de metadados suficiente em outros nós no site (ou você temlink:../expand/index.html["expandiu sua grade"] ) para acomodar os metadados que migrarão do nó de armazenamento que você está convertendo.
+
[CAUTION]
====
** Se os metadados que migram para outros nós no mesmo site excederem o tamanho dolink:../admin/managing-object-metadata-storage.html["espaço reservado de metadados"] , a rede ficará instável.
** Depois de iniciar a conversão, você não poderá expandir a grade.


====


.Sobre esta tarefa
Use este procedimento para converter um ou mais nós de armazenamento combinados que não contêm o serviço ADC em nós somente de dados.

Além de converter o nó de armazenamento, este procedimento descomissiona o Cassandra do nó.  Todos os metadados migrarão para nós de armazenamento combinados ou somente de metadados.  Dependendo da quantidade de metadados que precisam ser migrados, esse procedimento pode levar vários dias por nó para ser concluído.


TIP: Geralmente, você pode converter até 10 nós por vez se o uso de metadados por nó for menor que 1 TB.  Se o uso de metadados por nó for maior que 1 TB, converta até 5 nós por procedimento.

.Passos
. Registre os IDs dos nós de armazenamento não ADC que você deseja converter.
. Na parte superior do Gerenciador de Grade, selecione o ícone de ajuda e selecione *Documentação da API*.
. Selecione *vá para a documentação da API privada*.
. Selecione o `POST /private/convert-to-data-only-node/start` operação. Consulte link:../admin/using-grid-management-api.html#issue-api-requests["Emitir solicitações de API"] para maiores informações.
+
Cada nó será reinicializado durante o procedimento.

. Você pode usar `GET /private/convert-to-data-only-node` para monitorar o procedimento.  Se ocorrerem erros, selecione `POST /private/convert-to-data-only-node/retry` para tentar novamente o procedimento.
. link:../maintain/downloading-recovery-package.html["Baixe um pacote de recuperação"]após concluir este procedimento.

