---
permalink: maintain/decommission-procedure.html 
sidebar: sidebar 
keywords: how to decommission 
summary: Você pode executar um procedimento de desativação para remover permanentemente nós de grade ou um site inteiro do sistema StorageGRID. 
---
= Desativar o nó ou o local
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode executar um procedimento de desativação para remover permanentemente nós de grade ou um site inteiro do sistema StorageGRID.

Para remover um nó de grade ou um local, execute um dos seguintes procedimentos de desativação:

* Execute um link:grid-node-decommissioning.html["desativação do nó de grade"] para remover um ou mais nós, que podem estar em um ou mais locais. Os nós removidos podem estar online e conetados ao sistema StorageGRID, ou podem estar offline e desconetados.
* Execute um link:considerations-for-removing-site.html["desativação do site"] para remover um site. Você executa um *desativação do site conetado* se todos os nós estiverem conetados ao StorageGRID. Você executa um *desativação do site desconetada* se todos os nós estiverem desconetados do StorageGRID. Se o site contiver uma mistura de nós conetados e desconetados, você deverá colocar todos os nós off-line novamente.
+

CAUTION: Antes de executar uma desativação desconetada do site, entre em Contato com o representante da sua conta do NetApp. O NetApp revisará seus requisitos antes de ativar todas as etapas no assistente do site de desintegração. Você não deve tentar uma desativação de site desconetada se você acredita que pode ser possível recuperar o site ou recuperar dados de objeto do site.



Antes de desativar um nó de grade, você deve confirmar se não há trabalhos de reparo de dados ativos.  Se algum reparo falhar, você deve reiniciá-lo e esperar que ele seja concluído antes de executar o procedimento de descomissionamento. Consulte link:../maintain/checking-data-repair-jobs.html["Verifique os trabalhos de reparação de dados"] .
