---
permalink: maintain/gathering-required-materials-for-grid-node-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recovery, grid node recovery, node recovery 
summary: Antes de executar os procedimentos de manutenção, você deve garantir que você tenha os materiais necessários para recuperar um nó de grade com falha. 
---
= Reúna os materiais necessários para a recuperação do nó da grade
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de executar os procedimentos de manutenção, você deve garantir que você tenha os materiais necessários para recuperar um nó de grade com falha.

[cols="1a,2a"]
|===
| Item | Notas 


 a| 
Arquivo de instalação do StorageGRID
 a| 
Se você precisa recuperar um nó de grade, você precisa <<download-and-extract-install-files-recover,Transfira os ficheiros de instalação do StorageGRID>> fazer isso para sua plataforma.

*Observação:* você não precisa baixar arquivos se estiver recuperando volumes de armazenamento com falha em um nó de armazenamento.



 a| 
Serviço de laptop
 a| 
O computador portátil de serviço tem de ter o seguinte:

* Porta de rede
* Cliente SSH (por exemplo, PuTTY)
* link:../admin/web-browser-requirements.html["Navegador da Web suportado"]




 a| 
Arquivo de pacote de recuperação `.zip`
 a| 
Obtenha uma cópia do arquivo de pacote de recuperação mais recente `.zip`:
`sgws-recovery-package-_id-revision_.zip`

O conteúdo do `.zip` arquivo é atualizado sempre que o sistema é modificado. Você é direcionado para armazenar a versão mais recente do pacote de recuperação em um local seguro depois de fazer tais alterações. Use a cópia mais recente para recuperar de falhas na grade.

Se o nó Admin principal estiver operando normalmente, você poderá fazer o download do pacote de recuperação do Gerenciador de Grade. Selecione *MAINTENANCE* > *System* > *Recovery package*.

Se você não puder acessar o Gerenciador de Grade, poderá encontrar cópias criptografadas do pacote de recuperação em alguns nós de armazenamento que contêm o serviço ADC. Em cada nó de armazenamento, examine este local para o pacote de recuperação: `/var/local/install/sgws-recovery-package-_grid-id_-_revision_.zip.gpg` Use o pacote de recuperação com o número de revisão mais alto.



 a| 
`Passwords.txt` ficheiro
 a| 
Contém as senhas necessárias para acessar os nós de grade na linha de comando. Incluído no pacote de recuperação.



 a| 
Frase-passe do aprovisionamento
 a| 
A frase-passe é criada e documentada quando o sistema StorageGRID é instalado pela primeira vez. A senha de provisionamento não está no `Passwords.txt` arquivo.



 a| 
Documentação atual para a sua plataforma
 a| 
Vá para o site do fornecedor da plataforma para obter documentação.

Para obter as versões suportadas atuais da sua plataforma, consulte o https://imt.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade do NetApp"^].

|===


== Baixe e extraia arquivos de instalação do StorageGRID

.[[download-and-extract-install-files-recover]]
Baixe o software e extraia os arquivos, a menos que você seja link:recovering-from-storage-node-failures.html["Recuperando volumes de storage com falha em um nó de storage"].

Você deve usar a versão do StorageGRID que está atualmente em execução na grade.

.Passos
. Determine qual versão do software está instalada atualmente. Na parte superior do Gerenciador de Grade, selecione o ícone de ajuda e selecione *sobre*.
. Vá para https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Página de downloads do NetApp para StorageGRID"^] .
. Selecione a versão do StorageGRID que está atualmente em execução na grade.
+
As versões do software StorageGRID têm este formato: `11.x.y`.

. Inicie sessão com o nome de utilizador e a palavra-passe da sua conta NetApp.
. Leia o Contrato de Licença de Utilizador final, selecione a caixa de verificação e, em seguida, selecione *Accept & continue*.
. Na coluna *Instalar StorageGRID* da página de download, selecione o `.tgz` arquivo ou `.zip` para sua plataforma.
+
A versão apresentada no ficheiro de arquivo de instalação tem de corresponder à versão do software atualmente instalado.

+
Use o `.zip` arquivo se estiver executando o Windows.

+
[cols="1a,2a"]
|===
| Plataforma | Arquivo de instalação 


 a| 
Red Hat Enterprise Linux
| `StorageGRID-Webscale-_version_-RPM-_uniqueID_.zip` 
`StorageGRID-Webscale-_version_-RPM-_uniqueID_.tgz` 


 a| 
Ubuntu ou Debian ou appliances
| `StorageGRID-Webscale-_version_-DEB-_uniqueID_.zip` 
`StorageGRID-Webscale-_version_-DEB-_uniqueID_.tgz` 


 a| 
VMware
| `StorageGRID-Webscale-_version_-VMware-_uniqueID_.zip` 
`StorageGRID-Webscale-_version_-VMware-_uniqueID_.tgz` 
|===
. Transfira e extraia o ficheiro de arquivo.
. Siga o passo apropriado para sua plataforma escolher os arquivos que você precisa, com base em sua plataforma e quais nós de grade você precisa recuperar.
+
Os caminhos listados na etapa para cada plataforma são relativos ao diretório de nível superior instalado pelo arquivo de arquivo.

. Se estiver a recuperar um link:../rhel/index.html["Sistema Red Hat Enterprise Linux"], selecione os ficheiros apropriados.


[cols="1a,1a"]
|===
| Caminho e nome do arquivo | Descrição 


| ./rpms/README  a| 
Um arquivo de texto que descreve todos os arquivos contidos no arquivo de download do StorageGRID.



| ./rpms/NLF000000.txt  a| 
Uma licença gratuita que não fornece qualquer direito de suporte para o produto.



| ./rpms/StorageGRID-Webscale-Images-_version_-SHA.rpm  a| 
Pacote RPM para instalar as imagens do nó StorageGRID em seus hosts RHEL.



| ./rpms/StorageGRID-Webscale-Service-_version_-SHA.rpm  a| 
Pacote RPM para instalar o serviço de host StorageGRID em seus hosts RHEL.



| Ferramenta de script de implantação | Descrição 


| ./rpms/configure-StorageGRID.py  a| 
Um script Python usado para automatizar a configuração de um sistema StorageGRID.



| ./rpms/configure-sga.py  a| 
Um script Python usado para automatizar a configuração de dispositivos StorageGRID.



| ./rpms/configure-StorageGRID.sample.json  a| 
Um exemplo de arquivo de configuração para uso com o `configure-storagegrid.py` script.



| ./rpms/StorageGRID-ssoauth.py  a| 
Um exemplo de script Python que você pode usar para fazer login na API de Gerenciamento de Grade quando o logon único estiver ativado. Você também pode usar este script para integração Ping federate.



| ./rpms/configure-StorageGRID.blank.json  a| 
Um arquivo de configuração em branco para uso com o `configure-storagegrid.py` script.



| ./rpms/extras/ansible  a| 
Exemplo de função do Ansible e manual de estratégia para configurar hosts do RHEL para implantação de contêineres do StorageGRID. Você pode personalizar a função ou o manual de estratégia conforme necessário.



| ./rpms/StorageGRID-ssoauth-azure.py  a| 
Um exemplo de script Python que você pode usar para fazer login na API de Gerenciamento de Grade quando o logon único (SSO) está habilitado usando o ative Directory ou Ping federate.



| ./rpms/StorageGRID-ssoauth-azure.js  a| 
Um script auxiliar chamado pelo script Python complementar `storagegrid-ssoauth-azure.py` para executar interações SSO com o Azure.



| ./rpms/extras/api-schemas  a| 
Esquemas de API para StorageGRID.

*Nota*: Antes de executar uma atualização, você pode usar esses esquemas para confirmar que qualquer código que você tenha escrito para usar APIs de gerenciamento do StorageGRID será compatível com a nova versão do StorageGRID se você não tiver um ambiente StorageGRID que não seja de produção para teste de compatibilidade de atualização.

|===
. Se estiver a recuperar um link:../ubuntu/index.html["Sistema Ubuntu ou Debian"], selecione os ficheiros apropriados.


[cols="1a,1a"]
|===
| Caminho e nome do arquivo | Descrição 


| ./debs/README  a| 
Um arquivo de texto que descreve todos os arquivos contidos no arquivo de download do StorageGRID.



| ./debs/NLF000000.txt  a| 
Um arquivo de licença do NetApp que não é de produção que pode ser usado para testes e implantações de prova de conceito.



| ./debs/StorageGRID-webscale-images-version-SHA.deb  a| 
Pacote DEB para instalar as imagens do nó StorageGRID em hosts Ubuntu ou Debian.



| ./debs/StorageGRID-webscale-images-version-SHA.deb.md5  a| 
MD5 checksum para o arquivo `/debs/storagegrid-webscale-images-version-SHA.deb`.



| ./debs/StorageGRID-webscale-service-version-SHA.deb  a| 
Pacote DEB para instalar o serviço host StorageGRID em hosts Ubuntu ou Debian.



| Ferramenta de script de implantação | Descrição 


| ./debs/configure-StorageGRID.py  a| 
Um script Python usado para automatizar a configuração de um sistema StorageGRID.



| ./debs/configure-sga.py  a| 
Um script Python usado para automatizar a configuração de dispositivos StorageGRID.



| ./debs/StorageGRID-ssoauth.py  a| 
Um exemplo de script Python que você pode usar para fazer login na API de Gerenciamento de Grade quando o logon único estiver ativado. Você também pode usar este script para integração Ping federate.



| ./debs/configure-StorageGRID.sample.json  a| 
Um exemplo de arquivo de configuração para uso com o `configure-storagegrid.py` script.



| ./debs/configure-StorageGRID.blank.json  a| 
Um arquivo de configuração em branco para uso com o `configure-storagegrid.py` script.



| ./debs/extras/ansible  a| 
Exemplo Ansible role e playbook para configurar hosts Ubuntu ou Debian para a implantação de contentores StorageGRID. Você pode personalizar a função ou o manual de estratégia conforme necessário.



| ./debs/StorageGRID-ssoauth-azure.py  a| 
Um exemplo de script Python que você pode usar para fazer login na API de Gerenciamento de Grade quando o logon único (SSO) está habilitado usando o ative Directory ou Ping federate.



| ./debs/StorageGRID-ssoauth-azure.js  a| 
Um script auxiliar chamado pelo script Python complementar `storagegrid-ssoauth-azure.py` para executar interações SSO com o Azure.



| ./debs/extras/api-schemas  a| 
Esquemas de API para StorageGRID.

*Nota*: Antes de executar uma atualização, você pode usar esses esquemas para confirmar que qualquer código que você tenha escrito para usar APIs de gerenciamento do StorageGRID será compatível com a nova versão do StorageGRID se você não tiver um ambiente StorageGRID que não seja de produção para teste de compatibilidade de atualização.

|===
. Se estiver a recuperar um link:../vmware/index.html["Sistema VMware"], selecione os ficheiros apropriados.


[cols="1a,1a"]
|===
| Caminho e nome do arquivo | Descrição 


| ./vSphere/README  a| 
Um arquivo de texto que descreve todos os arquivos contidos no arquivo de download do StorageGRID.



| ./vSphere/NLF000000.txt  a| 
Uma licença gratuita que não fornece qualquer direito de suporte para o produto.



| ./vsphere/NetApp-SG-version-SHA.vmdk  a| 
O arquivo de disco da máquina virtual que é usado como um modelo para criar máquinas virtuais de nó de grade.



| ./vsphere/vsphere-primary-admin.ovf ./vsphere/vsphere-primary-admin.mf  a| 
O arquivo de modelo Open Virtualization Format (`.ovf`) e o arquivo de manifesto (`.mf`) para implantar o nó de administração principal.



| ./vsphere/vsphere-non-primary-admin.ovf ./vsphere/vsphere-non-primary-admin.mf  a| 
O arquivo de (`.ovf`modelo ) e o arquivo de manifesto (`.mf`) para implantar nós de administração não primários.



| ./vsphere/vsphere-gateway.ovf ./vsphere/vsphere-gateway.mf  a| 
O arquivo de (`.ovf`modelo ) e o arquivo de manifesto (`.mf`) para implantar nós do Gateway.



| ./vsphere/vsphere-storage.ovf ./vsphere/vsphere-storage.mf  a| 
O arquivo de (`.ovf`modelo ) e o arquivo de manifesto (`.mf`) para implantar nós de storage baseados em máquina virtual.



| Ferramenta de script de implantação | Descrição 


| ./vsphere/deploy-vsphere-ovftool.sh  a| 
Um script de shell Bash usado para automatizar a implantação de nós de grade virtual.



| ./vsphere/deploy-vsphere-ovftool-sample.ini  a| 
Um exemplo de arquivo de configuração para uso com o `deploy-vsphere-ovftool.sh` script.



| ./vsphere/configure-StorageGRID.py  a| 
Um script Python usado para automatizar a configuração de um sistema StorageGRID.



| ./vsphere/configure-sga.py  a| 
Um script Python usado para automatizar a configuração de dispositivos StorageGRID.



| ./vsphere/StorageGRID-ssoauth.py  a| 
Um exemplo de script Python que você pode usar para entrar na API de Gerenciamento de Grade quando o logon único (SSO) está ativado. Você também pode usar este script para integração Ping federate.



| ./vsphere/configure-StorageGRID.sample.json  a| 
Um exemplo de arquivo de configuração para uso com o `configure-storagegrid.py` script.



| ./vsphere/configure-StorageGRID.blank.json  a| 
Um arquivo de configuração em branco para uso com o `configure-storagegrid.py` script.



| ./vsphere/StorageGRID-ssoauth-azure.py  a| 
Um exemplo de script Python que você pode usar para fazer login na API de Gerenciamento de Grade quando o logon único (SSO) está habilitado usando o ative Directory ou Ping federate.



| ./vsphere/StorageGRID-ssoauth-azure.js  a| 
Um script auxiliar chamado pelo script Python complementar `storagegrid-ssoauth-azure.py` para executar interações SSO com o Azure.



| ./vsphere/extras/api-schemas  a| 
Esquemas de API para StorageGRID.

*Nota*: Antes de executar uma atualização, você pode usar esses esquemas para confirmar que qualquer código que você tenha escrito para usar APIs de gerenciamento do StorageGRID será compatível com a nova versão do StorageGRID se você não tiver um ambiente StorageGRID que não seja de produção para teste de compatibilidade de atualização.

|===
. Se estiver a recuperar um sistema baseado no StorageGRID Appliance, selecione os ficheiros apropriados.


[cols="1a,1a"]
|===
| Caminho e nome do arquivo | Descrição 


| ./debs/StorageGRID-webscale-images-version-SHA.deb  a| 
DEB pacote para instalar as imagens do nó StorageGRID em seus dispositivos.



| ./debs/StorageGRID-webscale-images-version-SHA.deb.md5  a| 
MD5 checksum para o arquivo `/debs/storagegridwebscale-
images-version-SHA.deb`.

|===

NOTE: Para a instalação do dispositivo, esses arquivos só são necessários se você precisar evitar o tráfego de rede. O dispositivo pode baixar os arquivos necessários do nó de administração principal.
