---
permalink: maintain/grid-node-procedures.html 
sidebar: sidebar 
keywords: storagegrid, grid node procedure 
summary: Talvez seja necessário executar procedimentos de manutenção relacionados a nós de grade ou serviços de nós específicos. 
---
= Procedimentos de manutenção do nó
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Talvez seja necessário executar procedimentos de manutenção relacionados a nós de grade ou serviços de nós específicos.

Procedimentos do Server Manager:: O Gerenciador de servidores é executado em cada nó de grade para supervisionar o início e a parada dos serviços e garantir que os serviços se juntem e saiam do sistema StorageGRID. O Gerenciador de servidores também monitora os serviços em cada nó de grade e tentará reiniciar automaticamente quaisquer serviços que relatem falhas.
+
--
Para executar os procedimentos do Gerenciador de servidores, você geralmente precisa acessar a linha de comando do nó.


NOTE: Você deve acessar o Server Manager somente se o suporte técnico o tiver direcionado para isso.


NOTE: Você deve fechar a sessão de shell de comando atual e fazer logout depois de terminar com o Gerenciador de servidor. Introduza: `exit`

--
Procedimentos de reinicialização, desligamento e energia do nó:: Use esses procedimentos para reinicializar um ou mais nós, desligar e reiniciar nós ou desligar nós e ligá-los novamente.
Procedimentos de remapeamento de portas:: Você pode usar os procedimentos de remapeamento de portas para remover os remapas de portas de um nó, por exemplo, se quiser configurar um ponto de extremidade do balanceador de carga usando uma porta que foi anteriormente remapeada.

