---
permalink: maintain/monitor-repairs.html 
sidebar: sidebar 
keywords: restore replicated data, restore erasure-coded data, recover appliance storage node, recover storage volume 
summary: 'Você pode monitorar o status dos trabalhos de reparo usando o `repair-data` script da linha de comando.' 
---
= Monitorizar trabalhos de reparação de dados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode monitorar o status dos trabalhos de reparo usando o `repair-data` script da linha de comando.

Estas incluem tarefas iniciadas manualmente ou trabalhos iniciados automaticamente pelo StorageGRID como parte de um procedimento de desativação.


NOTE: Em vez disso, se estiver a executar trabalhos de restauro de volumelink:../maintain/restoring-volume.html["Monitore o progresso e visualize um histórico desses trabalhos no Gerenciador de Grade"].

Monitore o status das `repair-data` tarefas com base se você usa *dados replicados*, *dados codificados por apagamento (EC)* ou ambos.

[role="tabbed-block"]
====
.Dados replicados
--
* Para obter uma conclusão percentual estimada para o reparo replicado, adicione a `show-replicated-repair-status` opção ao comando repair-data.
+
`repair-data show-replicated-repair-status`

* Para determinar se as reparações estão concluídas:
+
.. Selecione *NODES* > *_Storage Node a ser reparado_* > *ILM*.
.. Reveja os atributos na secção avaliação. Quando os reparos estiverem concluídos, o atributo *aguardando - All* indica objetos 0D.


* Para monitorizar a reparação em mais detalhes:
+
.. Selecione *SUPPORT* > *Tools* > *Grid topology*.
.. Selecione *_Grid_* > *_Storage Node a ser reparado_* > *LDR* > *Data Store*.
.. Use uma combinação dos seguintes atributos para determinar, assim como possível, se as reparações replicadas estão concluídas.
+

NOTE: As inconsistências do Cassandra podem estar presentes e as reparações falhadas não são rastreadas.

+
*** * Tentativas de reparos (XRPA)*: Use este atributo para rastrear o progresso de reparos replicados. Esse atributo aumenta cada vez que um nó de storage tenta reparar um objeto de alto risco. Quando este atributo não aumenta por um período superior ao período de digitalização atual (fornecido pelo atributo *período de digitalização -- estimado*), significa que a digitalização ILM não encontrou objetos de alto risco que precisam ser reparados em nenhum nó.
+

NOTE: Objetos de alto risco são objetos que correm o risco de serem completamente perdidos. Isso não inclui objetos que não satisfazem sua configuração ILM.

*** *Período de digitalização -- estimado (XSCM)*: Use este atributo para estimar quando uma alteração de política será aplicada a objetos ingeridos anteriormente. Se o atributo *Repairs tented* não aumentar durante um período superior ao período de digitalização atual, é provável que sejam efetuadas reparações replicadas. Note que o período de digitalização pode mudar. O atributo *período de digitalização -- estimado (XSCM)* aplica-se a toda a grade e é o máximo de todos os períodos de varredura de nós. Você pode consultar o histórico de atributos *período de digitalização -- estimado* para a grade para determinar um período de tempo apropriado.






--
.Dados codificados por apagamento (EC)
--
Para monitorar o reparo de dados codificados por apagamento e tentar novamente quaisquer solicitações que possam ter falhado:

. Determinar o status dos reparos de dados codificados por apagamento:
+
** Selecione *SUPPORT* > *Tools* > *Metrics* para visualizar o tempo estimado para conclusão e a porcentagem de conclusão do trabalho atual. Em seguida, selecione *EC Overview* na seção Grafana. Veja os painéis *Grid EC Job tempo estimado para conclusão* e *Grid EC Job percentage Completed*.
** Use este comando para ver o status de uma operação específica `repair-data`:
+
`repair-data show-ec-repair-status --repair-id repair ID`

** Utilize este comando para listar todas as reparações:
+
`repair-data show-ec-repair-status`

+
A saída lista informações, `repair ID`incluindo , para todas as reparações anteriores e atualmente em execução.



. Se a saída mostrar que a operação de reparo falhou, use a `--repair-id` opção para tentar novamente a reparação.
+
Este comando tenta novamente um reparo de nó com falha, usando a ID de reparo 6949309319275667690:

+
`repair-data start-ec-node-repair --repair-id 6949309319275667690`

+
Este comando tenta novamente uma reparação de volume com falha, utilizando a ID de reparação 6949309319275667690:

+
`repair-data start-ec-volume-repair --repair-id 6949309319275667690`



--
====