---
permalink: maintain/monitor-repairs.html 
sidebar: sidebar 
keywords: restore replicated data, restore erasure-coded data, recover appliance storage node, recover storage volume 
summary: 'Você pode monitorar o status dos trabalhos de reparo usando o `repair-data` script da linha de comando.' 
---
= Monitorizar trabalhos de reparação de dados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode monitorar o status dos trabalhos de reparo usando o `repair-data` script da linha de comando.

Estas incluem tarefas iniciadas manualmente ou trabalhos iniciados automaticamente pelo StorageGRID como parte de um procedimento de desativação.


NOTE: Em vez disso, se estiver a executar trabalhos de restauro de volumelink:../maintain/restoring-volume.html["Monitore o progresso e visualize um histórico desses trabalhos no Gerenciador de Grade"].

Monitore o status das `repair-data` tarefas com base se você usa *dados replicados*, *dados codificados por apagamento (EC)* ou ambos.

[role="tabbed-block"]
====
.Dados replicados
--
* Para obter uma conclusão percentual estimada para o reparo replicado, adicione a `show-replicated-repair-status` opção ao comando repair-data.
+
`repair-data show-replicated-repair-status`

* Para determinar se as reparações estão concluídas:
+
.. Selecione *NODES* > *_Storage Node a ser reparado_* > *ILM*.
.. Reveja os atributos na secção avaliação. Quando os reparos estiverem concluídos, o atributo *aguardando - All* indica objetos 0D.


* Para monitorizar a reparação em mais detalhes:
+
.. Selecione *NODES*.
.. Selecione *_grid name_* > *ILM*.
.. Posicione o cursor sobre o gráfico de fila ILM para ver o valor do atributo *taxa de digitalização (objetos/seg)*, que é a taxa na qual os objetos na grade são digitalizados e enfileirados para ILM.
.. Na seção fila de ILM, observe os seguintes atributos:
+
*** *Período de digitalização - estimado*: O tempo estimado para concluir uma varredura ILM completa de todos os objetos.
+
Uma verificação completa não garante que o ILM tenha sido aplicado a todos os objetos.

*** *Tentativas de reparação*: O número total de operações de reparação de objetos para dados replicados que foram tentados. Essa contagem aumenta cada vez que um nó de storage tenta reparar um objeto de alto risco. As reparações ILM de alto risco são priorizadas se a grelha ficar ocupada.
+
O mesmo reparo de objeto pode aumentar novamente se a replicação falhar após o reparo. Esses atributos podem ser úteis quando você está monitorando o progresso da recuperação de volume do nó de armazenamento. Se o número de reparações tentadas tiver parado de aumentar e tiver sido concluído um exame completo, a reparação provavelmente foi concluída.



.. Alternativamente, envie uma consulta Prometheus para `storagegrid_ilm_scan_period_estimated_minutes` e `storagegrid_ilm_repairs_attempted`.




--
.Dados codificados por apagamento (EC)
--
Para monitorar o reparo de dados codificados por apagamento e tentar novamente quaisquer solicitações que possam ter falhado:

. Determinar o status dos reparos de dados codificados por apagamento:
+
** Selecione *SUPPORT* > *Tools* > *Metrics* para visualizar o tempo estimado para conclusão e a porcentagem de conclusão do trabalho atual. Em seguida, selecione *EC Overview* na seção Grafana. Veja os painéis *Grid EC Job tempo estimado para conclusão* e *Grid EC Job percentage Completed*.
** Use este comando para ver o status de uma operação específica `repair-data`:
+
`repair-data show-ec-repair-status --repair-id repair ID`

** Utilize este comando para listar todas as reparações:
+
`repair-data show-ec-repair-status`

+
A saída lista informações, `repair ID`incluindo , para todas as reparações anteriores e atualmente em execução.



. Se a saída mostrar que a operação de reparo falhou, use a `--repair-id` opção para tentar novamente a reparação.
+
Este comando tenta novamente um reparo de nó com falha, usando a ID de reparo 6949309319275667690:

+
`repair-data start-ec-node-repair --repair-id 6949309319275667690`

+
Este comando tenta novamente uma reparação de volume com falha, utilizando a ID de reparação 6949309319275667690:

+
`repair-data start-ec-volume-repair --repair-id 6949309319275667690`



--
====