---
permalink: maintain/move-adc-service.html 
sidebar: sidebar 
keywords: storagegrid, move adc, adc quorum 
summary: Você pode mover o serviço ADC para outro nó de armazenamento no mesmo site. 
---
= Mova o serviço ADC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode mover o serviço ADC para outro nó de armazenamento no mesmo site.

.Antes de começar
* Você está conetado ao Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
* Você link:admin-group-permissions.html["Permissão de manutenção ou acesso root"]tem .
* O nó de origem contém o serviço ADC.
* O nó de destino não contém o serviço ADC.
* O nó de destino é apenas um nó combinado (metadados e dados de objetos).
* O nó de origem e o nó de destino estão no mesmo local.


.Sobre esta tarefa
Use o procedimento mover ADC quando quiser:

* Desativar um nó de armazenamento que contém o serviço ADC
* Converta um nó ADC em um nó somente de dados
* Adicione um nó para executar tarefas relacionadas ao ADC


Quando você deseja desativar um nó de armazenamento ou link:../maintain/convert-to-data-only-node.html["Converta um nó de storage em um nó somente de dados"], primeiro você pode precisar usar o procedimento mover ADC. Você precisará garantir que o link:../maintain/understanding-adc-service-quorum.html["O quórum de ADC é mantido"].

Este procedimento move os serviços ADC, IDNT, ACCT e RSM de um nó de armazenamento para outro no mesmo local. Os serviços RSM e ACCT dependem do serviço ADC, pelo que se movem automaticamente quando o serviço ADC se move.

.Passos
. Registre as IDs de nó dos nós de origem e destino.
+
Na API de Gerenciamento de Grade, o ID do nó de origem é `sourceNodeId` chamado de . O ID do nó de destino é `targetNodeId` chamado de .

. Na parte superior do Gerenciador de Grade, selecione o ícone de ajuda e selecione *Documentação da API*.
. Selecione *vá para a documentação da API privada*.
. Selecione a `POST /private/move-adc/start` operação. link:../admin/using-grid-management-api.html#issue-api-requests["Emitir solicitações de API"]Consulte para obter mais informações.
+
Cada nó reiniciará durante o procedimento.

. Pode utilizar `GET /private/move-adc` para monitorizar o procedimento. Se ocorrerem erros, `POST /private/move-adc/retry` selecione para tentar novamente o procedimento.
. link:../maintain/downloading-recovery-package.html["Baixe um pacote de recuperação"] depois de concluir este procedimento.

