---
permalink: maintain/powering-off-and-on-all-nodes-in-grid.html 
sidebar: sidebar 
keywords: storagegrid, recover, power nodes, power on nodes, power off nodes, power down nodes 
summary: Talvez seja necessário desligar todo o sistema StorageGRID, por exemplo, se você estiver movendo um data center. Estas etapas fornecem uma visão geral de alto nível da sequência recomendada para executar um desligamento controlado e inicialização. 
---
= Desligue e ligue todos os nós na rede
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Talvez seja necessário desligar todo o sistema StorageGRID, por exemplo, se você estiver movendo um data center. Estas etapas fornecem uma visão geral de alto nível da sequência recomendada para executar um desligamento controlado e inicialização.

Quando você desliga todos os nós em um local ou grade, não será possível acessar objetos ingeridos enquanto os nós de storage estiverem offline.



== Pare os serviços e encerre os nós da grade

Antes de poder desligar um sistema StorageGRID, você deve parar todos os serviços em execução em cada nó de grade e, em seguida, desligar todas as máquinas virtuais VMware, mecanismos de contêiner e dispositivos StorageGRID.

.Sobre esta tarefa
Pare primeiro os serviços em nós de administração e nós de gateway e, em seguida, pare os serviços em nós de storage.

Essa abordagem permite que você use o nó de administração principal para monitorar o status dos outros nós de grade pelo maior tempo possível.


NOTE: Se um único host incluir mais de um nó de grade, não encerre o host até que você tenha parado todos os nós nesse host. Se o host incluir o nó Admin principal, encerre esse host por último.


NOTE: Se necessário, você pode link:linux-migrating-grid-node-to-new-host.html["Migre nós de um host Linux para outro"]executar a manutenção do host sem afetar a funcionalidade ou a disponibilidade de sua grade.

.Passos
. O acesso SSH externo é bloqueado por padrão.  Se necessário,link:../admin/manage-external-ssh-access.html["permitir acesso temporariamente"] .
. Impedir que todas as aplicações cliente acedam à grelha.
. [[log_in_to_gn]]Faça login em cada nó de gateway:
+
.. Introduza o seguinte comando: `ssh admin@_grid_node_IP_`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
.. Digite o seguinte comando para mudar para root: `su -`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.


+
Quando você estiver conetado como root, o prompt mudará de `$` para `#`.

. [[stop_all_services]]pare todos os serviços em execução no nó: `service servermanager stop`
+
Os serviços podem levar até 15 minutos para serem encerrados, e você pode querer fazer login no sistema remotamente para monitorar o processo de desligamento.

. Repita as duas etapas anteriores para interromper os serviços em todos os nós de storage e nós de administração não primários.
+
Você pode parar os serviços nesses nós em qualquer ordem.

+

NOTE: Se você emitir o `service servermanager stop` comando para parar os serviços em um nó de armazenamento de dispositivo, será necessário desligar o dispositivo para reiniciar o nó.

. Para o nó de administração principal, repita as etapas para <<log_in_to_gn,iniciar sessão no nó>> e <<stop_all_services,parando todos os serviços no nó>>.
. Para nós que estão sendo executados em hosts Linux:
+
.. Faça login no sistema operacional host.
.. Pare o nó: `storagegrid node stop`
.. Encerre o sistema operacional do host.


. Para nós que estão sendo executados em máquinas virtuais VMware e para nós de storage do dispositivo, execute o comando shutdown: `shutdown -h now`
+
Execute esta etapa independentemente do resultado do `service servermanager stop` comando.

+
Para o dispositivo, esse comando desliga o controlador de computação, mas o dispositivo ainda está ligado. Você deve concluir o próximo passo.

. Se você tiver nós de dispositivo, siga as etapas para o seu dispositivo.
+
[role="tabbed-block"]
====
.SG110 ou SG1100
--
.. Desligue a alimentação do aparelho.
.. Aguarde até que o LED azul de alimentação se desligue.


--
.SG100 ou SG1000
--
.. Desligue a alimentação do aparelho.
.. Aguarde até que o LED azul de alimentação se desligue.


--
.SG6160
--
.. Desligue a alimentação do controlador de armazenamento SG6100-CN.
.. Aguarde até que o LED azul de alimentação no controlador de armazenamento SG6100-CN se desligue.


--
.SGF6112
--
.. Desligue a alimentação do aparelho.
.. Aguarde até que o LED azul de alimentação se desligue.


--
.SG6000
--
.. Aguarde que o LED verde Cache ative na parte de trás dos controladores de armazenamento se desligue.
+
Este LED fica aceso quando os dados em cache precisam ser gravados nas unidades. Tem de esperar que este LED se desligue antes de desligar a alimentação.

.. Desligue o aparelho e aguarde até que o LED azul de alimentação se desligue.


--
.SG5800
--
.. Aguarde que o LED verde Cache ative na parte de trás do controlador de armazenamento seja desligado.
+
Este LED fica aceso quando os dados em cache precisam ser gravados nas unidades. Tem de esperar que este LED se desligue antes de desligar a alimentação.

.. Na página inicial do Gerenciador do sistema do SANtricity, selecione *Exibir operações em andamento*.
.. Confirme se todas as operações foram concluídas antes de continuar com a próxima etapa.
.. Desligue ambos os interruptores de energia no compartimento do controlador e aguarde que todos os LEDs no compartimento do controlador se desliguem.


--
.SG5700
--
.. Aguarde que o LED verde Cache ative na parte de trás do controlador de armazenamento seja desligado.
+
Este LED fica aceso quando os dados em cache precisam ser gravados nas unidades. Tem de esperar que este LED se desligue antes de desligar a alimentação.

.. Desligue a alimentação do aparelho e aguarde que todas as atividades de exibição de LED e de sete segmentos parem.


--
====
. Se necessário, faça logout do shell de comando: `exit`
+
A grelha StorageGRID foi agora desligada.

. Se você permitiu acesso SSH externo,link:../admin/manage-external-ssh-access.html["bloquear acesso"] quando terminar de desligar os nós.




== Inicie os nós de grade


CAUTION: Se toda a grade tiver sido desligada por mais de 15 dias, entre em Contato com o suporte técnico antes de iniciar qualquer nó de grade. Não tente os procedimentos de recuperação que reconstroem dados do Cassandra. Isso pode resultar em perda de dados.

Se possível, ligue os nós da grade nesta ordem:

* Aplique o poder aos nós de administração primeiro.
* Aplique energia aos nós do Gateway por último.



NOTE: Se um host incluir vários nós de grade, os nós retornarão online automaticamente quando você ligar o host.

.Passos
. Ligue os hosts para o nó de administração principal e quaisquer nós de administração não primários.
+

NOTE: Você não poderá fazer login nos nós de administração até que os nós de storage tenham sido reiniciados.

. Ligue os hosts para todos os nós de storage.
+
Você pode ativar esses nós em qualquer ordem.

. Ligue os hosts para todos os nós do Gateway.
. Faça login no Gerenciador de Grade.
. Selecione *Nós* e monitore o status dos nós da grade.  Verifique se não há ícones de alerta ao lado dos nomes dos nós.


.Informações relacionadas
* https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/index.html["Aparelhos de armazenamento SGF6112 e SG6160"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg110-1100/index.html["Aparelhos de serviços SG110 e SG1100"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg100-1000/index.html["Aparelhos de serviços SG100 e SG1000"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg6000/index.html["SG6000 dispositivos de armazenamento"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg5800/index.html["SG5800 dispositivos de armazenamento"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg5700/index.html["SG5700 dispositivos de armazenamento"^]

