---
permalink: maintain/recovering-storagegrid-appliance-storage-node.html 
sidebar: sidebar 
keywords: recover, appliance storage node failure, workflow 
summary: O procedimento para recuperar um nó de storage de dispositivo StorageGRID com falha é o mesmo se você está se recuperando da perda da unidade do sistema ou da perda de volumes de storage somente. 
---
= Avisos para recuperar os nós de storage do dispositivo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O procedimento para recuperar um nó de storage de dispositivo StorageGRID com falha é o mesmo se você está se recuperando da perda da unidade do sistema ou da perda de volumes de storage somente.


CAUTION: Se mais de um nó de armazenamento tiver falhado (ou estiver offline), contacte o suporte técnico. Não execute o seguinte procedimento de recuperação. Pode ocorrer perda de dados. Para obter mais informações, link:how-site-recovery-is-performed-by-technical-support.html["Como o suporte técnico recupera um site"]consulte .


CAUTION: Se as regras ILM estiverem configuradas para armazenar apenas uma cópia replicada e a cópia existir num volume de armazenamento que falhou, não será possível recuperar o objeto.


NOTE: Para procedimentos de manutenção de hardware, como instruções para substituir um controlador ou reinstalar o sistema operacional SANtricity, consulte https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/index.html["instruções de manutenção para o seu aparelho de armazenamento"^].
