---
permalink: maintain/recovering-from-storage-volume-failure-where-system-drive-is-intact.html 
sidebar: sidebar 
keywords: storagegrid, recover, storage volume failure, volume failure, system drive intact 
summary: Você deve concluir uma série de tarefas para recuperar um nó de storage baseado em software em que um ou mais volumes de armazenamento no nó de armazenamento falharam, mas a unidade do sistema está intacta. Se apenas os volumes de armazenamento tiverem falhado, o nó de armazenamento ainda estará disponível para o sistema StorageGRID. 
---
= Recuperar de uma falha no volume de armazenamento em que a unidade do sistema está intacta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve concluir uma série de tarefas para recuperar um nó de storage baseado em software em que um ou mais volumes de armazenamento no nó de armazenamento falharam, mas a unidade do sistema está intacta. Se apenas os volumes de armazenamento tiverem falhado, o nó de armazenamento ainda estará disponível para o sistema StorageGRID.


NOTE: Este procedimento de recuperação aplica-se apenas a nós de storage baseados em software. Se os volumes de armazenamento tiverem falhado num nó de armazenamento de dispositivo, utilize o procedimento do dispositivo: link:recovering-storagegrid-appliance-storage-node.html["Recupere o nó de storage do dispositivo"].

Este procedimento de recuperação inclui as seguintes tarefas:

* link:reviewing-warnings-about-storage-volume-recovery.html["Reveja os avisos de recuperação do volume de armazenamento"]
* link:identifying-and-unmounting-failed-storage-volumes.html["Identificar e desmontar volumes de storage com falha"]
* link:recovering-failed-storage-volumes-and-rebuilding-cassandra-database.html["Recupere os volumes e reconstrua o banco de dados Cassandra"]
* link:restoring-object-data-to-storage-volume-where-system-drive-is-intact.html["Restaurar dados de objeto"]
* link:checking-storage-state-after-recovering-storage-volumes.html["Verifique o estado de armazenamento"]

