---
permalink: maintain/replacing-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, replace primary admin node, replacing primary admin node, primary admin node 
summary: Para recuperar um nó de administrador principal, primeiro você deve substituir o hardware físico ou virtual. 
---
= Substitua o nó de administração primário do StorageGRID usando o mesmo nó de administração primário
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para recuperar um nó de administrador principal, primeiro você deve substituir o hardware físico ou virtual.

Para recuperar um nó de administrador principal, primeiro você deve substituir o hardware físico ou virtual.

* Você pode substituir um nó de administração primário com falha por um nó de administração primário em execução na mesma plataforma.
* Você pode substituir um nó de administração primário em execução em um host VMware ou Linux por um nó de administração primário hospedado em um appliance de serviços StorageGRID.
* Você pode substituir um nó de administração primário em execução em um host VMware por um appliance de serviços SG1000 ou SG100.


Use o procedimento que corresponde à plataforma de substituição selecionada para o nó. Depois de concluir o procedimento de substituição do nó (que é adequado para todos os tipos de nó), esse procedimento irá direcioná-lo para a próxima etapa para a recuperação do nó de administração principal.

[cols="1a,2a"]
|===
| Plataforma de substituição | Procedimento 


 a| 
VMware
 a| 
link:all-node-types-replacing-vmware-node.html["Substitua um nó VMware por um nó de recuperação"]

link:replace-vmware-node-with-sg1000-sg100.html["Substitua um nó VMware por um SG1000 ou SG100"]



 a| 
Linux
 a| 
link:all-node-types-replacing-linux-node.html["Substitua um nó Linux"]



 a| 
Aparelhos de serviços
 a| 
link:replacing-failed-node-with-services-appliance.html["Substitua um dispositivo de serviços"]



 a| 
OpenStack
 a| 
Os arquivos e scripts de disco de máquina virtual fornecidos pela NetApp para OpenStack não são mais compatíveis com operações de recuperação. Se você precisar recuperar um nó em execução em uma implantação OpenStack, baixe os arquivos para seu sistema operacional Linux. Em seguida, siga o procedimento para link:all-node-types-replacing-linux-node.html["Substituindo um nó Linux"].

|===