---
permalink: maintain/restarting-server-manager-and-all-services.html 
sidebar: sidebar 
keywords: storagegrid, recover, server manager, restart server manager 
summary: Talvez seja necessário reiniciar o gerenciador de servidor e todos os serviços em execução em um nó de grade. 
---
= Reinicie o Server Manager e todos os serviços
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Talvez seja necessário reiniciar o gerenciador de servidor e todos os serviços em execução em um nó de grade.

.Antes de começar
Você tem o `Passwords.txt` arquivo.

.Passos
. Faça login no nó da grade:
+
.. Introduza o seguinte comando: `ssh admin@_grid_node_IP_`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
.. Digite o seguinte comando para mudar para root: `su -`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.


+
Quando você estiver conetado como root, o prompt mudará de `$` para `#`.

. Reinicie o Server Manager e todos os serviços no nó de grade: `service servermanager restart`
+
O Gerenciador de servidores e todos os serviços no nó de grade são interrompidos e reiniciados.

+

NOTE: Utilizar o `restart` comando é o mesmo que utilizar o `stop` comando seguido do `start` comando.

. Faça logout do shell de comando: `exit`

