---
permalink: maintain/reviewing-warnings-for-system-drive-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, system drive warning, storage node 
summary: Antes de recuperar uma unidade de sistema com falha de um nó de armazenamento, reveja os avisos e considerações gerais para a recuperação do nó de grade e os seguintes avisos específicos. 
---
= Avisos para recuperação da unidade do sistema Storage Node
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de recuperar uma unidade de sistema com falha de um nó de armazenamento, reveja os avisos gerais link:warnings-and-considerations-for-grid-node-recovery.html["avisos e considerações para a recuperação do nó da grade"] e específicos a seguir.

Os nós de storage têm um banco de dados Cassandra que inclui metadados de objetos. O banco de dados Cassandra pode ser reconstruído se:

* Um volume de armazenamento falha e é recuperado.
* A unidade do sistema e um ou mais volumes de armazenamento falham e são recuperados.


Quando o Cassandra é reconstruído, o sistema usa informações de outros nós de storage. Se o Cassandra foi reconstruído recentemente, os dados do Cassandra podem ainda não ser consistentes em toda a grade. Se muitos nós de storage estiverem offline:

* Alguns dados do Cassandra podem não estar disponíveis.
* Pode ocorrer perda de dados.



CAUTION: Se mais de um nó de armazenamento tiver falhado (ou estiver offline), contacte o suporte técnico. Não execute o seguinte procedimento de recuperação. Pode ocorrer perda de dados. Para obter mais informações, link:how-site-recovery-is-performed-by-technical-support.html["Como o suporte técnico recupera um site"]consulte .


CAUTION: Se este nó de armazenamento estiver no modo de manutenção somente leitura para permitir a recuperação de objetos por outro nó de armazenamento com volumes de armazenamento com falha, recupere volumes no nó de armazenamento com volumes de armazenamento com falha antes de recuperar este nó de armazenamento com falha. Consulte as instruções para link:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["recuperar de uma falha no volume de armazenamento em que a unidade do sistema está intacta"].


CAUTION: Se as regras ILM estiverem configuradas para armazenar apenas uma cópia replicada e a cópia existir num volume de armazenamento que falhou, não será possível recuperar o objeto.
