---
permalink: maintain/selecting-start-recovery-to-configure-storage-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, storage node 
summary: Depois de substituir um nó de armazenamento, você deve selecionar Iniciar recuperação no Gerenciador de Grade para configurar o novo nó como um substituto para o nó com falha. 
---
= Selecione Iniciar Recuperação para configurar StorageGRID Storage Node
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de substituir um nó de armazenamento, você deve selecionar Iniciar recuperação no Gerenciador de Grade para configurar o novo nó como um substituto para o nó com falha.

.Antes de começar
* Você está conetado ao Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
* Você tem o link:../admin/admin-group-permissions.html["Permissão de manutenção ou acesso root"].
* Você tem a senha de provisionamento.
* Você implantou e configurou o nó de substituição.
* Tem a data de início de quaisquer trabalhos de reparação para dados codificados por apagamento.


.Sobre esta tarefa
Se o nó de armazenamento for instalado como um contentor em um host Linux, você deverá executar esta etapa somente se um deles for verdadeiro:

* Você teve que usar o `--force` sinalizador para importar o nó, ou você emitiu `storagegrid node force-recovery _node-name_`
* Você teve que fazer uma reinstalação completa do nó, ou você precisava restaurar /var/local.


.Passos
. Faça login no nó de administração principal. Se o nó de administração principal estiver indisponível, use um nó de administração não principal, se houver.
. No Grid Manager, selecione *Manutenção* > *Tarefas* > *Recuperação de nó*.
. Selecione o nó de grade que você deseja recuperar na lista de nós pendentes.
+
Os nós aparecem na lista depois que eles falham, mas você não pode selecionar um nó até que ele seja reinstalado e esteja pronto para recuperação.

. Digite a *senha de provisionamento*.
. Clique em *Iniciar recuperação*.
. Acompanhe o progresso da recuperação selecionando *Manutenção* > *Tarefas* > *Recuperação de nó* e visualizando o progresso da recuperação.
+
** Se o nó da grade atingir o estágio "Aguardando etapas manuais", você deve link:../maintain/remounting-and-reformatting-storage-volumes-manual-steps.html["Remonte e reformate os volumes de armazenamento manualmente"]. Após a conclusão das etapas manuais, prossiga para link:../maintain/restoring-object-data-to-storage-volume.html["restaurar dados de objetos para os volumes"].
** Se a recuperação do nó da grade passou de *Em Andamento* para *Recuperado* sem passar pelo estágio "Aguardando etapas manuais", nenhuma ação adicional é necessária.
+
[NOTE]
====
A qualquer momento durante a recuperação, você pode selecionar *Redefinir* para iniciar uma nova recuperação. Uma caixa de diálogo será exibida, indicando que o nó ficará em um estado indeterminado se você redefinir o procedimento.

Se você quiser tentar novamente a recuperação após redefinir o procedimento, deve restaurar o nó do appliance para um estado pré-instalado, da seguinte forma:

*** *VMware*: Exclua o nó de grade virtual implantado. Em seguida, quando estiver pronto para reiniciar a recuperação, reimplante o nó.
*** * Linux*: Reinicie o nó executando este comando no host Linux: `storagegrid node force-recovery _node-name_`


====



