---
permalink: maintain/selecting-node-recovery-procedure.html 
sidebar: sidebar 
keywords: storagegrid, recover, procedure 
summary: Selecione o procedimento de recuperação correto para o tipo de nó que apresentou falha. 
---
= Selecione o procedimento de recuperação do nó StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Selecione o procedimento de recuperação correto para o tipo de nó que apresentou falha.

[cols="1a,2a"]
|===
| Nó de grade | Procedimento de recuperação 


 a| 
Nó de storage
 a| 
O procedimento de recuperação do nó de armazenamento depende do tipo de falha.

link:recovering-from-storage-node-failures.html["Recuperar de falhas no nó de storage"]



 a| 
Nó de administração
 a| 
O procedimento Admin Node depende se você precisa recuperar o nó Admin primário ou um nó Admin não primário.

link:recovering-from-admin-node-failures.html["Recuperar de falhas no Admin Node"]



 a| 
Nó de gateway
 a| 
link:replacing-gateway-node.html["Recuperação de falhas do Gateway Node"]



 a| 
Nó de arquivo
 a| 
https://docs.netapp.com/us-en/storagegrid-118/maintain/recovering-from-archive-node-failures.html["Recuperação de falhas de nó de arquivo (StorageGRID 11,8 doc site)"^]

|===

NOTE: Se um servidor que hospeda mais de um nó de grid falhar, você pode recuperar os nós em qualquer ordem. No entanto, se o servidor com falha estiver hospedando o nó de administração primário e não houver nós de administração não primários, você deve recuperar o nó de administração primário primeiro. Recuperar o nó de administração primário primeiro evita que a recuperação de outros nós seja interrompida enquanto eles tentam contatar o nó de administração primário. Se um nó de administração não primário estiver disponível, você também pode usá-lo para recuperar outros nós, permitindo que essas recuperações prossigam sem contatar o nó de administração primário.
