---
permalink: maintain/starting-storagegrid-appliance-installation.html 
sidebar: sidebar 
keywords: storagegrid, recover, appliance, appliance install 
summary: Para instalar o StorageGRID em um nó de armazenamento de dispositivos, use o Instalador de dispositivos StorageGRID, que está incluído no dispositivo. 
---
= Inicie a instalação do dispositivo StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para instalar o StorageGRID em um nó de armazenamento de dispositivos, use o Instalador de dispositivos StorageGRID, que está incluído no dispositivo.

.Antes de começar
* O dispositivo foi instalado em um rack, conetado às redes e ligado.
* Os links de rede e endereços IP foram configurados para o dispositivo usando o Instalador de dispositivos StorageGRID.
* Você sabe o endereço IP do nó de administrador principal para a grade StorageGRID.
* Todas as sub-redes de rede listadas na página Configuração IP do Instalador de dispositivos StorageGRID foram definidas na Lista de sub-redes de rede de Grade no nó de administração principal.
* Concluiu estas tarefas de pré-requisito seguindo as instruções de instalação do seu dispositivo de armazenamento.  https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/index.html["Início rápido para instalação de hardware"^]Consulte .
* Você está usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
* Você conhece um dos endereços IP atribuídos ao controlador de computação no dispositivo. Você pode usar o endereço IP da rede Admin (porta de gerenciamento 1 no controlador), da rede de Grade ou da rede do cliente.


.Sobre esta tarefa
Para instalar o StorageGRID em um nó de storage do dispositivo:

* Especifique ou confirme o endereço IP do nó de administração principal e o nome do host (nome do sistema) do nó.
* Inicie a instalação e aguarde à medida que os volumes estão configurados e o software está instalado.
+

NOTE: Ao recuperar um nó de storage de dispositivo, reinstale-o com o mesmo tipo de storage que o dispositivo original (combinado, somente metadados ou somente dados). Se especificar um tipo de armazenamento diferente, a recuperação falhará e exigirá a reinstalação do dispositivo com o tipo de armazenamento correto especificado.

* No decorrer do processo, a instalação é interrompida. Para retomar a instalação, você deve entrar no Gerenciador de Grade e configurar o nó de armazenamento pendente como um substituto para o nó com falha.
* Depois de configurar o nó, o processo de instalação do appliance é concluído e o appliance é reinicializado.


.Passos
. Abra um navegador e insira um dos endereços IP do controlador de computação no dispositivo.
+
`https://_Controller_IP_:8443`

+
A página inicial do instalador do dispositivo StorageGRID é exibida.

. Na seção conexão nó de administrador principal, determine se você precisa especificar o endereço IP do nó de administrador principal.
+
O Instalador do StorageGRID Appliance pode descobrir esse endereço IP automaticamente, assumindo que o nó de administrador principal, ou pelo menos um outro nó de grade com ADMIN_IP configurado, está presente na mesma sub-rede.

. Se este endereço IP não for exibido ou você precisar alterá-lo, especifique o endereço:
+
[cols="1a,2a"]
|===
| Opção | Passos 


 a| 
Entrada de IP manual
 a| 
.. Desmarque a caixa de seleção *Ativar descoberta de nó de administrador*.
.. Introduza o endereço IP manualmente.
.. Clique em *Salvar*.
.. Aguarde enquanto o estado de conexão para o novo endereço IP se torna "pronto".




 a| 
Detecção automática de todos os nós de administração principal conetados
 a| 
.. Marque a caixa de seleção *Enable Admin Node Discovery* (Ativar descoberta de nó de administrador).
.. Na lista de endereços IP descobertos, selecione o nó de administração principal para a grade em que este nó de armazenamento do dispositivo será implantado.
.. Clique em *Salvar*.
.. Aguarde enquanto o estado de conexão para o novo endereço IP se torna "pronto".


|===
. No campo *Nome do nó*, insira o mesmo nome de host (nome do sistema) usado para o nó que você está recuperando e clique em *Salvar*.
. Na seção Instalação, confirme se o estado atual é "Pronto para iniciar a instalação `_node name_` no grid com o nó Admin principal "_admin_ip_" e que o botão *Start Installation* está ativado.
+
Se o botão *Start Installation* (Iniciar instalação) não estiver ativado, poderá ser necessário alterar a configuração da rede ou as definições da porta. Para obter instruções, consulte as instruções de manutenção do seu aparelho.

. Na página inicial do Instalador de dispositivos StorageGRID, clique em *Iniciar instalação*.
+
O estado atual muda para "a instalação está em andamento" e a página Instalação do monitor é exibida.

+

NOTE: Se você precisar acessar a página Instalação do Monitor manualmente, clique em *Instalação do Monitor* na barra de menus.  https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/monitoring-appliance-installation.html["Monitore a instalação do dispositivo"^]Consulte .


