---
permalink: maintain/understanding-adc-service-quorum.html 
sidebar: sidebar 
keywords: storagegrid, recover, adc, adc quorum 
summary: 'O quórum do ADC garante que um número mínimo de serviços do Controlador de Domínio Administrativo (ADC) permaneça disponível em cada site. O StorageGRID move automaticamente o serviço do ADC durante a desativação, quando necessário.' 
---
= O que é o quorum do ADC do StorageGRID?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O quórum do ADC garante que um número mínimo de serviços do Controlador de Domínio Administrativo (ADC) permaneça disponível em cada site. O StorageGRID move automaticamente o serviço do ADC durante a desativação, quando necessário.

O serviço ADC, que é encontrado em alguns nós de storage, mantém informações de topologia de grade e fornece serviços de configuração para a grade. O sistema StorageGRID requer que um quórum de serviços ADC esteja disponível em cada local e em todos os momentos.

Não é possível desativar um nó de armazenamento se a remoção do nó fizer com que o quórum de ADC não seja mais atendido. Para satisfazer o quórum de ADC durante a desativação, um mínimo de três nós de armazenamento em cada local deve ter o serviço ADC. Se um local tiver mais de três nós de storage com o serviço ADC, a maioria simples desses nós deve permanecer disponível após a desativação: `((0.5 * _Storage Nodes with ADC_) + 1)`


CAUTION: Tenha cuidado ao desativar os nós de storage em uma grade que contém nós somente metadados baseados em software. Se você desativar todos os nós configurados para armazenar _tanto_ objetos quanto metadados, a capacidade de armazenar objetos será removida da grade. Consulte link:../primer/what-storage-node-is.html#types-of-storage-nodes["Tipos de nós de storage"] para obter mais informações sobre nós de storage somente de metadados.

Por exemplo, suponha que um site inclua atualmente seis nós de storage com serviços ADC e que você queira desativar três nós de storage. Devido ao requisito de quórum do ADC, você deve concluir dois procedimentos de desativação, como segue:

* No primeiro procedimento de desativação, você deve garantir que quatro nós de storage com serviços ADC permaneçam disponíveis: `((0.5 * 6) + 1)`. Isso significa que você só pode desativar dois nós de storage inicialmente.
* No segundo procedimento de descomissionamento, você pode remover o terceiro nó de armazenamento porque o quorum do ADC agora requer apenas três serviços do ADC para permanecerem disponíveis: `((0.5 * 4) + 1)` .


Ao desativar um Nó de Armazenamento que possui o serviço ADC, StorageGRID move automaticamente o serviço ADC para outro Nó de Armazenamento no mesmo site, caso a desativação reduza o número de ADCs do site a um número inferior ao quórum. A movimentação automática requer que todos os nós na grid estejam conectados e que haja Nós de Armazenamento sem ADC disponíveis no mesmo site para receber o serviço. O procedimento de desativação mantém um mínimo de três Nós de Armazenamento com ADC por site. Por exemplo, se você desativar quatro ou seis nós com ADC em um site, três Nós de Armazenamento com ADC permanecerão após o procedimento, desde que haja nós sem ADC disponíveis no mesmo site.

Se o serviço ADC não puder ser movido automaticamente, você pode link:move-adc-service.html["mover manualmente o serviço ADC"] movê-lo para outro Storage Node no mesmo site ou link:../expand/index.html["Adicionar um novo Storage Node em uma expansão"] e especificar que ele deve ter um serviço ADC. Em seguida, você pode descomissionar o Storage Node existente sem afetar o quorum.
