---
permalink: maintain/viewing-current-status-of-service.html 
sidebar: sidebar 
keywords: storagegrid, recover, service, status 
summary: Você pode visualizar o status atual de um serviço em execução em um nó de grade a qualquer momento. 
---
= Ver o estado atual do serviço
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode visualizar o status atual de um serviço em execução em um nó de grade a qualquer momento.

.Antes de começar
Você tem o `Passwords.txt` arquivo.

.Passos
. Faça login no nó da grade:
+
.. Introduza o seguinte comando: `ssh admin@_grid_node_IP_`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
.. Digite o seguinte comando para mudar para root: `su -`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.


+
Quando você estiver conetado como root, o prompt mudará de `$` para `#`.

. Exibir o status atual de um serviço em execução em um nó de grade: "*Service _servicename_ status* o status atual do serviço solicitado em execução no nó de grade é relatado (em execução ou não). Por exemplo:
+
[listing]
----
cmn running for 1d, 14h, 21m, 2s
----
. Faça logout do shell de comando: `*exit*`

