---
permalink: expand/adding-new-site.html 
sidebar: sidebar 
keywords: expand, expansion, new site, add site, guidelines, StorageGRID 
summary: Você pode expandir seu sistema StorageGRID adicionando um novo site. 
---
= Diretrizes para adicionar um novo site no StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode expandir seu sistema StorageGRID adicionando um novo site.



[[guidelines-for-adding-a-site]]
== Diretrizes para adicionar um site

Antes de adicionar um site, revise os seguintes requisitos e limitações:

* Só é possível adicionar um local por operação de expansão.
* Não é possível adicionar nós de grade a um site existente como parte da mesma expansão.
* Todos os sites devem incluir pelo menos três nós de armazenamento. Eles podem ser qualquer combinação de nós de armazenamento combinados e somente de metadados. Se houver mais de três nós de armazenamento, eles podem ser qualquer combinação de nós de armazenamento combinados, somente de metadados e somente de dados, desde que três serviços ADC estejam disponíveis. Para mais informações, consulte link:../primer/what-storage-node-is.html#required-storage-nodes-per-grid-and-per-site["Nós de armazenamento necessários por grade e por site"].
* Ao adicionar um novo site, o número de objetos que você pode armazenar não aumenta automaticamente. A capacidade total de objetos de uma grid depende da quantidade de storage disponível, da política ILM e da capacidade de metadados em cada site.
* Ao dimensionar um novo local, você deve garantir que ele inclua capacidade suficiente de metadados.
+
StorageGRID mantém uma cópia de todos os metadados em cada site. Ao adicionar um novo site, certifique-se de que ele inclua capacidade de metadados suficiente para os metadados de objeto existentes e capacidade de metadados suficiente para o crescimento.

+
Para obter mais informações, consulte o seguinte:

+
** link:../admin/managing-object-metadata-storage.html["Gerenciar o storage de metadados de objetos"]
** link:../monitor/monitoring-storage-capacity.html#monitor-object-metadata-capacity-for-each-storage-node["Monitore a capacidade dos metadados de objetos para cada nó de storage"]


* Você deve considerar a largura de banda de rede disponível entre sites e o nível de latência de rede. As atualizações de metadados são continuamente replicadas entre sites, mesmo que todos os objetos sejam armazenados apenas no local onde são ingeridos.
+
Para ajudar a evitar baixo desempenho devido à latência:

+
** A codificação de apagamento não é recomendada entre sites com latência superior a 100 ms.
** Os sites no seu sistema StorageGRID não devem abranger grandes distâncias geográficas, por exemplo, atravessando vários continentes.


* Como o sistema StorageGRID permanece operacional durante a expansão, você deve revisar as regras do ILM antes de iniciar o procedimento de expansão. Você deve garantir que as cópias de objeto não sejam armazenadas no novo local até que o procedimento de expansão seja concluído.
+
Por exemplo, antes de iniciar a expansão, verifique se alguma regra utiliza o pool de storage padrão (All Storage Nodes). Se utilizar, crie um novo pool de storage com os Storage Nodes existentes e atualize suas regras de ILM para usar o novo pool de storage. Caso contrário, os objetos são copiados para o novo site assim que o primeiro nó desse site se tornar ativo.

+
Para obter mais informações sobre como alterar uma política ILM ao adicionar um novo site, consulte o link:../ilm/example-6-changing-ilm-policy.html["Exemplo para alterar uma política ILM"].


