---
permalink: expand/adding-grid-nodes-to-existing-site-or-adding-new-site.html 
sidebar: sidebar 
keywords: grid node, add node, add site, expand, expansion, StorageGRID 
summary: Siga este procedimento para adicionar nós de grade a sites existentes ou para adicionar um novo site. Você só pode executar um tipo de expansão de cada vez. 
---
= Resumo do fluxo de trabalho para adicionar nós de grade ou novos sites ao StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimento para adicionar nós de grade a sites existentes ou para adicionar um novo site. Você só pode executar um tipo de expansão de cada vez.

.Antes de começar
* Você tem o link:../admin/admin-group-permissions.html["Acesso root ou permissão de manutenção"].
* Todos os nós existentes na grade estão ativos e em execução em todos os locais.
* Todos os procedimentos anteriores de expansão, atualização, desativação ou recuperação estão concluídos.
+

NOTE: Você é impedido de iniciar uma expansão enquanto outro procedimento de expansão, atualização, recuperação ou desativação ativa está em andamento. No entanto, se necessário, você pode pausar um procedimento de desativação para iniciar uma expansão.



.Passos
. link:updating-subnets-for-grid-network.html["Atualizar sub-redes para a Rede Grid"].
. link:deploying-new-grid-nodes.html["Implante os novos nós da grade."].
. link:performing-expansion.html["Execute a expansão"].

