---
permalink: expand/copying-audit-logs.html 
sidebar: sidebar 
keywords: copy audit log, Admin Node expansion, 
summary: Quando você adiciona um novo nó Admin por meio de um procedimento de expansão, seu serviço AMS somente Registra eventos e ações que ocorrem depois que ele se une ao sistema. Conforme necessário, você pode copiar logs de auditoria de um nó de administrador instalado anteriormente para o novo nó de administração de expansão, de modo que ele esteja sincronizado com o resto do sistema StorageGRID. 
---
= Copiar registos de auditoria
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando você adiciona um novo nó Admin por meio de um procedimento de expansão, seu serviço AMS somente Registra eventos e ações que ocorrem depois que ele se une ao sistema. Conforme necessário, você pode copiar logs de auditoria de um nó de administrador instalado anteriormente para o novo nó de administração de expansão, de modo que ele esteja sincronizado com o resto do sistema StorageGRID.

.Antes de começar
* Você concluiu as etapas de expansão necessárias para adicionar um nó de administrador.
* Você tem o `Passwords.txt` arquivo.


.Sobre esta tarefa
Para disponibilizar mensagens de auditoria histórica em um novo nó de administração, você deve copiar os arquivos de log de auditoria manualmente de um nó de administração existente para o nó de administração de expansão.

[NOTE]
====
Por padrão, as informações de auditoria são enviadas para o log de auditoria nos nós de administração. Você pode ignorar estas etapas se qualquer uma das seguintes situações se aplicar:

* Você configurou um servidor syslog externo e os logs de auditoria agora estão sendo enviados para o servidor syslog em vez de para nós de administrador.
* Você especificou explicitamente que as mensagens de auditoria devem ser salvas somente nos nós locais que as geraram.


link:../monitor/configure-audit-messages.html["Configurar mensagens de auditoria e destinos de log"]Consulte para obter detalhes.

====
.Passos
. Faça login no nó de administração principal:
+
.. Introduza o seguinte comando: `ssh _admin@_primary_Admin_Node_IP_`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
.. Digite o seguinte comando para mudar para root: `su -`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
+
Quando você estiver conetado como root, o prompt mudará de `$` para `#`.



. Pare o serviço AMS para impedir que ele crie um novo arquivo: `service ams stop`
. Navegue até o diretório de exportação de auditoria:
+
`cd /var/local/log`

. Renomeie o arquivo de origem `audit.log` para garantir que ele não substitua o arquivo no nó de administração de expansão para o qual você está copiando:
+
[listing]
----
ls -l
mv audit.log _new_name_.txt
----
. Copie todos os arquivos de log de auditoria para o local de destino no nó de administração de expansão:
+
`scp -p * _IP_address_:/var/local/log`

. Se for solicitada a senha para `/root/.ssh/id_rsa`, digite a senha de acesso SSH para o nó de administração principal listado no `Passwords.txt` arquivo.
. Restaure o arquivo original `audit.log`:
+
`mv _new_name_.txt audit.log`

. Inicie o serviço AMS:
+
`service ams start`

. Terminar sessão a partir do servidor:
+
`exit`

. Faça login no nó de administração de expansão:
+
.. Introduza o seguinte comando: `ssh admin@_expansion_Admin_Node_IP_`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
.. Digite o seguinte comando para mudar para root: `su -`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
+
Quando você estiver conetado como root, o prompt mudará de `$` para `#`.



. Atualize as configurações de usuário e grupo para os arquivos de log de auditoria:
+
`cd /var/local/log`

+
`chown ams-user:bycast *`

. Terminar sessão a partir do servidor:
+
`exit`


