---
permalink: expand/copying-admin-node-database.html 
sidebar: sidebar 
keywords: copy Admin Node database, alert history, Admin Node expansion, StorageGRID 
summary: Ao adicionar nós de administração através de um procedimento de expansão, você pode opcionalmente copiar o banco de dados do nó de administração principal para o novo nó de administração. Copiar o banco de dados permite que você retenha informações históricas sobre atributos, alertas e alertas. 
---
= Copie o banco de dados do nó de administração para novos nós de administração no StorageGRID.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao adicionar nós de administração através de um procedimento de expansão, você pode opcionalmente copiar o banco de dados do nó de administração principal para o novo nó de administração. Copiar o banco de dados permite que você retenha informações históricas sobre atributos, alertas e alertas.

.Antes de começar
* Você concluiu as etapas de expansão necessárias para adicionar um nó de administrador.
* Você tem o `Passwords.txt` arquivo.
* Você tem a senha de provisionamento.


.Sobre esta tarefa
O processo de ativação do software StorageGRID cria um banco de dados vazio para o serviço NMS no nó de administração de expansão. Quando o serviço NMS é iniciado no nó de administração de expansão, ele Registra informações para servidores e serviços que atualmente fazem parte do sistema ou adicionados mais tarde. Este banco de dados Admin Node inclui as seguintes informações:

* Histórico de alertas
* Dados de atributos históricos, que são usados em gráficos de estilo legado na página de nós


Para garantir que o banco de dados do nó de administração seja consistente entre nós, você pode copiar o banco de dados do nó de administração principal para o nó de administração de expansão.


NOTE: Copiar o banco de dados do nó Admin principal (o nó Admin__source__) para um nó Admin de expansão pode levar até várias horas para ser concluído. Durante esse período, o Gerenciador de Grade fica inacessível.

Siga estas etapas para interromper o serviço MI e o serviço API de gerenciamento no nó de administração principal e no nó de administração de expansão antes de copiar o banco de dados.

.Passos
. Conclua as etapas a seguir no nó de administração principal:
+
.. Faça login no nó Admin:
+
... Introduza o seguinte comando: `ssh admin@_grid_node_IP_`
... Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
... Digite o seguinte comando para mudar para root: `su -`
... Introduza a palavra-passe listada no `Passwords.txt` ficheiro.


.. Execute o seguinte comando: `recover-access-points`
.. Introduza a frase-passe de aprovisionamento.
.. Parar o serviço MI: `service mi stop`
.. Pare o serviço Management Application Program Interface (mgmt-api): `service mgmt-api stop`


. Execute as seguintes etapas no nó de administração de expansão:
+
.. Faça login no nó de administração de expansão:
+
... Introduza o seguinte comando: `ssh admin@_grid_node_IP_`
... Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
... Digite o seguinte comando para mudar para root: `su -`
... Introduza a palavra-passe listada no `Passwords.txt` ficheiro.


.. Parar o serviço MI: `service mi stop`
.. Pare o serviço mgmt-api: `service mgmt-api stop`
.. Adicione a chave privada SSH ao agente SSH. Introduza:``ssh-add``
.. Insira a senha de acesso SSH listada no `Passwords.txt` arquivo.
.. Copie o banco de dados do nó Admin de origem para o nó Admin de expansão: `/usr/local/mi/bin/mi-clone-db.sh _Source_Admin_Node_IP_`
.. Quando solicitado, confirme se deseja substituir o banco de dados MI no nó de administração de expansão.
+
O banco de dados e seus dados históricos são copiados para o nó de administração de expansão. Quando a operação de cópia é concluída, o script inicia o nó de administração de expansão.

.. Quando você não precisar mais de acesso sem senha a outros servidores, remova a chave privada do agente SSH. Introduza:``ssh-add -D``


. Reinicie os serviços no nó de administração principal: `service servermanager start`

