---
permalink: expand/rebalancing-erasure-coded-data-after-adding-storage-nodes.html 
sidebar: sidebar 
keywords: erasure coding, EC, rebalancing, site rebalance procedure, StorageGRID 
summary: ApĂłs adicionar Storage Nodes, vocĂȘ pode usar o procedimento de rebalanceamento de codificaĂ§ĂŁo de apagamento para redistribuir os fragmentos codificados por apagamento entre os Storage Nodes existentes e os novos. 
---
= Reequilibre os dados codificados por apagamento apĂłs adicionar nĂłs ao seu sistema StorageGRID.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de adicionar nĂłs de storage, use o procedimento de rebalancear a codificaĂ§ĂŁo de apagamento (EC) para redistribuir fragmentos codificados por apagamento entre os nĂłs de storage atuais e novos.

.Antes de comeĂ§ar
* VocĂȘ concluiu as etapas de expansĂŁo para adicionar os novos nĂłs de storage.
* VocĂȘ revisou o link:considerations-for-rebalancing-erasure-coded-data.html["consideraĂ§Ă”es para rebalanceamento de dados codificados por apagamento"].
* VocĂȘ entende que os dados do objeto replicado nĂŁo serĂŁo movidos por este procedimento e que o procedimento de rebalanceamento do EC nĂŁo move dados replicados.  No entanto, os dados replicados sĂŁo considerados ao determinar para onde mover os dados do EC.
* VocĂȘ tem o `Passwords.txt` arquivo.


.O que acontece quando este procedimento Ă© executado
Antes de iniciar o procedimento, tome nota do seguinte:

* O procedimento de reequilĂ­brio EC nĂŁo serĂĄ iniciado se um ou mais volumes estiverem offline (desmontados) ou se estiverem online (montados), mas em estado de erro.
* O procedimento de reequilĂ­brio CE reserva temporariamente uma grande quantidade de armazenamento. Os alertas de storage podem ser acionados, mas serĂŁo resolvidos quando o rebalancear for concluĂ­do. Se nĂŁo houver armazenamento suficiente para a reserva, o procedimento de reequilĂ­brio CE falharĂĄ. As reservas de armazenamento sĂŁo liberadas quando o procedimento de reequilĂ­brio CE for concluĂ­do, independentemente de o procedimento ter falhado ou ter ĂȘxito.
* Se um volume ficar offline enquanto o procedimento de reequilĂ­brio CE estiver em andamento, o procedimento de reequilĂ­brio serĂĄ encerrado. Quaisquer fragmentos de dados que jĂĄ foram movidos permanecerĂŁo em seus novos locais e nenhum dado serĂĄ perdido.
+
VocĂȘ pode executar novamente o procedimento depois que todos os volumes estiverem novamente online.

* Quando o procedimento de rebalanceamento EC estiver em execuĂ§ĂŁo, o desempenho das operaĂ§Ă”es ILM e das operaĂ§Ă”es do cliente S3 podem ser afetados.
+

NOTE: As operaĂ§Ă”es de API S3D para fazer upload de objetos (ou partes de objetos) podem falhar durante o procedimento de rebalanceamento EC se precisarem de mais de 24 horas para serem concluĂ­das. As OPERAĂĂES PUT de longa duraĂ§ĂŁo falharĂŁo se a regra ILM aplicĂĄvel usar um posicionamento equilibrado ou rigoroso na ingestĂŁo. O seguinte erro serĂĄ comunicado: `500 Internal Server Error`.

* *CondiĂ§Ă”es de conclusĂŁo de trabalho*. O procedimento de reequilĂ­brio CE Ă© considerado completo quando qualquer uma das seguintes situaĂ§Ă”es for verdadeira:
+
** Ele nĂŁo pode mover mais dados codificados por apagamento.
** Os dados em todos os nĂłs estĂŁo dentro de um desvio de 5% da partiĂ§ĂŁo de espaĂ§o utilizĂĄvel alvo.
** O procedimento estĂĄ em execuĂ§ĂŁo hĂĄ 30 dias.




.Passos
. [[Review_object_storage]]Revise os detalhes de armazenamento de objetos atuais para o site que vocĂȘ planeja reequilibrar.
+
.. Selecione *NĂłs*.
.. Selecione o primeiro nĂł de storage no local.
.. Selecione a guia *armazenamento*.
.. Posicione o cursor sobre o grĂĄfico Storage Used - Object Data (armazenamento usado - dados de objetos) para ver a quantidade atual de dados replicados e dados codificados por apagamento no Storage Node.
.. Repita estas etapas para exibir os outros nĂłs de storage no local.


. FaĂ§a login no nĂł de administraĂ§ĂŁo principal:
+
.. Introduza o seguinte comando: `ssh admin@_primary_Admin_Node_IP_`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
.. Digite o seguinte comando para mudar para root: `su -`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
+
Quando vocĂȘ estiver conetado como root, o prompt mudarĂĄ de `$` para `#`.



. Inicie o procedimento:
+
'rebalance-data start --site "_site-name_"

+
Para "_site-name_", especifique o primeiro local onde vocĂȘ adicionou novo nĂł de storage ou nĂłs. Inclua `site-name` em citaĂ§Ă”es.

+
O procedimento de reequilĂ­brio EC Ă© iniciado e um ID de tarefa Ă© retornado.

. Copie a ID do trabalho.
. [[view-status]]monitore o status do procedimento de rebalanceamento EC.
+
** Para visualizar o estado de um procedimento Ășnico de reequilĂ­brio CE:
+
`rebalance-data status --job-id _job-id_`

+
Para `_job-id_`, especifique o ID que foi retornado quando vocĂȘ iniciou o procedimento.

** Para visualizar o estado do atual procedimento de reequilĂ­brio CE e de quaisquer procedimentos concluĂ­dos anteriormente:
+
`rebalance-data status`

+
[NOTE]
====
Para obter ajuda sobre o comando rebalanceamento-data:

`rebalance-data --help`

====


. Execute etapas adicionais, com base no status retornado:
+
** Se `State` for `In progress`, a operaĂ§ĂŁo de reequilĂ­brio CE ainda estĂĄ em execuĂ§ĂŁo. VocĂȘ deve monitorar periodicamente o procedimento atĂ© que ele seja concluĂ­do.
+
Acesse a pĂĄgina NĂłs para avaliar a distribuiĂ§ĂŁo de dados entre os NĂłs de Armazenamento no site.

+
A tarefa de rebalanceamento do EC Ă© considerada concluĂ­da e serĂĄ interrompida quando o espaĂ§o utilizĂĄvel em todos os nĂłs estiver dentro de um desvio de 5% da partiĂ§ĂŁo de espaĂ§o utilizĂĄvel alvo.

** Se `State` for `Success`, opcionalmente <<review_object_storage,revise o armazenamento de objetos>> para ver os detalhes atualizados do site.
+
O espaĂ§o utilizĂĄvel agora deve estar mais equilibrado entre os Storage Nodes no site.

**  `State`Se for `Failure`:
+
... Confirme se todos os nĂłs de storage no local estĂŁo conetados Ă  grade.
... Verifique e resolva quaisquer alertas que possam estar afetando esses nĂłs de storage.
... Reiniciar o procedimento EC Rebalanceance
+
`rebalance-data start â-job-id _job-id_`

... <<view-status,Ver o estado>> do novo procedimento. Se `State` ainda estiver `Failure` , contacte o suporte tĂ©cnico.




. Se o procedimento de reequilĂ­brio EC estiver gerando muita carga (por exemplo, as operaĂ§Ă”es de ingestĂŁo sĂŁo afetadas), interrompa o procedimento.
+
`rebalance-data pause --job-id _job-id_`

. Se vocĂȘ precisar encerrar o procedimento de rebalanceamento EC (por exemplo, para que vocĂȘ possa executar uma atualizaĂ§ĂŁo de software StorageGRID), digite o seguinte:
+
`rebalance-data terminate --job-id _job-id_`

+

NOTE: Quando vocĂȘ encerrar um procedimento de rebalanceamento do EC, todos os fragmentos de dados que jĂĄ foram movidos permanecem em seus novos locais. Os dados nĂŁo sĂŁo movidos de volta para o local original.

. Se vocĂȘ estiver usando codificaĂ§ĂŁo de apagamento em mais de um site, execute este procedimento para todos os outros sites afetados.

