---
permalink: expand/verifying-storage-node-is-active.html 
sidebar: sidebar 
keywords: expand, expansion, add storage nodes, verify node is active 
summary: Após a conclusão de uma operação de expansão que adiciona novos nós de storage, o sistema StorageGRID deve começar a usar automaticamente os novos nós de storage. Você deve usar o sistema StorageGRID para verificar se o novo nó de storage está ativo. 
---
= Verifique se o nó de storage está ativo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Após a conclusão de uma operação de expansão que adiciona novos nós de storage, o sistema StorageGRID deve começar a usar automaticamente os novos nós de storage. Você deve usar o sistema StorageGRID para verificar se o novo nó de storage está ativo.

.Passos
. Faça login no Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
. Selecione *NÓS* > *_Expansion Storage Node_* > *Storage*.
. Posicione o cursor sobre o gráfico *Storage Used - Object Data* (armazenamento usado - dados do objeto) para visualizar o valor para *Used*, que é a quantidade total de espaço utilizável que foi usado para dados do objeto.
. Verifique se o valor de *usado* está aumentando à medida que você move o cursor para a direita no gráfico.

