---
permalink: ilm/advantages-disadvantages-of-ingest-options.html 
sidebar: sidebar 
keywords: ingest options, balance ingest, strict ingest, dual commit ingest 
summary: 'Compreender as vantagens e desvantagens de cada uma das três opções para proteger dados na ingestão (equilibrada, rigorosa ou dupla confirmação) pode ajudá-lo a decidir qual escolher para uma regra ILM.' 
---
= Vantagens, desvantagens e limitações das opções de ingestão
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Compreender as vantagens e desvantagens de cada uma das três opções de proteção de dados na ingestão (equilibrada, rigorosa ou dupla confirmação) pode ajudá-lo a decidir qual escolher para uma regra ILM.

Para obter uma visão geral das opções de ingestão, link:data-protection-options-for-ingest.html["Opções de ingestão"]consulte .



== Vantagens das opções equilibradas e estritas

Quando comparado ao Dual Commit, que cria cópias provisórias durante a ingestão, as duas opções de posicionamento síncrono podem oferecer as seguintes vantagens:

* *Melhor segurança de dados*: Os dados do objeto são imediatamente protegidos conforme especificado nas instruções de colocação da regra ILM, que podem ser configurados para proteger contra uma ampla variedade de condições de falha, incluindo a falha de mais de um local de armazenamento. A confirmação dupla só pode proteger contra a perda de uma única cópia local.
* *Operação de grade mais eficiente*: Cada objeto é processado apenas uma vez, pois é ingerido. Como o sistema StorageGRID não precisa rastrear ou excluir cópias provisórias, há menos carga de processamento e menos espaço no banco de dados é consumido.
* * (Equilibrado) recomendado*: A opção equilibrada proporciona uma eficiência ideal de ILM. O uso da opção Balanced é recomendado, a menos que um comportamento de ingestão rigoroso seja necessário ou a grade atenda a todos os critérios para usar o Dual Commit.
* *(strict) certeza sobre locais de objetos*: A opção strict garante que os objetos são imediatamente armazenados de acordo com as instruções de colocação na regra ILM.




== Desvantagens das opções equilibradas e estritas

Quando comparado ao Dual Commit, as opções equilibradas e estritas têm algumas desvantagens:

* * Maiores ingerências de clientes*: As latências de ingestão de clientes podem ser mais longas. Quando você usa as opções balanceadas ou rigorosas, uma mensagem "ingerir bem-sucedida" não será retornada ao cliente até que todos os fragmentos codificados por apagamento ou cópias replicadas sejam criados e armazenados. No entanto, os dados de objetos provavelmente alcançarão seu posicionamento final muito mais rápido.
* *(strict) taxas mais altas de falha de ingestão*: Com a opção estrita, a ingestão falha sempre que o StorageGRID não puder fazer imediatamente todas as cópias especificadas na regra ILM. Você pode ver altas taxas de falha de ingestão se um local de armazenamento necessário estiver temporariamente off-line ou se problemas de rede causarem atrasos na cópia de objetos entre sites.
* *(strict) S3 colocações de upload de várias partes podem não ser como esperado em algumas circunstâncias*: Com strict, você espera que objetos sejam colocados como descrito pela regra ILM ou para que a ingestão falhe. No entanto, com um upload multipart S3, o ILM é avaliado para cada parte do objeto à medida que ele é ingerido e para o objeto como um todo quando o upload multipart é concluído. Nas seguintes circunstâncias, isso pode resultar em colocações que são diferentes do que você espera:
+
** *Se o ILM mudar enquanto um upload multipart S3 está em andamento*: Porque cada parte é colocada de acordo com a regra que está ativa quando a peça é ingerida, algumas partes do objeto podem não atender aos requisitos atuais do ILM quando o upload multipart é concluído. Nesses casos, a ingestão do objeto não falha. Em vez disso, qualquer peça que não seja colocada corretamente é colocada na fila para reavaliação ILM e é movida para o local correto mais tarde.
** *Quando as regras do ILM filtram no tamanho*: Ao avaliar o ILM para uma peça, o StorageGRID filtra o tamanho da peça, não o tamanho do objeto. Isso significa que partes de um objeto podem ser armazenadas em locais que não atendem aos requisitos de ILM para o objeto como um todo. Por exemplo, se uma regra especifica que todos os objetos de 10 GB ou maior são armazenados em DC1 enquanto todos os objetos menores são armazenados em DC2, na ingestão cada parte de 1 GB de um upload multipart de 10 partes é armazenado em DC2. Quando ILM é avaliado para o objeto, todas as partes do objeto são movidas para DC1.


* *(strict) ingest não falha quando tags de objeto ou metadados são atualizados e não é possível fazer posicionamentos recém-solicitados*: Com strict, você espera que objetos sejam colocados conforme descrito pela regra ILM ou para falha de ingestão. No entanto, quando você atualiza metadados ou tags para um objeto que já está armazenado na grade, o objeto não é reingerido. Isso significa que quaisquer alterações no posicionamento de objetos que são acionadas pela atualização não são feitas imediatamente. As alterações de posicionamento são feitas quando o ILM é reavaliado por processos normais de ILM em segundo plano. Se as alterações de posicionamento necessárias não puderem ser feitas (por exemplo, porque um local recém-solicitado não está disponível), o objeto atualizado mantém seu posicionamento atual até que as alterações de posicionamento sejam possíveis.




== Limitações em posicionamentos de objetos com opções equilibradas e estritas

As opções equilibradas ou estritas não podem ser usadas para regras de ILM que tenham qualquer uma destas instruções de colocação:

* Colocação em um pool de storage de nuvem no dia 0.
* Posicionamentos em um pool de armazenamento em nuvem quando a regra tiver um tempo de criação definido pelo usuário como seu tempo de referência.


Essas restrições existem porque o StorageGRID não pode fazer cópias sincronamente para um pool de armazenamento em nuvem, e um tempo de criação definido pelo usuário pode ser resolvido até o momento.



== Como as regras de ILM e a consistência interagem para afetar a proteção de dados

Tanto sua regra ILM quanto sua escolha de consistência afetam a forma como os objetos são protegidos. Essas configurações podem interagir.

Por exemplo, o comportamento de ingestão selecionado para uma regra ILM afeta o posicionamento inicial de cópias de objetos, enquanto a consistência usada quando um objeto é armazenado afeta o posicionamento inicial dos metadados de objetos. Como o StorageGRID requer acesso aos dados e metadados de um objeto para atender às solicitações do cliente, selecionar níveis de proteção correspondentes para o comportamento de consistência e ingestão pode fornecer melhor proteção de dados iniciais e respostas do sistema mais previsíveis.

Aqui está um breve resumo dos valores de consistência que estão disponíveis no StorageGRID:

* *Todos*: Todos os nós recebem metadados de objeto imediatamente ou a solicitação falhará.
* *Strong-global*: Garante consistência de leitura após gravação para todas as solicitações de clientes em todos os sites.  Quando a semântica do Quorum é configurada, os seguintes comportamentos se aplicam:
+
** Permite tolerância a falhas de site para solicitações de clientes quando as grades têm três ou mais sites.  Redes de dois locais não terão tolerância a falhas de local.
** As seguintes operações do S3 não terão sucesso com um site inativo:
+
*** DeleteBucketEncryption
*** PutBucketBranch
*** PutBucketEncryption
*** PutBucketControle de versão
*** PutObjectLegalHod
*** PutObjectLockConfiguration
*** Retenção PutObjectRetention




+
Se necessário, você pode https://kb.netapp.com/hybrid/StorageGRID/Object_Mgmt/Configuring_StorageGRID_quorum_semantics_for_strong-global_consistency["configurar a semântica do StorageGRID Quorum para consistência global forte"^] .

* *Strong-site*: Metadados de objetos são imediatamente distribuídos para outros nós no site. Garante consistência de leitura após gravação para todas as solicitações de clientes dentro de um site.
* *Read-after-novo-write*: Fornece consistência de leitura após gravação para novos objetos e consistência para atualizações de objetos. Oferece alta disponibilidade e garantias de proteção de dados. Recomendado para a maioria dos casos.
* *Disponível*: Fornece consistência eventual para novos objetos e atualizações de objetos. Para buckets do S3, use somente conforme necessário (por exemplo, para um bucket que contém valores de log raramente lidos, ou para operações HEAD ou GET em chaves que não existem). Não compatível com buckets do FabricPool S3.



NOTE: Antes de selecionar um valor de consistência,link:../s3/consistency.html["leia a descrição completa da consistência"] .  Você deve entender os benefícios e limitações antes de alterar o valor padrão.



== Exemplo de como a consistência e as regras do ILM podem interagir

Suponha que você tenha uma grade de três sites com a seguinte regra ILM e a seguinte consistência:

* *Regra do ILM*: Crie três cópias de objetos, uma no site local e uma em cada site remoto.  Use o comportamento de ingestão estrito.
* *Consistência*: Fortemente global (os metadados do objeto são imediatamente distribuídos para vários sites).


Quando um cliente armazena um objeto na grade, o StorageGRID faz todas as três cópias do objeto e distribui metadados para vários sites antes de retornar o sucesso ao cliente.

O objeto é totalmente protegido contra perda no momento da ingestão bem-sucedida da mensagem.  Por exemplo, se o site local for perdido logo após a ingestão, cópias dos dados do objeto e dos metadados do objeto ainda existirão nos sites remotos.  O objeto pode ser totalmente recuperado de outros sites.

Se, em vez disso, você usasse a mesma regra de ILM e a consistência de site forte, o cliente poderia receber uma mensagem de sucesso depois que os dados do objeto fossem replicados para os sites remotos, mas antes que os metadados do objeto fossem distribuídos lá.  Nesse caso, o nível de proteção dos metadados do objeto não corresponde ao nível de proteção dos dados do objeto.  Se o site local for perdido logo após a ingestão, os metadados do objeto serão perdidos.  O objeto não pode ser recuperado.

A inter-relação entre consistência e regras de ILM pode ser complexa. Contacte a NetApp se necessitar de assistência.

.Informações relacionadas
link:example-5-ilm-rules-and-policy-for-strict-ingest-behavior.html["Exemplo 5: Regras de ILM e política para comportamento de ingestão rigorosa"]
