---
permalink: ilm/how-objects-are-deleted.html 
sidebar: sidebar 
keywords: ILM deletion, how objects are deleted 
summary: O StorageGRID pode excluir objetos em resposta direta a uma solicitaĂ§ĂŁo de cliente ou automaticamente como resultado da expiraĂ§ĂŁo de um ciclo de vida de bucket do S3 ou dos requisitos da polĂ­tica do ILM. Entender as diferentes maneiras pelas quais os objetos podem ser excluĂ­dos e como o StorageGRID lida com solicitaĂ§Ă”es de exclusĂŁo pode ajudar vocĂȘ a gerenciar objetos com mais eficiĂȘncia. 
---
= Como StorageGRID exclui objetos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O StorageGRID pode excluir objetos em resposta direta a uma solicitaĂ§ĂŁo de cliente ou automaticamente como resultado da expiraĂ§ĂŁo de um ciclo de vida de bucket do S3 ou dos requisitos da polĂ­tica do ILM. Entender as diferentes maneiras pelas quais os objetos podem ser excluĂ­dos e como o StorageGRID lida com solicitaĂ§Ă”es de exclusĂŁo pode ajudar vocĂȘ a gerenciar objetos com mais eficiĂȘncia.

O StorageGRID pode usar um dos dois mĂ©todos para excluir objetos:

* ExclusĂŁo sĂ­ncrona: Quando o StorageGRID recebe uma solicitaĂ§ĂŁo de exclusĂŁo de cliente, todas as cĂłpias de objeto sĂŁo removidas imediatamente. O cliente Ă© informado de que a exclusĂŁo foi bem-sucedida apĂłs as cĂłpias terem sido removidas.
* Os objetos sĂŁo enfileirados para exclusĂŁo: Quando o StorageGRID recebe uma solicitaĂ§ĂŁo de exclusĂŁo, o objeto Ă© enfileirado para exclusĂŁo e o cliente Ă© informado imediatamente de que a exclusĂŁo foi bem-sucedida. CĂłpias de objeto sĂŁo removidas posteriormente pelo processamento ILM em segundo plano.


Ao excluir objetos, o StorageGRID usa o mĂ©todo que otimiza o desempenho de exclusĂŁo, minimiza possĂ­veis backlogs de exclusĂŁo e libera espaĂ§o mais rapidamente.

A tabela resume quando o StorageGRID usa cada mĂ©todo.

[cols="1a,3a"]
|===
| MĂ©todo de execuĂ§ĂŁo da exclusĂŁo | Quando utilizado 


 a| 
Os objetos estĂŁo na fila para exclusĂŁo
 a| 
Quando *qualquer* das seguintes condiĂ§Ă”es for verdadeira:

* A exclusĂŁo automĂĄtica de objetos foi acionada por um dos seguintes eventos:
+
** A data de expiraĂ§ĂŁo ou o nĂșmero de dias na configuraĂ§ĂŁo do ciclo de vida de um bucket do S3 Ă© atingida.
** O Ășltimo perĂ­odo de tempo especificado em uma regra ILM decorre.


+
*ObservaĂ§ĂŁo:* objetos em um bucket que tenha o bloqueio de objeto S3 ativado nĂŁo podem ser excluĂ­dos se estiverem sob uma retenĂ§ĂŁo legal ou se uma data de retenĂ§ĂŁo atĂ© tiver sido especificada, mas ainda nĂŁo cumprida.

* Um cliente S3 solicita a exclusĂŁo e uma ou mais destas condiĂ§Ă”es Ă© verdadeira:
+
** As cĂłpias nĂŁo podem ser excluĂ­das dentro de 30 segundos porque, por exemplo, um local de objeto estĂĄ temporariamente indisponĂ­vel.
** As filas de exclusĂŁo em segundo plano estĂŁo ociosas.






 a| 
Os objetos sĂŁo removidos imediatamente (exclusĂŁo sĂ­ncrona)
 a| 
Quando um cliente S3 faz uma solicitaĂ§ĂŁo de exclusĂŁo e *todas* das seguintes condiĂ§Ă”es sĂŁo atendidas:

* Todas as cĂłpias podem ser removidas dentro de 30 segundos.
* As filas de exclusĂŁo em segundo plano contĂȘm objetos a serem processados.


|===
Quando os clientes S3 fazem solicitaĂ§Ă”es de exclusĂŁo, o StorageGRID comeĂ§a adicionando objetos Ă  fila de exclusĂŁo. Em seguida, ele alterna para executar a exclusĂŁo sĂ­ncrona. Certificar-se de que a fila de exclusĂŁo em segundo plano tem objetos para processar permite que o StorageGRID processe exclusĂ”es de forma mais eficiente, especialmente para clientes de baixa simultaneidade, ao mesmo tempo que ajuda a impedir que o cliente exclua backlogs.



[[time-required-to-delete-objects]]
== Tempo necessĂĄrio para excluir objetos

A forma como o StorageGRID exclui objetos pode afetar o desempenho do sistema:

* Quando o StorageGRID executa a exclusĂŁo sĂ­ncrona, pode levar StorageGRID atĂ© 30 segundos para retornar um resultado ao cliente. Isso significa que a exclusĂŁo pode parecer estar acontecendo mais lentamente, mesmo que as cĂłpias estejam sendo removidas mais rapidamente do que quando o StorageGRID coloca objetos em fila para exclusĂŁo.
* Se vocĂȘ estiver monitorando de perto o desempenho de exclusĂŁo durante uma exclusĂŁo em massa, vocĂȘ pode notar que a taxa de exclusĂŁo parece ser lenta apĂłs um certo nĂșmero de objetos ter sido excluĂ­do. Essa alteraĂ§ĂŁo ocorre quando o StorageGRID muda de enfileirar objetos para exclusĂŁo para a execuĂ§ĂŁo da exclusĂŁo sĂ­ncrona. A aparente reduĂ§ĂŁo na taxa de exclusĂŁo nĂŁo significa que as cĂłpias de objetos estejam sendo removidas mais lentamente. Pelo contrĂĄrio, indica que, em mĂ©dia, o espaĂ§o estĂĄ agora a ser libertado mais rapidamente.


Se vocĂȘ estiver excluindo grandes nĂșmeros de objetos e sua prioridade for liberar espaĂ§o rapidamente, considere usar uma solicitaĂ§ĂŁo de cliente para excluir objetos em vez de excluĂ­-los usando ILM ou outros mĂ©todos. Em geral, o espaĂ§o Ă© liberado mais rapidamente quando a exclusĂŁo Ă© realizada pelos clientes porque o StorageGRID pode usar a exclusĂŁo sĂ­ncrona.

A quantidade de tempo necessĂĄrio para liberar espaĂ§o depois que um objeto Ă© excluĂ­do depende de vĂĄrios fatores:

* Se as cĂłpias de objetos sĂŁo removidas de forma sĂ­ncrona ou estĂŁo em fila para serem removidas posteriormente (para solicitaĂ§Ă”es de exclusĂŁo de clientes).
* Outros fatores, como o nĂșmero de objetos na grade ou a disponibilidade de recursos da grade quando as cĂłpias de objetos sĂŁo enfileiradas para remoĂ§ĂŁo (para exclusĂ”es de clientes e outros mĂ©todos).




[[how-s3-versioned-objects-are-deleted]]
[[delete-s3-versioned-objects]]
== Como objetos com versĂŁo S3 sĂŁo excluĂ­dos

Quando o controle de versĂŁo estĂĄ habilitado para um bucket do S3, o StorageGRID segue o comportamento do Amazon S3 ao responder a solicitaĂ§Ă”es de exclusĂŁo, sejam elas provenientes de um cliente S3, a expiraĂ§ĂŁo de um ciclo de vida de bucket do S3 ou os requisitos da polĂ­tica do ILM.

Quando os objetos sĂŁo versionados, as solicitaĂ§Ă”es de exclusĂŁo de objetos nĂŁo excluem a versĂŁo atual do objeto e nĂŁo libertam espaĂ§o. Em vez disso, uma solicitaĂ§ĂŁo de exclusĂŁo de objeto cria um marcador de exclusĂŁo de byte zero como a versĂŁo atual do objeto, o que torna a versĂŁo anterior do objeto "nĂŁo atual". Um marcador de exclusĂŁo de objeto torna-se um marcador de exclusĂŁo de objeto expirado quando Ă© a versĂŁo atual e nĂŁo hĂĄ versĂ”es nĂŁo atuais.

Mesmo que o objeto nĂŁo tenha sido removido, o StorageGRID se comporta como se a versĂŁo atual do objeto nĂŁo estivesse mais disponĂ­vel. SolicitaĂ§Ă”es para esse objeto retornam 404 NotFound. No entanto, como os dados de objetos nĂŁo atuais nĂŁo foram removidos, as solicitaĂ§Ă”es que especificam uma versĂŁo nĂŁo atual do objeto podem ser bem-sucedidas.

Se um cliente excluir uma versĂŁo de objeto com um ID de versĂŁo de umlink:../tenant/what-is-branch-bucket.html["balde de galhos"] , StorageGRID oculta a existĂȘncia da versĂŁo do objeto, mas nĂŁo cria um marcador de exclusĂŁo no bucket de ramificaĂ§ĂŁo.  Se um cliente excluir um objeto sem um ID de versĂŁo de um bucket de ramificaĂ§ĂŁo, o StorageGRID criarĂĄ um marcador de exclusĂŁo no bucket de ramificaĂ§ĂŁo de acordo com o comportamento padrĂŁo do S3.

Para liberar espaĂ§o ao excluir objetos com controle de versĂŁo ou remover marcadores de exclusĂŁo, use um dos seguintes procedimentos:

* *SolicitaĂ§ĂŁo de cliente S3*: Especifique o ID da versĂŁo do objeto na solicitaĂ§ĂŁo DE EXCLUSĂO de objeto S3 (`DELETE /object?versionId=ID`). Tenha em mente que essa solicitaĂ§ĂŁo sĂł remove cĂłpias de objetos para a versĂŁo especificada (as outras versĂ”es ainda estĂŁo ocupando espaĂ§o).
* *Ciclo de vida do bucket*: Use a `NoncurrentVersionExpiration` aĂ§ĂŁo na configuraĂ§ĂŁo do ciclo de vida do bucket. Quando o nĂșmero de dias nĂŁo-correntes especificado Ă© atendido, o StorageGRID remove permanentemente todas as cĂłpias de versĂ”es de objetos nĂŁo-atuais. Essas versĂ”es de objeto nĂŁo podem ser recuperadas.
+
A `NewerNoncurrentVersions` aĂ§ĂŁo na configuraĂ§ĂŁo do ciclo de vida do bucket especifica o nĂșmero de versĂ”es nĂŁo atuais retidas em um bucket S3 com versĂŁo. Se houver mais versĂ”es nĂŁo atuais do que `NewerNoncurrentVersions` o especificado, o StorageGRID removerĂĄ as versĂ”es mais antigas quando o valor nĂŁo-atual tiver decorrido. O `NewerNoncurrentVersions` limite substitui as regras de ciclo de vida fornecidas pelo ILM, o que significa que um objeto nĂŁo atual com uma versĂŁo dentro do `NewerNoncurrentVersions` limite Ă© retido se o ILM solicitar sua exclusĂŁo.

+
Para remover marcadores de exclusĂŁo de objetos expirados, use a `Expiration` aĂ§ĂŁo com uma das seguintes tags: `ExpiredObjectDeleteMarker` `Days` , Ou `Date`.

* *ILM*: link:creating-ilm-policy.html["Clonar uma polĂ­tica ativa"] E adicione duas regras ILM Ă  nova polĂ­tica:
+
** Primeira regra: Use "tempo nĂŁo atual" como tempo de referĂȘncia para corresponder Ă s versĂ”es nĂŁo atuais do objeto. No link:create-ilm-rule-enter-details.html["Etapa 1 (Digite detalhes) do assistente criar uma regra ILM"], selecione *Sim* para a pergunta: "Aplicar esta regra apenas a versĂ”es de objetos mais antigas (em buckets do S3 com controle de versĂŁo ativado)?"
** Segunda regra: Use *tempo de ingestĂŁo* para corresponder Ă  versĂŁo atual. A regra "hora nĂŁo atual" deve aparecer na polĂ­tica acima da regra *tempo de ingestĂŁo*.
+
Para remover marcadores de exclusĂŁo de objetos expirados, use uma regra *tempo de ingestĂŁo* para corresponder aos marcadores de exclusĂŁo atuais. Os marcadores de exclusĂŁo sĂł sĂŁo removidos quando um *perĂ­odo de tempo* de *dias* passou e o criador de exclusĂŁo atual expirou (nĂŁo hĂĄ versĂ”es nĂŁo atuais).



* *Excluir objetos no bucket*: Use o gerenciador de locatĂĄrios para link:../tenant/deleting-s3-bucket-objects.html["eliminar todas as versĂ”es de objetos"], incluindo excluir marcadores, de um bucket.


Quando um objeto versionado Ă© excluĂ­do, o StorageGRID cria um marcador de exclusĂŁo de byte zero como a versĂŁo atual do objeto. Todos os objetos e marcadores de exclusĂŁo devem ser removidos antes que um bucket versionado possa ser excluĂ­do.

* Excluir marcadores criados no StorageGRID 11,7 ou anterior sĂł pode ser removido por meio de solicitaĂ§Ă”es de cliente S3, eles nĂŁo sĂŁo removidos pelo ILM, regras de ciclo de vida do bucket ou Excluir objetos em operaĂ§Ă”es de bucket.
* Excluir marcadores de um bucket criado no StorageGRID 11,8 ou posterior pode ser removido pelo ILM, regras de ciclo de vida do bucket, Excluir objetos em operaĂ§Ă”es de bucket ou uma exclusĂŁo explĂ­cita do cliente S3.


.InformaĂ§Ă”es relacionadas
* link:../s3/index.html["USE A API REST DO S3"]
* link:example-4-ilm-rules-and-policy-for-s3-versioned-objects.html["Exemplo 4: Regras ILM e polĂ­tica para objetos com versĂŁo S3"]

