---
permalink: release-notes/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: StorageGRID 12.1 utiliza a versão 4 da Grid Management API. A versão 4 descontinua a versão 3. No entanto, as versões 1, 2 e 3 ainda são suportadas. 
---
= Alterações na API de Gerenciamento de Grid no StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.1 utiliza a versão 4 da Grid Management API. A versão 4 torna a versão 3 obsoleta; no entanto, as versões 1, 2 e 3 ainda são suportadas.


NOTE: Você pode continuar usando versões obsoletas da API de gerenciamento com StorageGRID; no entanto, o suporte para essas versões da API será removido em uma versão futura do StorageGRID. Após atualizar para StorageGRID 12.0 ou posterior, você pode desativar as APIs obsoletas usando a  `PUT /grid/config/management` API.

Para saber mais, link:../admin/using-grid-management-api.html["Use a API de gerenciamento de grade"]acesse .



[[new-endpoints-for-changing-the-bmc-password-and-lan-ip-settings]]
== Novos endpoints para alterar a senha do BMC e as configurações de IP da LAN

O seguinte endpoint foi adicionado para permitir que você link:../harden/hardening-guidelines-for-storagegrid-nodes.html#change-appliance-bmc-password["alterar a senha do BMC de um appliance"].

`PUT /bmc-configuration/root-password`

Os seguintes endpoints foram adicionados para permitir que você link:../maintain/changing-nodes-network-configuration.html#change-appliance-node-bmc-lan-ip-settings["alterar ou visualizar as configurações de IP LAN do BMC"].

`PUT /grid/bmc/{node-id}/lan-ip-config`

`GET /grid/bmc/{node-id}/lan-ip-config`
