---
permalink: release-notes/whats-new.html 
sidebar: sidebar 
keywords: what is new in StorageGRID 12.1 
summary: Esta versão do StorageGRID introduz os seguintes recursos e alterações funcionais. 
---
= Novidades no StorageGRID 12.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.1 introduz os seguintes recursos e alterações funcionais.

Para obter detalhes sobre problemas corrigidos e problemas conhecidos nas versões recentes do StorageGRID 12.1, consulte a  https://library.netapp.com/ecm/ecm_download_file/ECMLP3373065["StorageGRID 12.1 Notas de lançamento"^]. Você precisa fazer login com sua NetApp conta ou criar uma conta para acessar as notas de versão.



[[capacity]]
== Capacidade



[[ec-rebalance-now-uses-free-space]]
=== O reequilíbrio da EC agora utiliza espaço livre

O rebalanceamento do EC agora usa espaço livre em vez de espaço usado. Consulte link:../expand/considerations-for-rebalancing-erasure-coded-data.html#what-is-ec-rebalancing["Saiba mais sobre o rebalanceamento de EC após a expansão no StorageGRID."].



[[metadata-allowed-space]]
=== Espaço permitido para metadados

Agora você pode aumentar o valor máximo permitido de metadados de 3,96 TB para 7,92 TB. Consulte link:../admin/managing-object-metadata-storage.html#allowed-metadata-space["Espaço de metadados permitido"].



[[control-access]]
== Controlar acesso



[[sso-using-oidc]]
=== SSO usando OIDC

Agora você pode link:../admin/learn-about-setting-up-sso-oidc.html["Configurar o login único (SSO) no StorageGRID usando o OpenID Connect (OIDC)"].



[[federation]]
== Federação



[[global-namespace]]
=== Espaço de nomes global

Agora você pode configurar um namespace global para permitir que os tenants acessem buckets em vários sistemas StorageGRID. Consulte link:../admin/learn-about-global-namespace.html["Saiba mais sobre o namespace global"].



[[manageability]]
== Gerenciabilidade



[[auto-move-adc-service]]
=== Serviço ADC de movimentação automática

link:../maintain/understanding-adc-service-quorum.html["Quando necessário para atingir o quórum do ADC"], o serviço ADC será movido automaticamente quando você estiver link:../maintain/convert-to-data-only-node.html["Convertendo um nó de armazenamento em um nó somente de dados"] ou link:../maintain/considerations-for-decommissioning-storage-nodes.html["desativando um nó de armazenamento"].



[[primary-admin-node-recovery]]
=== Recuperação do nó de administração primário

Agora você pode recuperar qualquer nó de um nó de administração que não seja o primário. Consulte link:../maintain/recovering-from-primary-admin-node-failures.html["Recuperando de falhas no nó de administração primário"].



[[s3]]
== S3



[[enable-s3-object-lock-on-existing-buckets]]
=== Ativar o bloqueio de objetos S3 em buckets existentes

Quando a configuração "Permitir S3 Object Lock para buckets existentes" está habilitada, uma conta de locatário S3 pode habilitar o S3 Object Lock para um bucket existente. Depois que uma conta de locatário S3 habilita o S3 Object Lock para um bucket existente, ele não pode ser desativado.



[[replication-allowed-for-s3-object-lock-enabled-buckets]]
=== A replicação é permitida para buckets com S3 Object Lock ativado

Agora você pode usar CloudMirror para replicar objetos em buckets do S3 com o recurso Object Lock ativado. Consulte link:../tenant/considerations-for-platform-services.html["Saiba mais sobre serviços de plataforma"].



[[enable-cross-grid-replication-for-non-empty-buckets]]
=== Ativar replicação entre grades para buckets não vazios

Agora você pode habilitar a replicação entre grades para buckets que não estão vazios. Consulte link:../admin/grid-federation-what-is-cross-grid-replication.html#requirements-for-cross-grid-replication["Requisitos para replicação entre grades"].



[[s3-batch-operations-fpvr-only]]
=== Operações em lote S3 (somente FPVR)

Você pode usar operações em lote do S3 para replicar objetos existentes em um bucket com controle de versão habilitado que você planeja configurar para replicação entre grids.

Este recurso requer aprovação da FPVR para StorageGRID 12.1. Para usar este recurso, entre em contato com seu representante de contas.



[[non-functional-s3-rest-api-headers]]
=== Cabeçalhos não funcionais da API REST S3

Os  `If-Match` e  `If-None-Match` cabeçalhos são aceitos, mas não funcionais para a API REST do S3 link:../s3/put-object.html["PutObject"], link:../s3/complete-multipart-upload.html["CompleteMultipartUpload"], link:../s3/put-object-copy.html["CopyObject"] e link:../s3/operations-on-objects.html["DeleteObject"].

Para obter informações adicionais, consulte link:../release-notes/changes-to-s3-rest-api.html["Alterações no suporte à API REST S3 do StorageGRID"].



[[support-for-pre-calculated-checksum-values]]
=== Suporte para valores de checksum pré-calculados

A SPI REST do S3 agora oferece suporte a valores de checksum pré-calculados e ao cabeçalho de solicitação  `x-amz-checksum-type`. Consulte link:../s3/index.html#updates-to-rest-api-support["Atualizações no suporte à API REST"].



[[security]]
== Segurança



[[multi-admin-verification]]
=== Verificação de múltiplos administradores

A verificação multi-administrador (MAV) ajuda a prevenir alterações acidentais ou não autorizadas no seu sistema StorageGRID. Consulte link:../admin/about-multi-admin-verify.html["Saiba mais sobre a verificação de múltiplos administradores do StorageGRID"].



[[security-policy-updates-for-fips]]
=== Atualizações de política de segurança para FIPS

Os critérios rigorosos da política FIPS foram atualizados. Consulte link:../admin/manage-tls-ssh-policy.html#select-a-security-policy["Selecione uma política de segurança em Gerenciar a política de TLS e SSH"].



[[tenants]]
== Inquilinos



[[account-sync]]
=== Sincronização de contas

O recurso _clonagem de conta_ agora se refere a uma clonagem única de informações específicas da conta do locatário.

A _sincronização de contas_ é um novo recurso que permite a você replicar automaticamente e de forma contínua contas de locatário, grupos de locatários, usuários de locatário e chaves de acesso S3 entre os sistemas StorageGRID em uma ou mais conexões de federação de grid. Consulte link:../admin/grid-federation-what-is-account-sync.html["Saiba mais sobre a sincronização de contas no StorageGRID"].



[[kafka-endpoints-and-mtls-authentication]]
=== Endpoints do Kafka e autenticação mTLS

A segurança da camada de transporte mútua (mTLS) agora é compatível com endpoints do Kafka. Consulte link:../tenant/configuring-platform-services-endpoints.html["Configurar endpoints de serviços de plataforma"].



[[maximum-number-of-buckets]]
=== Número máximo de buckets

Um sistema StorageGRID agora suporta um máximo de 20.000 buckets para cada conta de locatário S3.



[[upgrade]]
== Atualizar



[[time-to-enable-features-is-increased]]
=== O tempo para ativar os recursos aumentou

Durante a atualização do StorageGRID para a versão 12.1, o tempo para ativar recursos aumentou de menos de cinco minutos para uma hora. Consulte link:../upgrade/estimating-time-to-complete-upgrade.html#estimate-time-to-upgrade["Estime o tempo necessário para concluir uma atualização do StorageGRID"].



[[user-interface]]
== Interface do usuário



[[bmc-settings-page]]
=== Página de configurações do BMC

Uma nova guia BMC Settings foi adicionada à página Nodes no Grid Manager para permitir a redefinição da senha do BMC e alterações nas configurações de IP da LAN do BMC. Consulte link:../harden/hardening-guidelines-for-storagegrid-nodes.html["Alterar a senha do BMC do appliance"] e link:../maintain/changing-nodes-network-configuration.html#change-appliance-node-bmc-lan-ip-settings["Alterar as configurações de endereço IP da LAN do BMC do nó do appliance"]. Novos endpoints de API também foram adicionados para dar suporte a essas funções. Consulte link:../release-notes/changes-to-grid-management-api.html["Novos endpoints para alterar a senha do BMC e as configurações de IP da LAN"].



[[email-notifications]]
=== Notificações por e-mail

O Gerenciador de Grade agora possui uma página de e-mail comum para configurar e gerenciar notificações por e-mail para alertas, AutoSupport e verificação multi-administrador (MAV). Consulte link:../monitor/configure-email-server.html["Configurar servidor de e-mail"].



[[link-cost-page-update]]
=== Atualização da página de custo de link

StorageGRID 12.1 fornece informações e configurações mais detalhadas sobre o custo do link. Consulte link:../admin/manage-link-costs.html["Gerenciar custos de link"].



[[usb-port-control]]
=== Controle da porta USB

Agora você pode ativar ou desativar portas USB através do Grid Manager. Consulte link:../harden/hardening-guidelines-for-storagegrid-nodes.html#control-remote-access-through-usb-ports["Controle o acesso remoto por meio de portas USB"].
